/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Dashboard Analytics & AI Insights
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see README/INTEGRATION_NOTES.md at the project root.
 * ============================================================================= */
/**
 * AI Analytics Insights — POST /api/trips/:id/insights
 *
 * Powers the "Generate Insights" button on the Dashboard's Analytics tab
 * (a one-shot report generator, not a chatbot). Sends a single, controlled
 * snapshot of the trip/kpis/coach breakdown/missing list to an LLM and asks
 * for a short written summary. No conversation history, no arbitrary page
 * content — only this developer-authored snapshot ever leaves the server.
 *
 * Tries a local Ollama server first (free, no API key, no data leaves the
 * machine) and falls back to the Anthropic API if Ollama isn't running.
 * Both are optional and lazily checked — a missing/unreachable Ollama or a
 * missing ANTHROPIC_API_KEY can never crash server startup, only shape the
 * response of this one route.
 */

import { Router } from "express";
import { getTrip, getDashboard, getMissing, resolveTripUuid, COACHES } from "../../data.js";
import { requireAuth } from "../../lib/auth.js";

const router = Router();

const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

// Fixed 3-section structure the model must follow, per language — the
// frontend (AnalyticsPanel.jsx) bolds whatever text comes before the first
// colon on each line, so keeping these exact label strings is what makes
// the rendered output look like "Overall: ... / Missing: ... / Advice: ...".
const SECTION_LABELS = {
  en: { overall: "Overall", missing: "Missing", advice: "Advice" },
  zh: { overall: "总体情况", missing: "缺席情况", advice: "建议" },
};

function buildPrompt(snapshot, lang) {
  const labels = SECTION_LABELS[lang] || SECTION_LABELS.en;
  const languageInstruction =
    lang === "zh"
      ? "Write your entire response in Simplified Chinese (简体中文), including the three labels below exactly as given."
      : "Write your entire response in English.";

  return `You are generating a short internal briefing for SCCCI delegation staff, based on a live attendance snapshot taken at ${snapshot.asOf}.

Trip: ${snapshot.trip.name} (${snapshot.trip.dateRange}), Day ${snapshot.trip.dayOf} of ${snapshot.trip.totalDays}. Local time ${snapshot.trip.localTime}. Departs in ${snapshot.trip.departsIn}.

Totals: ${snapshot.kpis.total} delegates · ${snapshot.kpis.present} present · ${snapshot.kpis.missing} missing · ${snapshot.kpis.unassigned} unassigned.

Coaches:
${snapshot.coaches.map((c) => `- ${c.name}${c.city ? ` (${c.city})` : ""}: ${c.boarded}/${c.capacity} boarded, ${c.missing} missing`).join("\n")}

Missing delegates (${snapshot.missing.length}):
${snapshot.missing.length === 0 ? "(none)" : snapshot.missing.map((m) => `- ${m.name}${m.vip ? " (VIP)" : ""} · ${m.coach} · last seen: ${m.lastSeen || "unknown"}`).join("\n")}

Write EXACTLY 3 numbered points, one per line, in this fixed structure:
1. ${labels.overall}: overall attendance health — the specific numbers present/missing/unassigned out of the total, and whether that's on track for departure.
2. ${labels.missing}: which delegates and/or coaches are missing, naming the ones with the most missing (coach names, delegate names) and flagging any VIP delegates among them.
3. ${labels.advice}: concrete next actions staff should take right now — e.g. which coach's guide to contact first, whether to call a delegate directly using their last-seen location, or escalate a VIP delegate's absence.

Each point must start with its real number (1, 2, or 3), a period, a space, the exact label text given above, then a colon — for example the first point must literally begin "1. ${labels.overall}: " (substitute the real digit and label for points 2 and 3 the same way; never write the letter N or the word "Label" — those are not real output). Follow the label with one or two direct sentences containing the specific numbers/names it's based on — no vague language. No markdown, no headers, no intro/closing sentence — just the 3 numbered points. Be direct and factual — this is read by busy staff, not a general audience. ${languageInstruction}`;
}

/** Try a local Ollama server. Returns the generated text, or null if Ollama isn't reachable. */
// `numPredict` caps generated tokens — local CPU inference time scales
// roughly with output length, so the tiny ai-chart JSON reply (~15 tokens)
// was previously left uncapped and generating far past when the real
// answer was done (2026-07-24 — "can you improve the loading time on
// it?"). `keep_alive` keeps the model resident between calls so a request
// a few minutes after the last one skips a full cold-load.
async function tryOllama(prompt, { json = false, numPredict } = {}) {
  const base = process.env.OLLAMA_HOST || "http://localhost:11434";
  const model = process.env.OLLAMA_MODEL || "llama3.2";

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 45000); // local CPU inference can be slow
  try {
    const res = await fetch(`${base}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        messages: [{ role: "user", content: prompt }],
        stream: false,
        keep_alive: "30m",
        ...(json ? { format: "json" } : {}),
        ...(numPredict ? { options: { num_predict: numPredict } } : {}),
      }),
      signal: controller.signal,
    });
    if (!res.ok) return null;
    const data = await res.json();
    const text = data?.message?.content?.trim();
    return text || null;
  } catch {
    return null; // Ollama not installed/running — fall back to Anthropic
  } finally {
    clearTimeout(timer);
  }
}

/** Call the Anthropic API. Throws on failure; caller handles the error response. */
async function callAnthropic(prompt, maxTokens = 400) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;

  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const anthropic = new Anthropic({ apiKey });
  const model = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-5-20250929";

  const response = await anthropic.messages.create({
    model,
    max_tokens: maxTokens,
    messages: [{ role: "user", content: prompt }],
  });

  return (response.content || [])
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("\n")
    .trim();
}

// Pull the first {...} out of a model reply (handles chatty models that wrap
// JSON in prose despite instructions) — same approach as export.js's own
// extractJson(), duplicated rather than imported since these are two
// separate small AI-prompt features with no other shared code.
function extractJson(text) {
  if (!text) return null;
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  try { return JSON.parse(text.slice(start, end + 1)); } catch { return null; }
}

const CHART_TYPES = ["bar", "pie", "donut", "line"];
const CHART_GROUP_BY = ["status", "coach", "company", "industry", "vip"];

function buildChartPrompt(request) {
  return `You pick a chart configuration for a delegate-attendance analytics dashboard. Output ONLY a JSON object, no prose, no markdown.

Available chart types: ${CHART_TYPES.map((c) => `"${c}"`).join(", ")}.
Available group-by fields:
- "status" — Arrived/Assigned/Late/Missing/Unassigned counts
- "coach" — which coach/bus each delegate is on
- "company" — delegate's company
- "industry" — delegate's industry
- "vip" — VIP vs non-VIP

Any request mentioning an ATTENDANCE STATE word — "missing", "late", "arrived",
"assigned", "unassigned", "checked in", "boarded", "not boarded", "who hasn't
shown up" — MUST use groupBy "status", even if the request ALSO mentions VIPs
(e.g. "how many VIPs are missing" is still groupBy "status", not "vip" — the
chart is about attendance state; VIP is only a filter, not what's being
counted here since there is no separate VIP filter field). Only use groupBy
"vip" when the request is SPECIFICALLY about the VIP/non-VIP split itself and
mentions no attendance state (e.g. "VIP vs non-VIP breakdown", "how many VIPs
do we have").

There is no time/date field available at all — do NOT pick "line" just
because the request says "over time" or "trend" unless it's really asking to
compare across the categories above (e.g. "trend by coach" still means
groupBy "coach"); a request that's ONLY about literal calendar time with no
other real dimension has no good answer here, so fall back to
{"chartType": "bar", "groupBy": "status"} instead of guessing a field that
doesn't represent time at all.

Pick whichever chart type and group-by field best match the request. A part-of-whole request ("breakdown", "proportion", "%") should prefer "pie" or "donut"; a per-category comparison ("by coach", "by company") should prefer "bar". If genuinely unclear, default to {"chartType": "bar", "groupBy": "status"}.

Return EXACTLY this shape:
{"chartType": "bar", "groupBy": "status"}

Staff request: "${String(request).slice(0, 300)}"

JSON:`;
}

function sanitizeChartChoice(raw) {
  return {
    chartType: CHART_TYPES.includes(raw?.chartType) ? raw.chartType : "bar",
    groupBy: CHART_GROUP_BY.includes(raw?.groupBy) ? raw.groupBy : "status",
  };
}

// Natural-language → chart config, for the Analytics tab's custom chart
// builder (2026-07-24). Bounded the same way export.js's ai-filter is: the
// model only ever picks from a fixed enum of chart types/fields, never sees
// or writes actual delegate data, and the UI shows the result in the SAME
// editable dropdowns the manual builder uses — this is a starting point, not
// a black box.
router.post("/api/trips/:id/analytics/ai-chart", requireAuth(), wrap(async (req, res) => {
  const request = (req.body?.prompt || "").toString().trim();
  if (!request) return res.status(400).json({ error: "NO_PROMPT", message: "Describe what you want to see." });

  const prompt = buildChartPrompt(request);
  let parsed = extractJson(await tryOllama(prompt, { json: true, numPredict: 40 }));
  if (!parsed) {
    try { parsed = extractJson(await callAnthropic(prompt, 40)); }
    catch (err) { console.error("Analytics AI-chart call failed:", err.message || err); }
  }
  if (!parsed) {
    return res.status(503).json({
      error: "AI_NOT_CONFIGURED",
      message: "Install Ollama locally (free) or ask an admin to set ANTHROPIC_API_KEY in backend/.env.",
    });
  }
  res.json(sanitizeChartChoice(parsed));
}));

router.post(
  "/api/trips/:id/insights",
  requireAuth(),
  wrap(async (req, res) => {
    // 2026-07-24 fix: this used to call getTrip()/getDashboard()/getMissing()
    // with NO arguments, i.e. always the base/default trip regardless of
    // req.params.id — "Generate Insights" silently described the base trip
    // no matter which trip's Analytics tab you were actually on.
    const tripUuid = await resolveTripUuid(req.params.id);
    const [trip, dashboard, missing] = await Promise.all([getTrip(tripUuid), getDashboard(tripUuid), getMissing(tripUuid)]);
    const snapshot = {
      asOf: new Date().toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" }),
      trip,
      kpis: dashboard.kpis,
      coaches: dashboard.coaches.length ? dashboard.coaches : COACHES,
      missing,
    };
    const lang = req.body?.lang === "zh" ? "zh" : "en";
    const prompt = buildPrompt(snapshot, lang);

    // 1. Try local Ollama first — free, no key, nothing leaves the machine.
    const ollamaText = await tryOllama(prompt, { numPredict: 260 });
    if (ollamaText) {
      return res.json({ insights: ollamaText, asOf: snapshot.asOf, source: "ollama" });
    }

    // 2. Fall back to the Anthropic API.
    try {
      const anthropicText = await callAnthropic(prompt);
      if (anthropicText) {
        return res.json({ insights: anthropicText, asOf: snapshot.asOf, source: "anthropic" });
      }
    } catch (err) {
      console.error("Anthropic insights call failed:", err.message || err);
      return res.status(502).json({
        error: "AI_SERVICE_ERROR",
        message: "AI insights are temporarily unavailable. Please try again shortly.",
      });
    }

    // Neither Ollama nor an Anthropic key is available.
    res.status(503).json({
      error: "AI_NOT_CONFIGURED",
      message: "Install Ollama locally (free) or ask an admin to set ANTHROPIC_API_KEY in backend/.env.",
    });
  })
);

export default router;
