/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see OWNSHIP.md at the project root.
 * ============================================================================= */
/** Account control + Staff Operations routes. Everything here requires the
 * "manageAccounts" permission. */
import { Router } from "express";
import { wrap } from "../lib/wrap.js";
import { makeToken, requirePermission, requireAccountsView } from "../lib/auth.js";
import {
  listAccounts, createAccount, updateAccount, deleteAccount, listActiveAccounts,
  listRoleTemplates, createRoleTemplate, updateRoleTemplate, deleteRoleTemplate,
  listPendingAccounts, approveAccount, rejectAccount, approveAllPending, rejectAllPending,
} from "../data.js";

const router = Router();

/**
 * GET /api/staff/active-sessions — "Active" = last_seen_at within 45s, stamped
 * by the 15s session-poll clients already make (touchLastSeen() in data.js).
 * Deliberately no new polling infra.
 */
router.get("/api/staff/active-sessions", requireAccountsView(), wrap(async (_req, res) => {
  const [all, active] = await Promise.all([listAccounts(), listActiveAccounts()]);
  // role is "admin" or "staff" only (cleanRole()/accountPublic() in data.js).
  const adminCount = all.filter((a) => a.role === "admin").length;
  const staffCount = all.length - adminCount;
  res.json({ totalStaff: all.length, adminCount, staffCount, activeCount: active.length, active });
}));

router.get("/api/accounts", requireAccountsView(), wrap(async (_req, res) => {
  res.json({ accounts: await listAccounts() });
}));

router.post("/api/accounts", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await createAccount(req.body || {});
  if (result.error) return res.status(accountErrStatus(result.error)).json(result);
  res.status(201).json(result.account);
}));

router.patch("/api/accounts/:id", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await updateAccount(req.params.id, req.body || {});
  if (result.error) return res.status(accountErrStatus(result.error)).json(result);
  // Editing your OWN account returns a fresh token for the (possibly new)
  // username so the client keeps working. Must reuse the current token_version
  // — bumping it would invalidate this very browser's session.
  const isSelf = req.account && req.account.id === req.params.id;
  res.json({
    account: result.account,
    self: !!isSelf,
    token: isSelf ? makeToken(result.account.username, req.account.token_version ?? 0) : undefined,
  });
}));

router.delete("/api/accounts/:id", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await deleteAccount(req.params.id);
  if (result.error) return res.status(accountErrStatus(result.error)).json(result);
  res.json(result);
}));

// Self-registration approval queue — "Pending approval" section on Account
// control. Same manageAccounts gate as the rest of this file.
router.get("/api/accounts/pending", requireAccountsView(), wrap(async (_req, res) => {
  res.json({ accounts: await listPendingAccounts() });
}));

router.post("/api/accounts/:id/approve", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await approveAccount(req.params.id);
  if (result.error) return res.status(accountErrStatus(result.error)).json(result);
  res.json(result.account);
}));

router.post("/api/accounts/:id/reject", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await rejectAccount(req.params.id);
  if (result.error) return res.status(accountErrStatus(result.error)).json(result);
  res.json(result.account);
}));

// "Approve all"/"Reject all". Static paths, not /:id, so no route-ordering
// conflict with the two routes above.
router.post("/api/accounts/pending/approve-all", requirePermission("manageAccounts"), wrap(async (_req, res) => {
  res.json(await approveAllPending());
}));

router.post("/api/accounts/pending/reject-all", requirePermission("manageAccounts"), wrap(async (_req, res) => {
  res.json(await rejectAllPending());
}));

// Role templates — "Manage roles" screen. Same manageAccounts gate: editing a
// role is itself an account-administration action.
router.get("/api/role-templates", requireAccountsView(), wrap(async (_req, res) => {
  res.json({ templates: await listRoleTemplates() });
}));

router.post("/api/role-templates", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await createRoleTemplate(req.body || {});
  if (result.error) return res.status(result.error === "LABEL_REQUIRED" ? 400 : 400).json(result);
  res.status(201).json(result.template);
}));

router.patch("/api/role-templates/:id", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await updateRoleTemplate(req.params.id, req.body || {});
  if (result.error) return res.status(result.error === "NOT_FOUND" ? 404 : 400).json(result);
  res.json(result.template);
}));

router.delete("/api/role-templates/:id", requirePermission("manageAccounts"), wrap(async (req, res) => {
  const result = await deleteRoleTemplate(req.params.id);
  if (result.error) return res.status(404).json(result);
  res.json(result);
}));

function accountErrStatus(code) {
  if (code === "NOT_FOUND") return 404;
  if (code === "USERNAME_TAKEN" || code === "EMAIL_TAKEN") return 409;
  if (code === "LAST_MAIN") return 409;
  return 400; // USERNAME_REQUIRED / PASSWORD_REQUIRED / WEAK_PASSWORD / EMAIL_REQUIRED
}

export default router;
