/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see OWNSHIP.md at the project root.
 * ============================================================================= */
/** Delegate CRUD + profile photo routes — split out of server.js (2026-07-21). */
import { Router } from "express";
import multer from "multer";
import { wrap } from "../lib/wrap.js";
import { actorOf } from "../lib/actor.js";
import { requireAuth, requirePermission } from "../lib/auth.js";
import { isConfigured as photoStorageConfigured, uploadImage, destroyImage } from "../lib/cloudinary.js";
import {
  resolveTripUuid,
  listDelegates,
  getDelegateById,
  createDelegate,
  updateDelegate,
  deleteDelegate,
  deleteAllDelegates,
  setDelegatePhoto,
  clearDelegatePhoto,
} from "../data.js";
import { syncCurrentCheckpointStatus } from "./checkpoints.js";

const router = Router();

// Delegate photo uploads — memory storage (never touches local disk; the
// buffer goes straight to Cloudinary). 5MB cap and an image-only MIME
// filter are the first layer of validation; Cloudinary's own image decode
// (resource_type: "image" in cloudinary.js) is the second, real one — it
// rejects anything that isn't actually a valid image regardless of what
// the client claimed.
const photoUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    if (!file.mimetype.startsWith("image/")) return cb(new Error("UNSUPPORTED_TYPE"));
    cb(null, true);
  },
});

router.get("/api/trips/:id/delegates", requireAuth(), wrap(async (req, res) => {
  res.json({ delegates: await listDelegates(await resolveTripUuid(req.params.id)) });
}));

// DELETE all delegates (dashboard "Delete all" button) — scoped to whichever
// trip is currently selected; the base t-1 view (resolveTripUuid -> null)
// keeps the original "clear everything" behaviour.
router.delete("/api/trips/:id/delegates", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const deleted = await deleteAllDelegates(await resolveTripUuid(req.params.id), actorOf(req));
  res.json({ deleted });
}));

router.post("/api/trips/:id/delegates", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const body = req.body || {};
  if (!body.name || !body.name.trim()) {
    return res.status(400).json({ error: "NAME_REQUIRED", message: "A name is required." });
  }
  // A coach is required unless the delegate is explicitly Unassigned.
  if (body.status && body.status !== "UNASSIGNED" && !body.coachId) {
    return res.status(400).json({ error: "COACH_REQUIRED", message: "Please select a coach, or set status to Unassigned." });
  }
  const delegate = await createDelegate(body, await resolveTripUuid(req.params.id), actorOf(req));
  res.status(201).json(delegate);
}));

router.patch("/api/delegates/:id", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const patch = req.body || {};
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });
  // Validate against the RESULT of applying this patch, not just the patch
  // alone — e.g. changing only the status on an already-unassigned delegate
  // still needs a coach if the new status isn't Unassigned.
  const nextStatus = patch.status !== undefined ? patch.status : existing.status;
  const nextCoachId = patch.coachId !== undefined ? patch.coachId : existing.coachId;
  if (nextStatus !== "UNASSIGNED" && !nextCoachId) {
    return res.status(400).json({ error: "COACH_REQUIRED", message: "Please select a coach, or set status to Unassigned." });
  }
  const updated = await updateDelegate(req.params.id, patch, actorOf(req));
  if (!updated) return res.status(404).json({ error: "NOT_FOUND" });
  // Keep the checkpoint-scoped view (checkpoint_checkins) honest when staff
  // manually correct a delegate's status by hand — see
  // syncCurrentCheckpointStatus() in routes/checkpoints.js for why.
  if (patch.status !== undefined) {
    syncCurrentCheckpointStatus(req.params.id, existing.trip_id, updated.status, actorOf(req));
  }
  res.json(updated);
}));

router.delete("/api/delegates/:id", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const existing = await getDelegateById(req.params.id);
  const ok = await deleteDelegate(req.params.id, actorOf(req));
  if (!ok) return res.status(404).json({ error: "NOT_FOUND" });
  if (existing?.photoPublicId) await destroyImage(existing.photoPublicId); // clean up Cloudinary too
  res.json({ deleted: true });
}));

/* ---- Delegate profile photo (Cloudinary) ----------------------------------
 * Separate from the JSON PATCH route above on purpose — see the comment on
 * the "photoUrl" column in data.js's createSchema(). multer parses the
 * multipart body into req.file (memory buffer, never written to disk).
 * ------------------------------------------------------------------------- */
router.post("/api/delegates/:id/photo", requirePermission("manageDelegates"), (req, res, next) => {
  photoUpload.single("photo")(req, res, (err) => {
    if (err) {
      const code = err.message === "UNSUPPORTED_TYPE" ? "UNSUPPORTED_TYPE" : "UPLOAD_FAILED";
      const message = code === "UNSUPPORTED_TYPE" ? "Please upload an image file." : "Upload too large (5MB max) or failed.";
      return res.status(400).json({ error: code, message });
    }
    next();
  });
}, wrap(async (req, res) => {
  if (!photoStorageConfigured()) {
    return res.status(503).json({ error: "PHOTO_STORAGE_NOT_CONFIGURED", message: "Photo storage isn't set up on this server yet." });
  }
  if (!req.file) return res.status(400).json({ error: "FILE_REQUIRED", message: "Please choose an image." });
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });

  const { url, publicId } = await uploadImage(req.file.buffer, "mustergo/delegates");
  const oldPublicId = await setDelegatePhoto(req.params.id, url, publicId);
  if (oldPublicId) await destroyImage(oldPublicId); // replacing a photo — clean up the old asset

  res.json({ photoUrl: url });
}));

router.delete("/api/delegates/:id/photo", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const oldPublicId = await clearDelegatePhoto(req.params.id);
  if (oldPublicId === null) return res.status(404).json({ error: "NOT_FOUND" });
  if (oldPublicId) await destroyImage(oldPublicId);
  res.json({ deleted: true });
}));

export default router;
