/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Emergency escalations
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see README/INTEGRATION_NOTES.md at the project root.
 * ============================================================================= */
/**
 * "Escalate to office" (2026-07-24) — built from real user testing feedback:
 * staff on-site sometimes can't reach a delegate by phone and need a fast way
 * to pull in offsite admin/office staff to help. Explicitly a MANUAL,
 * staff-clicked action, never automatic — see the big comment in
 * db/escalations.js.
 *
 * Three notification tiers on create:
 *   1. In-app: any signed-in account polls GET /api/escalations/open (see
 *      EscalationBanner.jsx) — no permission gate on reading this, since an
 *      emergency should be visible to whoever's signed in, not just admins.
 *   2. Tab-flash/chime — entirely frontend, no backend involvement.
 *   3. Email (live) + SMS/WhatsApp (stubbed, no paid provider wired in) —
 *      see lib/notify.js for exactly what's real vs. what needs a Twilio
 *      account to actually fire.
 */
import { Router } from "express";
import { wrap } from "../lib/wrap.js";
import { requireAuth, requirePermission } from "../lib/auth.js";
import { actorOf } from "../lib/actor.js";
import { all } from "../db/connection.js";
import { createEscalation, listOpenEscalations, listActiveEscalations, acknowledgeEscalation, acknowledgeAllOpen, resolveEscalation } from "../db/escalations.js";
import { sendEscalationEmails, sendEscalationSms, sendEscalationWhatsApp, buildEscalationHtml } from "../lib/notify.js";

const router = Router();

/** Every admin account with an email on file — the pool of people the
 *  frontend's Escalate modal lets staff pick from (2026-07-24, "on frontend
 *  I can choose who to alert to"). Exposes only what's needed to pick a
 *  recipient (name/email), not the full account record.
 *
 *  When a tripId is given, whoever's name matches that trip's free-text
 *  `lead` field (Desmond's TransitFlow field — a plain name, not a real
 *  foreign key to accounts) is flagged `isTripLead` and sorted first — a
 *  smarter DEFAULT, not a hard restriction. Deliberately not narrowing who
 *  CAN be alerted: `lead` is just a display string with no guaranteed match,
 *  and an emergency is exactly the wrong place to silently under-alert if
 *  the name match misses. Every admin still appears and stays checked by
 *  default in the picker; the trip lead just floats to the top. */
async function listRecipientCandidates(tripId) {
  const rows = await all(
    `SELECT id, name, username, email FROM accounts
     WHERE email IS NOT NULL AND status = 'approved' AND role = 'admin'
     ORDER BY name`
  );
  let leadName = null;
  if (tripId) {
    const trip = await all(`SELECT "lead" FROM trips WHERE uuid_id = $1`, [tripId]);
    leadName = (trip[0]?.lead || "").trim().toLowerCase() || null;
  }
  const tagged = rows.map((r) => ({ ...r, isTripLead: !!leadName && r.name?.trim().toLowerCase() === leadName }));
  tagged.sort((a, b) => (b.isTripLead - a.isTripLead) || a.name.localeCompare(b.name));
  return tagged;
}

/** Who actually receives the email. Priority order:
 *   1. `recipientEmails` explicitly chosen on the frontend for THIS escalation.
 *   2. ESCALATION_EMAIL_TO env override (comma-separated), for a deployment
 *      that wants a fixed list regardless of what's picked in the UI.
 *   3. Every admin account's own email, as a default so this still works
 *      out of the box before anyone's picked anything. */
async function resolveEmailRecipients(recipientEmails) {
  if (Array.isArray(recipientEmails) && recipientEmails.length) {
    return recipientEmails.map((e) => String(e).trim()).filter(Boolean);
  }
  const override = (process.env.ESCALATION_EMAIL_TO || "").split(",").map((s) => s.trim()).filter(Boolean);
  if (override.length) return override;
  const rows = await listRecipientCandidates();
  return rows.map((r) => r.email).filter(Boolean);
}

router.get("/api/escalations/recipients", requireAuth(), wrap(async (req, res) => {
  res.json({ recipients: await listRecipientCandidates(req.query.tripId) });
}));

router.post("/api/escalations", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const { tripId, delegateId, message, recipientEmails } = req.body || {};
  const escalation = await createEscalation({ tripId, delegateId, message }, actorOf(req));

  // Dedupe hit (2026-07-25) — same delegate already has an open escalation,
  // so this is a re-click, not a new emergency. Skip re-notifying entirely
  // (that's the actual spam this guards against) and tell the frontend so
  // it can show "already escalated" instead of a fresh success message.
  if (escalation.alreadyOpen) {
    return res.status(200).json({ escalation, alreadyOpen: true, notified: null });
  }

  // Delegate detail for the richer email (phone, last location) — a small
  // extra query, but escalations are rare/low-frequency so this is cheap.
  let delegate = null;
  if (escalation.delegateId) {
    const rows = await all(`SELECT name, phone, "lastLocation" FROM delegates WHERE id = $1`, [escalation.delegateId]);
    delegate = rows[0] || null;
  }
  let tripName = null;
  if (escalation.tripId) {
    const rows = await all(`SELECT name FROM trips WHERE uuid_id = $1`, [escalation.tripId]);
    tripName = rows[0]?.name || null;
  }

  const actor = actorOf(req) || "A staff member";
  // No emoji / "urgent"-sounding wording in the subject (2026-07-25) — a
  // spam-filter mitigation; the actual fix for landing in spam is proper
  // domain authentication (see THIRD_PARTY_SERVICES.md), this just removes
  // an easy, free thing to stop tripping content-based filters.
  const subject = `MusterGo — assistance needed${delegate ? ` for ${delegate.name}` : ""}`;
  const text = [
    `${actor} escalated an issue and needs help from the office.`,
    delegate?.name ? `\nDelegate: ${delegate.name}` : "",
    tripName ? `\nTrip: ${tripName}` : "",
    escalation.message ? `\nDetails: ${escalation.message}` : "",
    delegate?.phone ? `\nPhone: ${delegate.phone}` : "",
    delegate?.lastLocation ? `\nLast known location: ${delegate.lastLocation}` : "",
    `\nOpen the Dashboard to see full context and acknowledge this alert.`,
  ].join("");
  const html = buildEscalationHtml({
    actor, message: escalation.message, delegateName: delegate?.name,
    phone: delegate?.phone, lastLocation: delegate?.lastLocation, tripName,
  });

  const recipients = await resolveEmailRecipients(recipientEmails);
  const emailSent = await sendEscalationEmails(recipients, { subject, text, html });
  const sms = await sendEscalationSms(text);
  const whatsapp = await sendEscalationWhatsApp(text);

  res.status(201).json({ escalation, alreadyOpen: false, notified: { emailSent, sms, whatsapp, to: recipients } });
}));

router.get("/api/escalations/open", requireAuth(), wrap(async (_req, res) => {
  res.json({ escalations: await listOpenEscalations() });
}));

// Feeds the Alerts modal's "Emergency" section (2026-07-25) — open AND
// acknowledged, so an escalation stays reviewable/actionable until someone
// explicitly resolves it, instead of vanishing the moment it's acknowledged.
router.get("/api/escalations/active", requireAuth(), wrap(async (_req, res) => {
  res.json({ escalations: await listActiveEscalations() });
}));

router.post("/api/escalations/:id/acknowledge", requireAuth(), wrap(async (req, res) => {
  const result = await acknowledgeEscalation(req.params.id, actorOf(req));
  if (result.error) return res.status(result.error === "NOT_FOUND" ? 404 : 409).json(result);
  res.json(result);
}));

// Bulk-acknowledge every currently open escalation (2026-07-25) — the top
// banner's Acknowledge button uses this instead of one-at-a-time, so 50
// open escalations don't mean 50 clicks. Everything acknowledged this way
// still shows up in the Alerts modal's Emergency section — nothing is lost,
// just cleared off the banner in one go.
router.post("/api/escalations/acknowledge-all", requireAuth(), wrap(async (req, res) => {
  res.json(await acknowledgeAllOpen(actorOf(req)));
}));

router.post("/api/escalations/:id/resolve", requireAuth(), wrap(async (req, res) => {
  const result = await resolveEscalation(req.params.id, actorOf(req));
  if (result.error) return res.status(404).json(result);
  res.json(result);
}));

export default router;
