/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * PostgreSQL data layer for the MusterGo dashboard — BARREL FILE.
 *
 * Split into backend/db/*.js by domain on 2026-07-21 (this file used to be
 * ~1075 lines of connection setup + schema + delegates + accounts +
 * dashboard views + history all in one place). This file's only job now is
 * to re-export everything from those submodules under the exact same names,
 * so every existing `import { X } from "../data.js"` (or "./data.js")
 * elsewhere in the backend — auth.js, server.js, routes/desmond.js,
 * routes/exceptions.js, routes/vance.js, routes/vimal.js, routes/export.js,
 * routes/insights.js, routes/media.js, seed-demo.js, seed-team.js,
 * reset-login.js — keeps working completely unchanged. Nobody else's
 * imports needed to change for this split.
 *
 *   backend/db/connection.js  — pool + all()/get()/run() query helpers
 *   backend/db/constants.js   — TRIP, COACHES (seed fixtures)
 *   backend/db/schema.js      — createSchema(), seed() (called by initDb below)
 *   backend/db/accounts.js    — accounts, permissions, password hashing
 *   backend/db/delegates.js   — delegate CRUD, photos, late-cutoff, rollback
 *   backend/db/dashboard.js   — derived read views (getDashboard, getMissing, ...)
 *   backend/db/history.js     — persisted activity log
 *
 * IMPORTANT: pg is asynchronous, so every exported function below returns a
 * Promise — server.js `await`s them. Call initDb() once before serving requests.
 */

import { connect } from "./db/connection.js";
import { createSchema, seed } from "./db/schema.js";

export * from "./db/constants.js";
export * from "./db/accounts.js";
export * from "./db/delegates.js";
export * from "./db/dashboard.js";
export * from "./db/history.js";

/** Connect to Postgres, then create the schema and seed data — in that
 *  order, since schema/seed both need the pool connect() sets up. */
export async function initDb() {
  await connect();
  await createSchema();
  await seed();
}
