/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * PostgreSQL data layer for the MusterGo dashboard (via the `pg` driver).
 *
 * Works with any Postgres host — Neon, Supabase, or a local Postgres server —
 * since they're all plain Postgres underneath. Connection details come from
 * environment variables:
 *
 *   DATABASE_URL = postgresql://user:password@host:5432/dbname   (preferred —
 *                  this is exactly what Neon/Supabase give you on their
 *                  dashboard; paste it straight into backend/.env)
 *   -- or the individual pieces --
 *   DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME
 *
 * Neon/Supabase require SSL; a local Postgres server usually doesn't. This
 * file auto-detects: SSL is enabled unless the host is localhost/127.0.0.1.
 * You can also force it with PGSSL=true or PGSSL=false in .env.
 *
 * The database schema and seed data (first "main" account, trip, coaches) are
 * created automatically on first run — nobody sets those up by hand.
 *
 * IMPORTANT: pg is asynchronous, so every exported function below returns a
 * Promise — server.js `await`s them. Call initDb() once before serving requests.
 */

import pg from "pg";
import bcrypt from "bcryptjs";
import { cleanPermissions } from "../permissions.js";

const { Pool } = pg;

/* ---- Fixed structure used to seed the database -------------------------- */
export const TRIP = {
  id: "t-1",
  name: "Beijing study mission",
  dateRange: "12–16 Aug 2026",
  dayOf: 3,
  totalDays: 5,
  lead: "Wei Ming Tan",
  status: "In progress",
  localTime: "14:26",
  departsIn: "04:53",
};

export const COACHES = [
  { id: "c1", label: "C1", name: "Coach 1", city: "Beijing",  capacity: 40 },
  { id: "c2", label: "C2", name: "Coach 2", city: "Shanghai", capacity: 40 },
  { id: "c3", label: "C3", name: "Coach 3", city: "Hangzhou", capacity: 40 },
  { id: "c4", label: "C4", name: "Coach 4", city: "Suzhou",   capacity: 40 },
];

/* ---- Connection --------------------------------------------------------- */
let pool;

function readConfig() {
  const url = process.env.DATABASE_URL || process.env.POSTGRES_URL;
  const forceSsl = process.env.PGSSL; // "true" | "false" | undefined (auto)

  if (url) {
    const isLocal = /localhost|127\.0\.0\.1/.test(url);
    const ssl = forceSsl === "true" ? { rejectUnauthorized: false }
              : forceSsl === "false" ? false
              : isLocal ? false
              : { rejectUnauthorized: false }; // Neon/Supabase need SSL
    return { connectionString: url, ssl };
  }

  const host = process.env.DB_HOST || "localhost";
  const isLocal = /localhost|127\.0\.0\.1/.test(host);
  const ssl = forceSsl === "true" ? { rejectUnauthorized: false }
            : forceSsl === "false" ? false
            : isLocal ? false
            : { rejectUnauthorized: false };

  return {
    host,
    port: Number(process.env.DB_PORT || 5432),
    user: process.env.DB_USER || "postgres",
    password: process.env.DB_PASSWORD || "",
    database: process.env.DB_NAME || "mustergo",
    ssl,
  };
}

/** Create the pool, the tables, and the seed data. */
export async function initDb() {
  const cfg = readConfig();
  pool = new Pool(cfg);

  // Fail fast with a clear error if the connection is bad, rather than only
  // discovering it on the first request.
  const client = await pool.connect();
  client.release();

  await createSchema();
  await seed();

  const label = cfg.connectionString ? maskUrl(cfg.connectionString) : `${cfg.user}@${cfg.host}:${cfg.port}/${cfg.database}`;
  console.log(`  PostgreSQL connected -> ${label}`);
}

function maskUrl(url) {
  try {
    const u = new URL(url);
    return `${u.username}@${u.hostname}:${u.port || 5432}${u.pathname}`;
  } catch {
    return "(connected)";
  }
}

/* ---- Query helpers -------------------------------------------------------
 * Postgres uses $1, $2, ... positional placeholders, and query results come
 * back as `.rows` on the returned object (the `pg` driver's shape).
 * ------------------------------------------------------------------------- */
async function all(sql, params = []) {
  const res = await pool.query(sql, params);
  return res.rows;
}
async function get(sql, params = []) {
  const rows = await all(sql, params);
  return rows[0] || null;
}
async function run(sql, params = []) {
  await pool.query(sql, params);
}

/* ---- Schema ------------------------------------------------------------- *
 * Postgres syntax notes vs. MySQL: VARCHAR sizes are optional but kept for
 * clarity, TINYINT(1) -> BOOLEAN, and reserved words `lead`/`localTime` still
 * need double-quoting (Postgres lower-cases unquoted identifiers, and our
 * columns are camelCase, so every mixed-case column name is quoted).
 * ------------------------------------------------------------------------- */
async function createSchema() {
  /* ---- JQ base tables (Dashboard / Auth / Accounts) --------------------- */
  await run(`CREATE TABLE IF NOT EXISTS trips (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), "dateRange" VARCHAR(255), "dayOf" INT,
    "totalDays" INT, "lead" VARCHAR(255), status VARCHAR(255), "localTime" VARCHAR(64), "departsIn" VARCHAR(64)
  )`);
  await run(`CREATE TABLE IF NOT EXISTS coaches (
    id VARCHAR(64) PRIMARY KEY, label VARCHAR(64), name VARCHAR(255), city VARCHAR(255), capacity INT
  )`);
  await run(`CREATE TABLE IF NOT EXISTS delegates (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), initials VARCHAR(16), "coachId" VARCHAR(64),
    status VARCHAR(32), vip BOOLEAN, "lastSeen" VARCHAR(255)
  )`);
  // When each delegate was first added (upload/creation time) — powers the
  // "Uploaded" column + "recently added" sort on the Dashboard. Additive: a
  // NOT NULL DEFAULT now() means existing rows get the migration time and new
  // rows default to their insert time (createDelegate doesn't set it).
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()`);
  // Profile photo — set only via POST /api/delegates/:id/photo (uploads
  // through Cloudinary, see uploadDelegatePhoto below), never via the plain
  // PATCH /api/delegates/:id JSON route, so a client can't just PATCH in an
  // arbitrary external URL and bypass the upload validation entirely.
  // photoPublicId is Cloudinary's asset id, kept so the old image can be
  // destroyed on Cloudinary when replaced or removed (otherwise it's an
  // orphaned asset forever).
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "photoUrl" TEXT`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "photoPublicId" TEXT`);
  // Last known location — a free-text place/address (e.g. "Novotel Beijing,
  // Lobby" or a full street address), staff-entered, separate from
  // "lastSeen" (which is a time/note, not a lookup-able place). Rendered as
  // an embedded Google Map (Maps Embed API — a static <iframe>, no live
  // tracking) wherever a delegate's location matters, especially the
  // missing-delegates list. Not geocoded/validated server-side; the Embed
  // API's `q=` param accepts free text and looks it up itself.
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "lastLocation" VARCHAR(255)`);
  await run(`CREATE TABLE IF NOT EXISTS accounts (
    id VARCHAR(64) PRIMARY KEY, username VARCHAR(191) UNIQUE, name VARCHAR(255),
    password VARCHAR(255), role VARCHAR(32), permissions TEXT, "createdAt" VARCHAR(64)
  )`);
  // Single active session per account: each login bumps this, and a token is
  // only valid while its embedded version matches. So signing in on a new
  // browser invalidates the token held by any older one (which then gets
  // logged out by the session poll in the frontend Layout).
  await run(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS token_version INT NOT NULL DEFAULT 0`);
  // Stamped on every GET /api/auth/session call — every signed-in client
  // already polls that endpoint every 15s for the force-logout guard, so this
  // piggybacks on existing traffic instead of adding new polling. Powers the
  // Staff Operations dashboard's "active now" list (accounts seen in the last
  // ~45s, comfortably wider than the 15s poll interval).
  await run(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ`);

  /* ---- Desmond "TransitFlow" schema (Trip Booking & Coach Management) ----
   * Folded in from what originally shipped as database/003_*.sql + 004_*.sql.
   * ALL ADDITIVE: new tables + `ADD COLUMN IF NOT EXISTS` on the base tables
   * above — it never changes/drops anything the base app relies on (trips.id,
   * coaches.id, delegates.id all stay VARCHAR text like "t-1"/"c1"), and every
   * statement is idempotent so it re-runs harmlessly on each startup.
   * --------------------------------------------------------------------- */
  await run(`CREATE EXTENSION IF NOT EXISTS pgcrypto`); // for gen_random_uuid()

  // trips: a parallel UUID identity. The base trips.id stays "t-1"; every new
  // table/column below references this uuid_id instead, so they're real UUIDs.
  await run(`ALTER TABLE trips ADD COLUMN IF NOT EXISTS uuid_id UUID UNIQUE DEFAULT gen_random_uuid()`);
  await run(`UPDATE trips SET uuid_id = gen_random_uuid() WHERE uuid_id IS NULL`);

  // users: a lightweight staff directory for coach assignment ONLY (a "guide"
  // per coach). Separate from `accounts` — these rows never sign in anywhere.
  await run(`CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE,
    role VARCHAR(32) NOT NULL DEFAULT 'staff', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`);

  // coaches: trip link, assigned guide, board order, driver name.
  // sort_order is intentionally added WITHOUT a default so seed() can tell
  // "never positioned" (NULL) apart and backfill a stable order first.
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS trip_id       UUID REFERENCES trips(uuid_id)`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS staff_user_id UUID REFERENCES users(id)`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS sort_order    INT`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS driver_name   VARCHAR(255)`);

  // delegates: trip link + optional free-text fields shown on the board.
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS trip_id             UUID REFERENCES trips(uuid_id)`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS notes               TEXT`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS company             VARCHAR(255)`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS accessibility_notes TEXT`);

  // itinerary_items: per-trip schedule strip driving the journey timeline.
  await run(`CREATE TABLE IF NOT EXISTS itinerary_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL REFERENCES trips(uuid_id) ON DELETE CASCADE,
    day_number INT NOT NULL, start_time TIME NOT NULL, title TEXT NOT NULL,
    location TEXT, sort_order INT NOT NULL DEFAULT 0,
    category VARCHAR(24) NOT NULL DEFAULT 'other'
      CHECK (category IN ('hotel','attraction','meal','factory','airport','transport','other'))
  )`);

  // Indexes for the trip-scoped lookups desmond.js runs.
  await run(`CREATE INDEX IF NOT EXISTS idx_coaches_trip   ON coaches(trip_id)`);
  await run(`CREATE INDEX IF NOT EXISTS idx_delegates_trip ON delegates(trip_id)`);
  await run(`CREATE INDEX IF NOT EXISTS idx_itinerary_trip ON itinerary_items(trip_id, day_number, sort_order)`);

  // History tracker: the Dashboard's activity feed. Previously an in-memory
  // array capped at 8 entries — wiped on every backend restart. Now a real
  // table so past activity survives restarts and accumulates indefinitely.
  await run(`CREATE TABLE IF NOT EXISTS activity_log (
    id VARCHAR(64) PRIMARY KEY, text TEXT NOT NULL, kind VARCHAR(32),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`);
  // actor = the account name that performed the action, so the History
  // tracker can show WHO made each change instead of a generic "you".
  // Nullable: rows created before this column (and any write that doesn't
  // pass an actor) fall back to "you" in rowToActivity().
  await run(`ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS actor TEXT`);
  await run(`CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log("createdAt" DESC)`);
}

async function seed() {
  // First "main" account (once).
  if (!(await get("SELECT id FROM accounts LIMIT 1"))) {
    const perms = defaultPermsForRole("main");
    await run(`INSERT INTO accounts (id, username, name, password, role, permissions, "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7)`, [
      "u-1", "staff_194", "Staff 194", await hashPassword("password123!"), "main", JSON.stringify(perms), new Date().toISOString(),
    ]);
  }
  // Trip (once).
  if (!(await get("SELECT id FROM trips LIMIT 1"))) {
    await run(
      `INSERT INTO trips (id, name, "dateRange", "dayOf", "totalDays", "lead", status, "localTime", "departsIn") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
      [TRIP.id, TRIP.name, TRIP.dateRange, TRIP.dayOf, TRIP.totalDays, TRIP.lead, TRIP.status, TRIP.localTime, TRIP.departsIn]
    );
  }
  // Coaches (once).
  if (!(await get("SELECT id FROM coaches LIMIT 1"))) {
    for (const c of COACHES) {
      await run("INSERT INTO coaches (id, label, name, city, capacity) VALUES ($1,$2,$3,$4,$5)", [c.id, c.label, c.name, c.city, c.capacity]);
    }
  }

  // Desmond "TransitFlow" seed + backfill (folded from database/003_*.sql).
  await seedTransitFlow();
}

/* Seed the staff directory and attach existing coaches/delegates to the
 * Beijing trip so nothing "disappears" once the trip board filters by trip_id.
 * Everything here is idempotent (ON CONFLICT / WHERE ... IS NULL), so it runs
 * safely on every startup — it only ever fills gaps, never overwrites edits. */
async function seedTransitFlow() {
  // 1. Staff directory (6 people) — assignment targets only, not login accounts.
  await run(`
    INSERT INTO users (name, email, role) VALUES
      ('Rachel Tan Hui Min',       'rachel.tan@example.com',   'staff'),
      ('Marcus Lim Wei Jie',       'marcus.lim@example.com',   'staff'),
      ('Priya Suresh',             'priya.suresh@example.com', 'staff'),
      ('Muhammad Hafiz Bin Rosli', 'hafiz.rosli@example.com',  'staff'),
      ('Jonathan Koh Zhi Hao',     'jonathan.koh@example.com', 'admin'),
      ('Serene Ng Xin Yi',         'serene.ng@example.com',    'admin')
    ON CONFLICT (email) DO NOTHING
  `);

  // 2. Attach existing coaches + delegates to the Beijing trip (t-1).
  await run(`UPDATE coaches   SET trip_id = (SELECT uuid_id FROM trips WHERE id = 't-1')
             WHERE trip_id IS NULL AND EXISTS (SELECT 1 FROM trips WHERE id = 't-1')`);
  await run(`UPDATE delegates SET trip_id = (SELECT uuid_id FROM trips WHERE id = 't-1')
             WHERE trip_id IS NULL AND EXISTS (SELECT 1 FROM trips WHERE id = 't-1')`);

  // 3. Give every coach a stable board position (by id order) if it has none,
  //    then set a default for future inserts.
  await run(`
    WITH ordered AS (
      SELECT id, ROW_NUMBER() OVER (ORDER BY id) - 1 AS rn FROM coaches WHERE sort_order IS NULL
    )
    UPDATE coaches SET sort_order = ordered.rn FROM ordered WHERE coaches.id = ordered.id
  `);
  await run(`ALTER TABLE coaches ALTER COLUMN sort_order SET DEFAULT 0`);

  // 4. Round-robin a guide onto any coach that has none, so "every coach has a
  //    staff member" holds immediately (done in JS rather than a plpgsql block).
  const staff = await all("SELECT id FROM users ORDER BY email");
  if (staff.length) {
    const unassigned = await all(`SELECT id FROM coaches WHERE staff_user_id IS NULL ORDER BY sort_order NULLS LAST, id`);
    for (let i = 0; i < unassigned.length; i++) {
      await run("UPDATE coaches SET staff_user_id = $1 WHERE id = $2", [staff[i % staff.length].id, unassigned[i].id]);
    }
  }
}

/* ---- History tracker (persisted activity log) ---------------------------
 * Was an in-memory array capped at 8 entries and wiped on every restart;
 * now stored in activity_log so history survives restarts and accumulates
 * over time (see getActivity/deleteActivity/deleteAllActivity below). */
async function logActivity(text, kind, actor = null) {
  const id = `a-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  await run(`INSERT INTO activity_log (id, text, kind, actor) VALUES ($1,$2,$3,$4)`, [id, text, kind, actor || null]);
}

function rowToActivity(row) {
  return {
    id: row.id,
    text: row.text,
    kind: row.kind,
    time: new Date(row.createdAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }),
    // Who did it — the acting account's name. Legacy rows (and writes with no
    // actor) have none; fall back to "you" (the frontend translates that).
    via: row.actor || "you",
    createdAt: row.createdAt,
  };
}

/** Most recent activity entries, newest first. `limit` defaults to a small
 *  preview (matches the old in-memory cap) — the Dashboard's History tracker
 *  card asks for a much larger limit to show real history. */
export async function getActivity(limit = 8) {
  const rows = await all(`SELECT * FROM activity_log ORDER BY "createdAt" DESC LIMIT $1`, [limit]);
  return rows.map(rowToActivity);
}

export async function deleteActivity(id) {
  const existing = await get("SELECT id FROM activity_log WHERE id = $1", [id]);
  if (!existing) return false;
  await run("DELETE FROM activity_log WHERE id = $1", [id]);
  return true;
}

export async function deleteAllActivity() {
  const count = Number((await get("SELECT COUNT(*) AS c FROM activity_log"))?.c || 0);
  await run("DELETE FROM activity_log");
  return count;
}

/* ---- Helpers ------------------------------------------------------------ */
function initialsOf(name) {
  return (name || "?")
    .trim()
    .split(/\s+/)
    .map((w) => w[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();
}

function rowToDelegate(row) {
  return { ...row, vip: !!row.vip };
}

function normalize(input, id) {
  const status = ["PRESENT", "MISSING", "UNASSIGNED"].includes(input.status)
    ? input.status
    : "UNASSIGNED";
  return {
    id,
    name: (input.name || "").trim() || "Unnamed delegate",
    initials: initialsOf(input.name),
    coachId: status === "UNASSIGNED" ? null : input.coachId || null,
    status,
    vip: !!input.vip,
    lastSeen: (input.lastSeen || "").trim() || null,
    lastLocation: (input.lastLocation || "").trim() || null,
  };
}

async function nextId() {
  const row = await get(`SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 3) AS INTEGER)), 0) AS m FROM delegates`);
  return `d-${Number(row?.m || 0) + 1}`;
}

/* ---- Password rule (shared with the frontend hint) ---------------------- *
 * At least 8 characters, with a letter and a number. Returns an error
 * message, or null if the password is acceptable.
 * ------------------------------------------------------------------------- */
export function passwordProblem(pw) {
  const s = String(pw || "");
  if (s.length < 8) return "Password must be at least 8 characters.";
  if (!/[A-Za-z]/.test(s)) return "Password must include at least one letter.";
  if (!/[0-9]/.test(s)) return "Password must include at least one number.";
  return null;
}

/* ---- Password hashing (bcrypt) -------------------------------------------
 * Passwords are stored as bcrypt hashes. Older rows created before hashing
 * was added may still hold a plaintext password — verifyPassword() detects
 * that (a bcrypt hash always looks like "$2a$10$...") and falls back to a
 * plain comparison, then the login route upgrades the row via
 * upgradePasswordIfNeeded() so it's hashed from then on. Nobody has to run a
 * manual migration.
 * ------------------------------------------------------------------------- */
function isBcryptHash(s) {
  return typeof s === "string" && /^\$2[aby]?\$\d{2}\$/.test(s);
}

export async function hashPassword(plain) {
  return bcrypt.hash(String(plain), 10);
}

/** Compare a plaintext password against a stored (hashed or legacy plaintext) value. */
export async function verifyPassword(plain, stored) {
  if (!stored) return false;
  if (isBcryptHash(stored)) return bcrypt.compare(String(plain), stored);
  return String(plain) === stored; // legacy pre-hashing row
}

/** After a successful login, hash-and-persist any account still on a legacy plaintext password. */
export async function upgradePasswordIfNeeded(account, plainPassword) {
  if (isBcryptHash(account.password)) return;
  await run("UPDATE accounts SET password = $1 WHERE id = $2", [await hashPassword(plainPassword), account.id]);
}

/* ---- Delegate CRUD ------------------------------------------------------ */
export async function listDelegates(tripUuid = null) {
  if (tripUuid) {
    return (await all('SELECT * FROM delegates WHERE trip_id = $1 ORDER BY id', [tripUuid])).map(rowToDelegate);
  }
  return (await all('SELECT * FROM delegates ORDER BY id')).map(rowToDelegate);
}

export async function getDelegateById(id) {
  const row = await get("SELECT * FROM delegates WHERE id = $1", [id]);
  return row ? rowToDelegate(row) : null;
}

export async function createDelegate(input, tripUuid = null, actor = null) {
  const d = normalize(input, await nextId());
  await run(
    `INSERT INTO delegates (id, name, initials, "coachId", status, vip, "lastSeen", "lastLocation", trip_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
    [d.id, d.name, d.initials, d.coachId, d.status, d.vip, d.lastSeen, d.lastLocation, tripUuid]
  );
  await logActivity(`${d.name} added`, d.status === "PRESENT" ? "checkin" : "reassign", actor);
  return d;
}

export async function updateDelegate(id, patch, actor = null) {
  const existing = await get("SELECT * FROM delegates WHERE id = $1", [id]);
  if (!existing) return null;
  const merged = normalize({ ...rowToDelegate(existing), ...patch }, id);
  await run(
    `UPDATE delegates SET name=$1, initials=$2, "coachId"=$3, status=$4, vip=$5, "lastSeen"=$6, "lastLocation"=$7 WHERE id=$8`,
    [merged.name, merged.initials, merged.coachId, merged.status, merged.vip, merged.lastSeen, merged.lastLocation, id]
  );
  await logActivity(`${merged.name} updated`, "reassign", actor);
  return merged;
}

export async function deleteDelegate(id, actor = null) {
  const existing = await get("SELECT * FROM delegates WHERE id = $1", [id]);
  if (!existing) return false;
  await run("DELETE FROM delegates WHERE id = $1", [id]);
  await logActivity(`${existing.name} removed`, "exception", actor);
  return true;
}

/* ---- Profile photo (Cloudinary) -----------------------------------------
 * Deliberately separate from updateDelegate/normalize — see the comment on
 * the "photoUrl" column in createSchema() for why the plain JSON PATCH route
 * must never be able to set these fields. The actual Cloudinary upload/
 * destroy calls live in backend/cloudinary.js and are made by the route
 * handler in server.js; these two just persist the resulting URL/id (or
 * clear them) and return the old publicId so the caller can clean it up. */
export async function setDelegatePhoto(id, url, publicId) {
  const existing = await get('SELECT "photoPublicId" FROM delegates WHERE id = $1', [id]);
  if (!existing) return null;
  await run('UPDATE delegates SET "photoUrl" = $1, "photoPublicId" = $2 WHERE id = $3', [url, publicId, id]);
  return existing.photoPublicId || null;
}

export async function clearDelegatePhoto(id) {
  const existing = await get('SELECT "photoPublicId" FROM delegates WHERE id = $1', [id]);
  if (!existing) return null;
  await run('UPDATE delegates SET "photoUrl" = NULL, "photoPublicId" = NULL WHERE id = $1', [id]);
  return existing.photoPublicId || null;
}

/* ---- Bulk delete (dashboard "Delete all") -------------------------------
 * tripUuid scopes the wipe to just that trip's delegates; null (the base t-1
 * unfiltered view) keeps the original behaviour of clearing every delegate. */
export async function deleteAllDelegates(tripUuid = null, actor = null) {
  const where = tripUuid ? "WHERE trip_id = $1" : "";
  const params = tripUuid ? [tripUuid] : [];
  const count = Number((await get(`SELECT COUNT(*) AS c FROM delegates ${where}`, params))?.c || 0);
  await run(`DELETE FROM delegates ${where}`, params);
  if (count > 0) await logActivity(`All delegates removed (${count})`, "exception", actor);
  return count;
}

/* ---- Derived views ------------------------------------------------------ */
export async function getTrip(tripUuid = null) {
  if (tripUuid) {
    const t = await get("SELECT * FROM trips WHERE uuid_id = $1", [tripUuid]);
    if (t) return t;
  }
  return (await get("SELECT * FROM trips LIMIT 1")) || TRIP;
}

/** Resolve a dashboard :id param to the trip uuid to scope every read/write by.
 *  "t-1" (the base Beijing trip) now resolves to the REAL Beijing trip uuid,
 *  not null.
 *
 *  WHY (this fixed two linked bugs): "t-1" used to mean "null = show every
 *  delegate/coach across ALL trips". That was fine while only Beijing had data,
 *  but once other trips got their own coaches/delegates it meant (a) the base
 *  dashboard's Coach status listed coaches that belong to OTHER trips (looked
 *  like stray "placeholder" coaches), and (b) a delegate added on the base
 *  dashboard was created with trip_id = NULL, so it showed on the dashboard
 *  (null = everything) but NEVER on Desmond's Trips board (which filters by the
 *  trip uuid) — e.g. "desmond" was missing there. Scoping "t-1" to the real
 *  Beijing uuid makes the base dashboard and the Trips board the exact same
 *  dataset, so they stay in sync. The startup backfill in seedTransitFlow()
 *  already attaches any legacy NULL-trip rows to Beijing, so nothing vanishes.
 *  Falls back to null only if the Beijing trip somehow has no uuid yet. */
export async function resolveTripUuid(tripId) {
  if (!tripId) return null;
  if (tripId === "t-1") {
    const t = await get("SELECT uuid_id FROM trips WHERE id = 't-1'");
    return t?.uuid_id || null;
  }
  const t = await get("SELECT uuid_id FROM trips WHERE uuid_id = $1", [tripId]);
  return t?.uuid_id || null;
}

export async function getDashboard(tripUuid = null) {
  const d = await listDelegates(tripUuid);
  const activity = await getActivity(8); // small preview — full history lives on its own endpoint
  const present = d.filter((x) => x.status === "PRESENT").length;
  const missing = d.filter((x) => x.status === "MISSING").length;
  const unassigned = d.filter((x) => x.status === "UNASSIGNED").length;

  const coachRows = tripUuid
    ? await all("SELECT * FROM coaches WHERE trip_id = $1 ORDER BY sort_order NULLS LAST, id", [tripUuid])
    : await all("SELECT * FROM coaches ORDER BY id");
  const coaches = coachRows.map((c) => {
    const assigned = d.filter((x) => x.coachId === c.id);
    return {
      id: c.id,
      label: c.label,
      name: c.name,
      city: c.city,
      capacity: c.capacity,
      boarded: assigned.filter((x) => x.status === "PRESENT").length,
      missing: assigned.filter((x) => x.status === "MISSING").length,
      total: assigned.length,
    };
  });

  return {
    trip: await getTrip(tripUuid),
    kpis: {
      total: d.length,
      present,
      missing,
      unassigned,
      openExceptions: 0,
      criticalExceptions: 0,
      normalExceptions: 0,
      presentDelta: activity.filter((a) => a.kind === "checkin").length,
    },
    coaches,
    activity,
  };
}

export async function getMissing(tripUuid = null) {
  const coaches = await all("SELECT * FROM coaches");
  return (await listDelegates(tripUuid))
    .filter((x) => x.status === "MISSING")
    .map((x) => {
      const coach = coaches.find((c) => c.id === x.coachId);
      return {
        id: x.id,
        name: x.name,
        initials: x.initials,
        status: x.status, // always "MISSING" here, but carried so DelegateAvatar can tint red
        coachId: x.coachId,
        // Coaches added outside the seed may have no city — don't render "null".
        coach: coach ? [coach.name, coach.city].filter(Boolean).join(" · ") : "Unassigned",
        vip: x.vip,
        lastSeen: x.lastSeen,
        lastLocation: x.lastLocation,
        createdAt: x.createdAt,
      };
    });
}

export async function getDelegates(tripUuid = null) {
  return listDelegates(tripUuid);
}

/* ---- Accounts + permissions -------------------------------------------- *
 * Each account carries a set of permissions (tickboxes on the Account control
 * page). A short "role" label (main/admin/staff) is derived from the
 * permissions for display. Passwords are stored as bcrypt hashes (see
 * hashPassword/verifyPassword above).
 * ------------------------------------------------------------------------- */
function defaultPermsForRole(role) {
  if (role === "main") return { manageDelegates: true, exportData: true, manageAccounts: true };
  if (role === "admin") return { manageDelegates: true, exportData: true, manageAccounts: false };
  return { manageDelegates: true, exportData: false, manageAccounts: false }; // staff
}

function cleanPerms(input) {
  return cleanPermissions(input);
}

function roleFromPerms(p) {
  if (p.manageAccounts) return "main";
  if (p.manageDelegates || p.exportData) return "admin";
  return "staff";
}

/** Parsed permissions for an account row (falls back to role defaults). */
export function accountPermissions(row) {
  if (!row) return cleanPerms({});
  try {
    if (row.permissions) return cleanPerms(JSON.parse(row.permissions));
  } catch { /* fall through */ }
  return defaultPermsForRole(row.role);
}

export function accountCan(row, perm) {
  return !!accountPermissions(row)[perm];
}

async function countManagers() {
  return (await all("SELECT * FROM accounts")).filter((a) => accountPermissions(a).manageAccounts).length;
}

function accountPublic(row) {
  if (!row) return null;
  const { password, permissions, token_version, ...rest } = row; // never expose password / raw JSON / session counter
  return { ...rest, permissions: accountPermissions(row) };
}

/**
 * Start a fresh login session for an account: bump its token_version and
 * return the new value. Any token minted with the previous version stops
 * validating (see accountFromReq in auth.js), so an older browser is logged
 * out the next time it polls. Called from the login route only.
 */
export async function startNewSession(id) {
  const row = await get(`UPDATE accounts SET token_version = token_version + 1 WHERE id = $1 RETURNING token_version`, [id]);
  return row?.token_version ?? 0;
}

/** Stamp "seen right now" on an account — called from GET /api/auth/session,
 *  which every signed-in client already polls every 15s. Powers the Staff
 *  Operations "active now" list; fire-and-forget from the caller's side (a
 *  failed stamp shouldn't fail the session check itself). */
export async function touchLastSeen(id) {
  await run(`UPDATE accounts SET last_seen_at = now() WHERE id = $1`, [id]);
}

/** Clears "seen right now" on explicit logout, so the Staff Operations
 *  "active now" list drops the account immediately instead of waiting up to
 *  45s for last_seen_at to age out. Called from POST /api/auth/logout. */
export async function clearLastSeen(id) {
  await run(`UPDATE accounts SET last_seen_at = NULL WHERE id = $1`, [id]);
}

/** Accounts considered "active now" — seen within the last `withinSeconds`.
 *  Same accountPublic() shape as listAccounts(), so the frontend can reuse
 *  the existing role/permission-chip rendering. */
export async function listActiveAccounts(withinSeconds = 45) {
  const rows = await all(
    `SELECT * FROM accounts WHERE last_seen_at IS NOT NULL AND last_seen_at > now() - ($1 || ' seconds')::interval ORDER BY last_seen_at DESC`,
    [withinSeconds]
  );
  return rows.map(accountPublic);
}

async function nextAccountId() {
  const row = await get(`SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 3) AS INTEGER)), 0) AS m FROM accounts`);
  return `u-${Number(row?.m || 0) + 1}`;
}

/** Full row incl. password — used only for login / auth checks. */
export async function getAccountByUsername(username) {
  return get("SELECT * FROM accounts WHERE username = $1", [String(username || "").trim()]);
}

export async function listAccounts() {
  return (await all("SELECT * FROM accounts ORDER BY id")).map(accountPublic);
}

export async function createAccount(input) {
  const username = String(input.username || "").trim();
  const password = String(input.password || "");
  const name = String(input.name || "").trim() || username;
  const perms = cleanPerms(input.permissions);
  const role = roleFromPerms(perms);

  if (!username) return { error: "USERNAME_REQUIRED" };
  if (!password) return { error: "PASSWORD_REQUIRED" };
  const pwProblem = passwordProblem(password);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
  if (await getAccountByUsername(username)) return { error: "USERNAME_TAKEN" };

  const id = await nextAccountId();
  await run(`INSERT INTO accounts (id, username, name, password, role, permissions, "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7)`, [
    id, username, name, await hashPassword(password), role, JSON.stringify(perms), new Date().toISOString(),
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

export async function updateAccount(id, patch) {
  const existing = await get("SELECT * FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  const username = patch.username !== undefined ? String(patch.username).trim() : existing.username;
  const name = patch.name !== undefined ? String(patch.name).trim() || username : existing.name;
  const perms = patch.permissions ? cleanPerms(patch.permissions) : accountPermissions(existing);
  const role = roleFromPerms(perms);

  let password = existing.password;
  if (patch.password) {
    const pwProblem = passwordProblem(String(patch.password));
    if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
    password = await hashPassword(String(patch.password));
  }

  if (!username) return { error: "USERNAME_REQUIRED" };
  const clash = await getAccountByUsername(username);
  if (clash && clash.id !== id) return { error: "USERNAME_TAKEN" };

  if (accountPermissions(existing).manageAccounts && !perms.manageAccounts && (await countManagers()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run(`UPDATE accounts SET username=$1, name=$2, password=$3, role=$4, permissions=$5 WHERE id=$6`, [
    username, name, password, role, JSON.stringify(perms), id,
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/**
 * "Forgot password" self-service reset — username + new password, no
 * identity verification (no old password, no email/OTP). Intentionally
 * simple for this project's small trusted-team context; NOT safe as-is for
 * a real public deployment, where anyone who knows a username could take
 * over that account. Bumps token_version so any existing session for that
 * account is invalidated by the reset (same pattern as a fresh login).
 */
export async function resetPassword(username, newPassword) {
  const pwProblem = passwordProblem(newPassword);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };

  const existing = await getAccountByUsername(username);
  if (!existing) {
    // Generic error either way — avoids confirming which usernames exist.
    return { error: "RESET_FAILED" };
  }

  await run(`UPDATE accounts SET password = $1, token_version = token_version + 1 WHERE id = $2`, [
    await hashPassword(newPassword), existing.id,
  ]);
  return { ok: true };
}

export async function deleteAccount(id) {
  const existing = await get("SELECT * FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  if (accountPermissions(existing).manageAccounts && (await countManagers()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run("DELETE FROM accounts WHERE id = $1", [id]);
  return { deleted: true };
}
