/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * MySQL data layer for the MusterGo dashboard (via the `mysql2` driver).
 *
 * The backend now talks to a real MySQL server (each developer runs their own
 * local one — see MYSQL-SETUP.txt). Connection details come from environment
 * variables:
 *
 *   DATABASE_URL = mysql://user:password@localhost:3306/mustergo   (preferred)
 *   -- or the individual pieces --
 *   DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME
 *
 * If none are set it falls back to root@localhost:3306 with database "mustergo".
 * The database and tables are created automatically on first run, and the first
 * "main" account (staff_194 / password123!) is seeded so there's always a way in.
 *
 * IMPORTANT: mysql2 is asynchronous, so every exported function below returns a
 * Promise — server.js `await`s them. Call initDb() once before serving requests.
 */

import mysql from "mysql2/promise";
import { cleanPermissions } from "../permissions.js";

/* ---- Fixed structure used to seed the database -------------------------- */
export const TRIP = {
  id: "t-1",
  name: "Beijing study mission",
  dateRange: "12–16 Aug 2026",
  dayOf: 3,
  totalDays: 5,
  lead: "Wei Ming Tan",
  status: "In progress",
  localTime: "14:26",
  departsIn: "04:53",
};

export const COACHES = [
  { id: "c1", label: "C1", name: "Coach 1", city: "Beijing",  capacity: 40 },
  { id: "c2", label: "C2", name: "Coach 2", city: "Shanghai", capacity: 40 },
  { id: "c3", label: "C3", name: "Coach 3", city: "Hangzhou", capacity: 40 },
  { id: "c4", label: "C4", name: "Coach 4", city: "Suzhou",   capacity: 40 },
];

/* ---- Connection --------------------------------------------------------- */
let pool;

function readConfig() {
  const url = process.env.DATABASE_URL || process.env.MYSQL_URL;
  if (url) {
    const u = new URL(url);
    return {
      host: u.hostname || "localhost",
      port: Number(u.port || 3306),
      user: decodeURIComponent(u.username || "root"),
      password: decodeURIComponent(u.password || ""),
      database: (u.pathname || "/mustergo").slice(1) || "mustergo",
    };
  }
  return {
    host: process.env.DB_HOST || "localhost",
    port: Number(process.env.DB_PORT || 3306),
    user: process.env.DB_USER || "root",
    password: process.env.DB_PASSWORD || "",
    database: process.env.DB_NAME || "mustergo",
  };
}

/** Create the database (if needed), the pool, the tables, and the seed data. */
export async function initDb() {
  const cfg = readConfig();

  // 1) Make sure the database exists (connect without selecting one first).
  const boot = await mysql.createConnection({
    host: cfg.host, port: cfg.port, user: cfg.user, password: cfg.password,
  });
  await boot.query(`CREATE DATABASE IF NOT EXISTS \`${cfg.database}\``);
  await boot.end();

  // 2) Pool bound to the database.
  pool = mysql.createPool({
    ...cfg,
    waitForConnections: true,
    connectionLimit: 10,
  });

  // 3) Schema + seed.
  await createSchema();
  await seed();

  console.log(`  MySQL connected -> ${cfg.user}@${cfg.host}:${cfg.port}/${cfg.database}`);
}

/* ---- Query helpers ------------------------------------------------------ */
async function all(sql, params = []) {
  const [rows] = await pool.query(sql, params);
  return rows;
}
async function get(sql, params = []) {
  const rows = await all(sql, params);
  return rows[0] || null;
}
async function run(sql, params = []) {
  await pool.query(sql, params);
}

/* ---- Schema ------------------------------------------------------------- *
 * MySQL syntax notes vs. SQLite: TEXT-as-primary-key -> VARCHAR, INTEGER -> INT,
 * and the reserved words `lead` / `localTime` are back-ticked.
 * ------------------------------------------------------------------------- */
async function createSchema() {
  await run(`CREATE TABLE IF NOT EXISTS trips (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), dateRange VARCHAR(255), dayOf INT,
    totalDays INT, \`lead\` VARCHAR(255), status VARCHAR(255), \`localTime\` VARCHAR(64), departsIn VARCHAR(64)
  )`);
  await run(`CREATE TABLE IF NOT EXISTS coaches (
    id VARCHAR(64) PRIMARY KEY, label VARCHAR(64), name VARCHAR(255), city VARCHAR(255), capacity INT
  )`);
  await run(`CREATE TABLE IF NOT EXISTS delegates (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), initials VARCHAR(16), coachId VARCHAR(64),
    status VARCHAR(32), vip TINYINT(1), lastSeen VARCHAR(255)
  )`);
  await run(`CREATE TABLE IF NOT EXISTS accounts (
    id VARCHAR(64) PRIMARY KEY, username VARCHAR(191) UNIQUE, name VARCHAR(255),
    password VARCHAR(255), role VARCHAR(32), permissions TEXT, createdAt VARCHAR(64)
  )`);
}

async function seed() {
  // First "main" account (once).
  if (!(await get("SELECT id FROM accounts LIMIT 1"))) {
    const perms = defaultPermsForRole("main");
    await run("INSERT INTO accounts (id, username, name, password, role, permissions, createdAt) VALUES (?,?,?,?,?,?,?)", [
      "u-1", "staff_194", "Staff 194", "password123!", "main", JSON.stringify(perms), new Date().toISOString(),
    ]);
  }
  // Trip (once).
  if (!(await get("SELECT id FROM trips LIMIT 1"))) {
    await run(
      "INSERT INTO trips (id, name, dateRange, dayOf, totalDays, `lead`, status, `localTime`, departsIn) VALUES (?,?,?,?,?,?,?,?,?)",
      [TRIP.id, TRIP.name, TRIP.dateRange, TRIP.dayOf, TRIP.totalDays, TRIP.lead, TRIP.status, TRIP.localTime, TRIP.departsIn]
    );
  }
  // Coaches (once).
  if (!(await get("SELECT id FROM coaches LIMIT 1"))) {
    for (const c of COACHES) {
      await run("INSERT INTO coaches (id, label, name, city, capacity) VALUES (?,?,?,?,?)", [c.id, c.label, c.name, c.city, c.capacity]);
    }
  }
}

/* ---- In-memory activity log --------------------------------------------- */
let ACTIVITY = [];

function logActivity(text, kind) {
  ACTIVITY.unshift({
    id: `a-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    text,
    time: new Date().toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }),
    via: "you",
    kind,
  });
  ACTIVITY = ACTIVITY.slice(0, 8);
}

/* ---- Helpers ------------------------------------------------------------ */
function initialsOf(name) {
  return (name || "?")
    .trim()
    .split(/\s+/)
    .map((w) => w[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();
}

function rowToDelegate(row) {
  return { ...row, vip: !!row.vip };
}

function normalize(input, id) {
  const status = ["PRESENT", "MISSING", "UNASSIGNED"].includes(input.status)
    ? input.status
    : "UNASSIGNED";
  return {
    id,
    name: (input.name || "").trim() || "Unnamed delegate",
    initials: initialsOf(input.name),
    coachId: status === "UNASSIGNED" ? null : input.coachId || null,
    status,
    vip: !!input.vip,
    lastSeen: (input.lastSeen || "").trim() || null,
  };
}

async function nextId() {
  const row = await get("SELECT COALESCE(MAX(CAST(SUBSTRING(id, 3) AS UNSIGNED)), 0) AS m FROM delegates");
  return `d-${Number(row?.m || 0) + 1}`;
}

/* ---- Password rule (shared with the frontend hint) ---------------------- *
 * Appropriate minimum for the demo: at least 8 characters, with a letter and a
 * number. Returns an error message, or null if the password is acceptable.
 * ------------------------------------------------------------------------- */
export function passwordProblem(pw) {
  const s = String(pw || "");
  if (s.length < 8) return "Password must be at least 8 characters.";
  if (!/[A-Za-z]/.test(s)) return "Password must include at least one letter.";
  if (!/[0-9]/.test(s)) return "Password must include at least one number.";
  return null;
}

/* ---- Delegate CRUD ------------------------------------------------------ */
export async function listDelegates() {
  return (await all("SELECT * FROM delegates ORDER BY id")).map(rowToDelegate);
}

export async function createDelegate(input) {
  const d = normalize(input, await nextId());
  await run("INSERT INTO delegates (id, name, initials, coachId, status, vip, lastSeen) VALUES (?,?,?,?,?,?,?)", [
    d.id, d.name, d.initials, d.coachId, d.status, d.vip ? 1 : 0, d.lastSeen,
  ]);
  logActivity(`${d.name} added`, d.status === "PRESENT" ? "checkin" : "reassign");
  return d;
}

export async function updateDelegate(id, patch) {
  const existing = await get("SELECT * FROM delegates WHERE id = ?", [id]);
  if (!existing) return null;
  const merged = normalize({ ...rowToDelegate(existing), ...patch }, id);
  await run(
    "UPDATE delegates SET name=?, initials=?, coachId=?, status=?, vip=?, lastSeen=? WHERE id=?",
    [merged.name, merged.initials, merged.coachId, merged.status, merged.vip ? 1 : 0, merged.lastSeen, id]
  );
  logActivity(`${merged.name} updated`, "reassign");
  return merged;
}

export async function deleteDelegate(id) {
  const existing = await get("SELECT * FROM delegates WHERE id = ?", [id]);
  if (!existing) return false;
  await run("DELETE FROM delegates WHERE id = ?", [id]);
  logActivity(`${existing.name} removed`, "exception");
  return true;
}

/* ---- Bulk delete (dashboard "Delete all") ------------------------------- */
export async function deleteAllDelegates() {
  const count = Number((await get("SELECT COUNT(*) AS c FROM delegates"))?.c || 0);
  await run("DELETE FROM delegates");
  if (count > 0) logActivity(`All delegates removed (${count})`, "exception");
  return count;
}

/* ---- Derived views ------------------------------------------------------ */
export async function getTrip() {
  return (await get("SELECT * FROM trips LIMIT 1")) || TRIP;
}

export function getActivity() {
  return ACTIVITY;
}

export async function getDashboard() {
  const d = await listDelegates();
  const present = d.filter((x) => x.status === "PRESENT").length;
  const missing = d.filter((x) => x.status === "MISSING").length;
  const unassigned = d.filter((x) => x.status === "UNASSIGNED").length;

  const coaches = (await all("SELECT * FROM coaches ORDER BY id")).map((c) => {
    const assigned = d.filter((x) => x.coachId === c.id);
    return {
      id: c.id,
      label: c.label,
      name: c.name,
      city: c.city,
      capacity: c.capacity,
      boarded: assigned.filter((x) => x.status === "PRESENT").length,
      missing: assigned.filter((x) => x.status === "MISSING").length,
      total: assigned.length,
    };
  });

  return {
    trip: await getTrip(),
    kpis: {
      total: d.length,
      present,
      missing,
      unassigned,
      openExceptions: 0,
      criticalExceptions: 0,
      normalExceptions: 0,
      presentDelta: ACTIVITY.filter((a) => a.kind === "checkin").length,
    },
    coaches,
    activity: ACTIVITY,
  };
}

export async function getMissing() {
  const coaches = await all("SELECT * FROM coaches");
  return (await listDelegates())
    .filter((x) => x.status === "MISSING")
    .map((x) => {
      const coach = coaches.find((c) => c.id === x.coachId);
      return {
        id: x.id,
        name: x.name,
        initials: x.initials,
        coach: coach ? `${coach.name} · ${coach.city}` : "Unassigned",
        vip: x.vip,
        lastSeen: x.lastSeen,
      };
    });
}

export async function getDelegates() {
  return listDelegates();
}

/* ---- Accounts + permissions -------------------------------------------- *
 * Each account carries a set of permissions (tickboxes on the Account control
 * page). A short "role" label (main/admin/staff) is derived from the
 * permissions for display. Passwords are plaintext for this school demo;
 * production would hash them (bcrypt).
 * ------------------------------------------------------------------------- */
function defaultPermsForRole(role) {
  if (role === "main") return { manageDelegates: true, exportData: true, manageAccounts: true };
  if (role === "admin") return { manageDelegates: true, exportData: true, manageAccounts: false };
  return { manageDelegates: true, exportData: false, manageAccounts: false }; // staff
}

function cleanPerms(input) {
  return cleanPermissions(input);
}

function roleFromPerms(p) {
  if (p.manageAccounts) return "main";
  if (p.manageDelegates || p.exportData) return "admin";
  return "staff";
}

/** Parsed permissions for an account row (falls back to role defaults). */
export function accountPermissions(row) {
  if (!row) return cleanPerms({});
  try {
    if (row.permissions) return cleanPerms(JSON.parse(row.permissions));
  } catch { /* fall through */ }
  return defaultPermsForRole(row.role);
}

export function accountCan(row, perm) {
  return !!accountPermissions(row)[perm];
}

async function countManagers() {
  return (await all("SELECT * FROM accounts")).filter((a) => accountPermissions(a).manageAccounts).length;
}

function accountPublic(row) {
  if (!row) return null;
  const { password, permissions, ...rest } = row; // never expose the password / raw JSON
  return { ...rest, permissions: accountPermissions(row) };
}

async function nextAccountId() {
  const row = await get("SELECT COALESCE(MAX(CAST(SUBSTRING(id, 3) AS UNSIGNED)), 0) AS m FROM accounts");
  return `u-${Number(row?.m || 0) + 1}`;
}

/** Full row incl. password — used only for login / auth checks. */
export async function getAccountByUsername(username) {
  return get("SELECT * FROM accounts WHERE username = ?", [String(username || "").trim()]);
}

export async function listAccounts() {
  return (await all("SELECT * FROM accounts ORDER BY id")).map(accountPublic);
}

export async function createAccount(input) {
  const username = String(input.username || "").trim();
  const password = String(input.password || "");
  const name = String(input.name || "").trim() || username;
  const perms = cleanPerms(input.permissions);
  const role = roleFromPerms(perms);

  if (!username) return { error: "USERNAME_REQUIRED" };
  if (!password) return { error: "PASSWORD_REQUIRED" };
  const pwProblem = passwordProblem(password);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
  if (await getAccountByUsername(username)) return { error: "USERNAME_TAKEN" };

  const id = await nextAccountId();
  await run("INSERT INTO accounts (id, username, name, password, role, permissions, createdAt) VALUES (?,?,?,?,?,?,?)", [
    id, username, name, password, role, JSON.stringify(perms), new Date().toISOString(),
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = ?", [id])) };
}

export async function updateAccount(id, patch) {
  const existing = await get("SELECT * FROM accounts WHERE id = ?", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  const username = patch.username !== undefined ? String(patch.username).trim() : existing.username;
  const name = patch.name !== undefined ? String(patch.name).trim() || username : existing.name;
  const perms = patch.permissions ? cleanPerms(patch.permissions) : accountPermissions(existing);
  const role = roleFromPerms(perms);

  // Only change/validate the password if a new one was provided.
  let password = existing.password;
  if (patch.password) {
    const pwProblem = passwordProblem(String(patch.password));
    if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
    password = String(patch.password);
  }

  if (!username) return { error: "USERNAME_REQUIRED" };
  const clash = await getAccountByUsername(username);
  if (clash && clash.id !== id) return { error: "USERNAME_TAKEN" };

  // Don't let the last account that can manage accounts lose that permission.
  if (accountPermissions(existing).manageAccounts && !perms.manageAccounts && (await countManagers()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run("UPDATE accounts SET username=?, name=?, password=?, role=?, permissions=? WHERE id=?", [
    username, name, password, role, JSON.stringify(perms), id,
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = ?", [id])) };
}

export async function deleteAccount(id) {
  const existing = await get("SELECT * FROM accounts WHERE id = ?", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  if (accountPermissions(existing).manageAccounts && (await countManagers()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run("DELETE FROM accounts WHERE id = ?", [id]);
  return { deleted: true };
}
