/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  README/INTEGRATION_NOTES.md at the project root for what's yours vs. off-limits, and integration gotchas.
 * ============================================================================= */
import { useEffect, useState, useRef } from "react";
import { Outlet, useLocation } from "react-router-dom";
import { Menu, ClipboardCheck } from "lucide-react";
import Sidebar from "./Sidebar.jsx";
import ChatBubble from "./ChatBubble.jsx";
import EscalationBanner from "./EscalationBanner.jsx";
import { getCriticalOpenCount } from "../lib/exceptionsApi.js";
import { useSessionGuard } from "../lib/useSessionGuard.js";
import { useLang } from "../lib/i18n.jsx";
import { getPermissions } from "../lib/api.js";

// How often (ms) to refresh the sidebar's critical-exception badge. Kept
// separate from the session-guard's own interval since it's unrelated data.
const EXCEPTION_BADGE_INTERVAL_MS = 15000;

/**
 * Admin shell layout. The sidebar persists; routed pages render in <Outlet/>.
 * `onLogout` is passed through to the sidebar's Log out button.
 * `exceptionCount` is the live count of unresolved CRITICAL tickets from
 * Jayden's exception module (GET /api/trips/:id/exceptions/critical-count).
 *
 * useSessionGuard() (shared with MobileLayout.jsx) polls GET /api/auth/
 * session so a stale/invalidated token — an admin edited/deleted this
 * account, or someone logged into it elsewhere, which invalidates this
 * token server-side — force-logs-out instead of the UI silently carrying on
 * with a broken session.
 */
export default function Layout({ onLogout }) {
  const { t } = useLang();
  const [openExceptions, setOpenExceptions] = useState(0);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const location = useLocation();
  // Same drag-to-select-text guard used across every modal in the app —
  // only dismiss if the WHOLE click gesture started on the backdrop itself.
  const downOnBackdrop = useRef(false);

  useSessionGuard(onLogout);

  // Close the drawer automatically on every navigation (tablet/narrow
  // screens only — CSS keeps the sidebar always-visible on desktop widths
  // regardless of this state, see tokens.css's collapsible-sidebar block).
  useEffect(() => {
    setSidebarOpen(false);
  }, [location.pathname]);

  useEffect(() => {
    let cancelled = false;
    async function loadBadge() {
      try {
        const n = await getCriticalOpenCount();
        if (!cancelled) setOpenExceptions(n);
      } catch {
        // Exception module unreachable/not seeded yet — leave the badge at 0
        // rather than showing a stale or broken count.
      }
    }
    loadBadge();
    const iv = setInterval(loadBadge, EXCEPTION_BADGE_INTERVAL_MS);
    return () => { cancelled = true; clearInterval(iv); };
  }, []);

  return (
    <div className="app-shell">
      {/* Hamburger topbar — hidden on desktop widths via CSS, only rendered
         visibly at tablet/narrow widths where the sidebar collapses into an
         off-canvas drawer instead of staying pinned open. */}
      <div className="app-topbar-collapsed">
        <button
          className="app-hamburger"
          onClick={() => setSidebarOpen((v) => !v)}
          aria-label={t("Toggle navigation")}
          aria-expanded={sidebarOpen}
        >
          <Menu size={20} />
        </button>
        <span className="app-topbar-brand wordmark">
          <ClipboardCheck size={18} strokeWidth={2.4} /> MusterGo
        </span>
      </div>

      {sidebarOpen && (
        <div className="app-sidebar-backdrop"
          onMouseDown={(e) => { downOnBackdrop.current = e.target === e.currentTarget; }}
          onClick={(e) => { if (downOnBackdrop.current && e.target === e.currentTarget) setSidebarOpen(false); }}
        />
      )}

      <Sidebar exceptionCount={openExceptions} onLogout={onLogout} open={sidebarOpen} />
      <main className="main">
        <EscalationBanner />
        <Outlet />
      </main>
      {getPermissions().viewChatbot && <ChatBubble />}
    </div>
  );
}
