/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  README/INTEGRATION_NOTES.md at the project root for what's yours vs. off-limits, and integration gotchas.
 * ============================================================================= */
import { useEffect, useState, useRef } from "react";
import { Outlet, useLocation } from "react-router-dom";
import { Menu, ClipboardCheck } from "lucide-react";
import Sidebar from "./Sidebar.jsx";
import ChatBubble from "./mchat/ChatBubble.jsx";
import EscalationBanner from "./EscalationBanner.jsx";
import SyncStatus from "./localstorage/SyncStatus.jsx";
import { getCriticalOpenCount } from "../lib/exception/exceptionsApi.js";
import { getActiveTripId } from "../lib/activeTrip.js";
import { useSessionGuard } from "../lib/useSessionGuard.js";
import { useLang } from "../lib/i18n.jsx";
import { getPermissions, getUser, apiGet } from "../lib/api.js";
import { countUnseenAnnouncements } from "../lib/announcements/announcementsSeen.js";
import { useVisiblePolling } from "../lib/useVisiblePolling.js";

// How often (ms) to refresh the sidebar's critical-exception badge. Kept
// separate from the session-guard's own interval since it's unrelated data.
const EXCEPTION_BADGE_INTERVAL_MS = 15000;

// Same localStorage key DashboardPage.jsx/AnnouncementsPage.jsx use for
// "currently viewing trip" — the announcements badge tracks THAT trip, same
// as the page it links to.
const DASHBOARD_TRIP_KEY = "mg_dashboard_trip";

/**
 * Admin shell layout. The sidebar persists; routed pages render in <Outlet/>.
 * `onLogout` is passed through to the sidebar's Log out button.
 * `exceptionCount` is the live count of unresolved CRITICAL tickets from
 * Jayden's exception module (GET /api/trips/:id/exceptions/critical-count).
 *
 * useSessionGuard() (shared with MobileLayout.jsx) polls GET /api/auth/
 * session so a stale/invalidated token — an admin edited/deleted this
 * account, or someone logged into it elsewhere, which invalidates this
 * token server-side — force-logs-out instead of the UI silently carrying on
 * with a broken session.
 */
export default function Layout({ onLogout }) {
  const { t } = useLang();
  const [openExceptions, setOpenExceptions] = useState(0);
  const [unseenAnnouncements, setUnseenAnnouncements] = useState(0);
  const [pendingAccounts, setPendingAccounts] = useState(0);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const location = useLocation();
  // Same drag-to-select-text guard used across every modal in the app —
  // only dismiss if the WHOLE click gesture started on the backdrop itself.
  const downOnBackdrop = useRef(false);

  useSessionGuard(onLogout);

  // Close the drawer automatically on every navigation (tablet/narrow
  // screens only — CSS keeps the sidebar always-visible on desktop widths
  // regardless of this state, see tokens.css's collapsible-sidebar block).
  useEffect(() => {
    setSidebarOpen(false);
  }, [location.pathname]);

  // Both badge polls below pause while the tab is hidden (2026-07-29) — see
  // useVisiblePolling. These two matter more than any single page's poller
  // because they run on EVERY route: any open MusterGo tab, on any screen, was
  // previously hitting the backend twice every 15s forever.
  useVisiblePolling(async () => {
    try {
      setOpenExceptions(await getCriticalOpenCount(getActiveTripId()));
    } catch {
      // Exception module unreachable/not seeded yet — leave the badge at 0
      // rather than showing a stale or broken count.
    }
  }, EXCEPTION_BADGE_INTERVAL_MS);

  useVisiblePolling(async () => {
    if (!getPermissions().viewAnnouncements) return;
    let tripId;
    try { tripId = localStorage.getItem(DASHBOARD_TRIP_KEY); } catch { tripId = null; }
    if (!tripId) return; // nobody's picked a trip yet — nothing to badge against
    try {
      const data = await apiGet(`/trips/${tripId}/announcements`);
      setUnseenAnnouncements(countUnseenAnnouncements(tripId, data.announcements || []));
    } catch {
      // Trip switched/deleted mid-poll, or backend hiccup — leave the last
      // known count rather than flashing the badge to 0.
    }
  }, EXCEPTION_BADGE_INTERVAL_MS);

  // New-account badge on the "Account control" nav item (2026-08-03 —
  // "add the badge so can see new account") — same live-count pattern as
  // Exceptions above, just against GET /accounts/pending. Gated the same way
  // Sidebar itself decides whether to show the Account control link at all
  // (a read-only Admin can still VIEW pending accounts, just not act on
  // them), so a Staff account doesn't fire a 403 every poll for a link it
  // never even sees.
  useVisiblePolling(async () => {
    const perms = getPermissions();
    const user = getUser();
    const isAdmin = !!perms.manageAccounts || (user?.role === "admin" && user?.readOnly);
    if (!isAdmin) return;
    try {
      const data = await apiGet("/accounts/pending");
      setPendingAccounts((data.accounts || []).length);
    } catch {
      // Leave the last known count rather than flashing the badge to 0.
    }
  }, EXCEPTION_BADGE_INTERVAL_MS);

  return (
    <div className="app-shell">
      {/* Hamburger topbar — hidden on desktop widths via CSS, only rendered
         visibly at tablet/narrow widths where the sidebar collapses into an
         off-canvas drawer instead of staying pinned open. */}
      <div className="app-topbar-collapsed">
        <button
          className="app-hamburger"
          onClick={() => setSidebarOpen((v) => !v)}
          aria-label={t("Toggle navigation")}
          aria-expanded={sidebarOpen}
        >
          <Menu size={20} />
        </button>
        <span className="app-topbar-brand wordmark">
          <ClipboardCheck size={18} strokeWidth={2.4} /> MusterGo
        </span>
      </div>

      {sidebarOpen && (
        <div className="app-sidebar-backdrop"
          onMouseDown={(e) => { downOnBackdrop.current = e.target === e.currentTarget; }}
          onClick={(e) => { if (downOnBackdrop.current && e.target === e.currentTarget) setSidebarOpen(false); }}
        />
      )}

      <Sidebar exceptionCount={openExceptions} announcementCount={unseenAnnouncements} pendingAccountsCount={pendingAccounts} onLogout={onLogout} open={sidebarOpen} />
      <main className="main">
        <EscalationBanner />
        <Outlet />
      </main>
      {getPermissions().viewChatbot && <ChatBubble />}
      {/* Offline / unsynced-writes pill (2026-07-28) — every route, since losing
          signal isn't page-specific. Renders nothing when online and drained. */}
      <SyncStatus />
    </div>
  );
}
