/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  README/INTEGRATION_NOTES.md for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * Accounts + permissions + password hashing. Exactly two roles: "admin" and
 * "staff" — role is an independent, explicitly set field (the Account control
 * role picker), NOT derived from which permission checkboxes are ticked.
 * Passwords are stored as bcrypt hashes.
 *
 * SECURITY: admin BYPASSES every permission check — accountPermissions()
 * returns every key true for an admin regardless of what's stored, so
 * requirePermission() (auth.js) and frontend getPermissions().xyz checks
 * unlock for admins with no per-call special-casing. Staff are governed by
 * their stored checkboxes, defaulting to just manageDelegates.
 *
 * defaultPermsForRole() is exported so db/schema.js's seed() can reuse the
 * role-default logic instead of duplicating it.
 */

import bcrypt from "bcryptjs";
import { cleanPermissions, PERM_KEYS, PERMISSIONS } from "../../frontend/src/lib/permissions.js";
import { all, get, run } from "./connection.js";

// Every action-group key (manageDelegates, manageAccounts, ...) — the write
// capabilities a read-only Admin loses. Everything else (desktopView/
// mobileView) stays true so a read-only Admin still sees every tab.
const ACTION_KEYS = PERMISSIONS.filter((p) => p.group === "action").map((p) => p.key);

/* ---- Password rule (shared with the frontend hint) ---------------------- *
 * At least 8 characters, with a letter and a number. Returns an error
 * message, or null if the password is acceptable.
 * ------------------------------------------------------------------------- */
export function passwordProblem(pw) {
  const s = String(pw || "");
  if (s.length < 8) return "Password must be at least 8 characters.";
  if (!/[A-Za-z]/.test(s)) return "Password must include at least one letter.";
  if (!/[0-9]/.test(s)) return "Password must include at least one number.";
  return null;
}

/* ---- Password hashing (bcrypt) -------------------------------------------
 * Legacy rows predating hashing may still hold plaintext — verifyPassword()
 * detects that (a bcrypt hash looks like "$2a$10$...") and falls back to a
 * plain compare, then the login route calls upgradePasswordIfNeeded() to
 * hash it in place. Avoids needing a manual migration.
 * ------------------------------------------------------------------------- */
function isBcryptHash(s) {
  return typeof s === "string" && /^\$2[aby]?\$\d{2}\$/.test(s);
}

export async function hashPassword(plain) {
  return bcrypt.hash(String(plain), 10);
}

/** Compare a plaintext password against a stored (hashed or legacy plaintext) value. */
export async function verifyPassword(plain, stored) {
  if (!stored) return false;
  if (isBcryptHash(stored)) return bcrypt.compare(String(plain), stored);
  return String(plain) === stored; // legacy pre-hashing row
}

/** After a successful login, hash-and-persist any account still on a legacy plaintext password. */
export async function upgradePasswordIfNeeded(account, plainPassword) {
  if (isBcryptHash(account.password)) return;
  await run("UPDATE accounts SET password = $1 WHERE id = $2", [await hashPassword(plainPassword), account.id]);
}

/** readOnly=true gives a "read-only Admin": every key true EXCEPT the
 *  action-group (write) ones, which are forced false — full visibility, zero
 *  write capability. Meaningless (ignored) for role="staff". */
export function defaultPermsForRole(role, readOnly = false) {
  if (role === "admin") {
    const all = Object.fromEntries(PERM_KEYS.map((k) => [k, true]));
    if (readOnly) for (const k of ACTION_KEYS) all[k] = false;
    return cleanPermissions(all);
  }
  return cleanPermissions({ manageDelegates: true }); // staff
}

function cleanPerms(input) {
  return cleanPermissions(input);
}

/** Coerce any input into exactly "admin" or "staff" (defaults to "staff" for
 *  anything else, including the retired "main" role on legacy rows). */
export function cleanRole(role) {
  return role === "admin" ? "admin" : "staff";
}

/** Parsed permissions for an account row. Admins bypass entirely (always
 *  every permission true, or every-but-action if flagged readOnly); staff
 *  get their stored checkboxes, falling back to the staff defaults if the
 *  stored JSON is missing/corrupt. */
export function accountPermissions(row) {
  if (!row) return cleanPerms({});
  if (row.role === "admin") return defaultPermsForRole("admin", !!row.readOnly);
  let perms;
  try {
    perms = row.permissions ? cleanPerms(JSON.parse(row.permissions)) : defaultPermsForRole("staff");
  } catch {
    perms = defaultPermsForRole("staff");
  }
  // View permissions (desktopView/mobileView groups) are always granted — see
  // AccountControlPage.jsx's EMPTY_FORM comment: "an account can always SEE
  // every page/tab", the two access dropdowns only ever control WRITE
  // capability. applyAccessLevels() (accountHelpers.js) already enforces this
  // for every account saved through the current New/Edit form, but it only
  // runs when that form is actually touched — an account whose permissions
  // JSON still carries an explicit `false` for a view key from BEFORE the
  // 2026-07-31 redesign (the old per-permission checkbox tree let an admin
  // individually uncheck e.g. Announcements) stays stuck on that stale value
  // forever otherwise, since editing an existing account loads its permissions
  // as-is (AccountControlPage.jsx's openEdit) and only applyAccessLevels()
  // would normalize it, which nothing forces the admin to trigger. Enforcing
  // the same invariant here, at the single canonical resolver every read path
  // (login, account listing/editing, ViewGate authorization) goes through,
  // self-heals every such account immediately with no per-account re-save
  // needed (2026-08-08 — "why this role not allow staff to see the
  // announcement page").
  for (const p of PERMISSIONS) {
  if (p.group === "desktopView" || p.group === "mobileView") permissions[p.key] = true;
}
  return perms;
}

/** Count of FULL (non-read-only) admin accounts — used to block
 *  removing/demoting/read-only-flagging the last one, which would otherwise
 *  lock everyone out of Account control (a read-only admin can see the page
 *  but has no manageAccounts permission to act on it). */
async function countAdmins() {
  return (await all("SELECT role, \"readOnly\" FROM accounts")).filter((a) => a.role === "admin" && !a.readOnly).length;
}

function accountPublic(row) {
  if (!row) return null;
  const { password, permissions, token_version, ...rest } = row; // never expose password / raw JSON / session counter
  return { ...rest, role: cleanRole(row.role), permissions: accountPermissions(row), status: row.status || "approved" };
}

/* ---- Email ---------------------------------------------------------------
 * Stored plain text, not hashed — only the password field is ever bcrypt'd.
 * Deliberately permissive check: rejects obvious garbage without failing a
 * real address on a pedantic RFC edge case. */
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export function emailProblem(email) {
  const s = String(email || "").trim();
  if (!s) return "Email is required.";
  if (!EMAIL_RE.test(s)) return "Please enter a valid email address.";
  return null;
}
export async function getAccountByEmail(email) {
  const s = String(email || "").trim().toLowerCase();
  if (!s) return null;
  return get("SELECT * FROM accounts WHERE lower(email) = $1", [s]);
}

/**
 * Bump token_version and return the new value. Any token minted with the
 * previous version stops validating (see accountFromReq in auth.js), so an
 * older browser is logged out on its next poll. Login route only.
 */
export async function startNewSession(id) {
  const row = await get(`UPDATE accounts SET token_version = token_version + 1 WHERE id = $1 RETURNING token_version`, [id]);
  return row?.token_version ?? 0;
}

/** Stamp "seen right now" — called from GET /api/auth/session (polled every
 *  15s). Powers the Staff Operations "active now" list. Call fire-and-forget:
 *  a failed stamp must not fail the session check itself. */
export async function touchLastSeen(id) {
  await run(`UPDATE accounts SET last_seen_at = now() WHERE id = $1`, [id]);
}

/** Clears last_seen_at on explicit logout so "active now" drops the account
 *  immediately instead of waiting ~45s to age out. POST /api/auth/logout. */
export async function clearLastSeen(id) {
  await run(`UPDATE accounts SET last_seen_at = NULL WHERE id = $1`, [id]);
}

/** Accounts seen within the last `withinSeconds`. Same accountPublic() shape
 *  as listAccounts() so the frontend reuses its role/permission-chip render. */
export async function listActiveAccounts(withinSeconds = 45) {
  const rows = await all(
    `SELECT * FROM accounts WHERE last_seen_at IS NOT NULL AND last_seen_at > now() - ($1 || ' seconds')::interval ORDER BY last_seen_at DESC`,
    [withinSeconds]
  );
  return rows.map(accountPublic);
}

async function nextAccountId() {
  // Must filter to "u-<number>" rows: the seeded "__kiosk__" account uses the
  // non-numeric id "u-kiosk" (db/schema.js seed()), which breaks the CAST.
  const row = await get(`SELECT COALESCE(MAX(CAST(SUBSTRING(id FROM 3) AS INTEGER)), 0) AS m FROM accounts WHERE id ~ '^u-[0-9]+$'`);
  return `u-${Number(row?.m || 0) + 1}`;
}

/** Full row incl. password — used only for login / auth checks. */
export async function getAccountByUsername(username) {
  return get("SELECT * FROM accounts WHERE username = $1", [String(username || "").trim()]);
}

export async function listAccounts() {
  // Hide the internal __kiosk__ account (db/schema.js seed()) — plumbing for
  // passwordless check-ins, must never appear in Account control or staff tiles.
  return (await all("SELECT * FROM accounts WHERE username <> '__kiosk__' ORDER BY id")).map(accountPublic);
}

export async function createAccount(input) {
  const username = String(input.username || "").trim();
  const password = String(input.password || "");
  const email = String(input.email || "").trim();
  const phone = String(input.phone || "").trim();
  const name = String(input.name || "").trim() || username;
  // An admin's checkboxes are moot (accountPermissions() bypasses them all),
  // so store the admin-default set for a clean "Access" display; staff keep
  // whatever was submitted.
  const role = cleanRole(input.role);
  const readOnly = role === "admin" && !!input.readOnly;
  const perms = role === "admin" ? defaultPermsForRole("admin", readOnly) : cleanPerms(input.permissions);

  if (!username) return { error: "USERNAME_REQUIRED" };
  if (!password) return { error: "PASSWORD_REQUIRED" };
  const pwProblem = passwordProblem(password);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
  // Required for every NEW account (here and registerAccount()) — legacy
  // accounts with no email on file are untouched and keep working.
  const emailErr = emailProblem(email);
  if (emailErr) return { error: "EMAIL_REQUIRED", message: emailErr };
  if (await getAccountByUsername(username)) return { error: "USERNAME_TAKEN" };
  if (await getAccountByEmail(email)) return { error: "EMAIL_TAKEN" };

  const id = await nextAccountId();
  // status defaults to 'approved' (schema.js) — an admin creating an account
  // IS the approval, unlike registerAccount(), which starts 'pending'.
  await run(`INSERT INTO accounts (id, username, name, email, phone, password, role, permissions, "readOnly", "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`, [
    id, username, name, email, phone || null, await hashPassword(password), role, JSON.stringify(perms), readOnly, new Date().toISOString(),
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/**
 * Public self-service sign-up. SECURITY: always role="staff" (registration
 * can never mint an admin) and always status="pending" — the row exists but
 * CANNOT log in (status check in routes/auth.js's login route) until an admin
 * approves. Otherwise identical validation/hashing/uniqueness to
 * createAccount().
 */
export async function registerAccount(input) {
  const username = String(input.username || "").trim();
  const password = String(input.password || "");
  const email = String(input.email || "").trim();
  const name = username;

  if (!username) return { error: "USERNAME_REQUIRED" };
  if (!password) return { error: "PASSWORD_REQUIRED" };
  const pwProblem = passwordProblem(password);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
  const emailErr = emailProblem(email);
  if (emailErr) return { error: "EMAIL_REQUIRED", message: emailErr };
  if (await getAccountByUsername(username)) return { error: "USERNAME_TAKEN" };
  if (await getAccountByEmail(email)) return { error: "EMAIL_TAKEN" };

  const id = await nextAccountId();
  const perms = defaultPermsForRole("staff");
  await run(
    `INSERT INTO accounts (id, username, name, email, password, role, permissions, "createdAt", status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'pending')`,
    [id, username, name, email, await hashPassword(password), "staff", JSON.stringify(perms), new Date().toISOString()]
  );
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/** Accounts awaiting admin review, oldest first — the "Pending approval"
 *  list on Account control. */
export async function listPendingAccounts() {
  return (await all("SELECT * FROM accounts WHERE status = 'pending' ORDER BY \"createdAt\" ASC")).map(accountPublic);
}

export async function approveAccount(id) {
  const existing = await get("SELECT id FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };
  await run("UPDATE accounts SET status = 'approved' WHERE id = $1", [id]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/** Rejecting RETAINS the row rather than deleting it: audit trail of who was
 *  turned down, and deletion would free the username/email for the rejected
 *  applicant to re-register. A rejected account can never log in (see
 *  routes/auth.js); DELETE /api/accounts/:id still hard-deletes if wanted. */
export async function rejectAccount(id) {
  const existing = await get("SELECT id FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };
  await run("UPDATE accounts SET status = 'rejected' WHERE id = $1", [id]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/** Bulk approve/reject in one UPDATE (Pending approval card's "Approve all"/
 *  "Reject all"). Returns rows actually flipped, so the UI shows a real count
 *  even if the pending list changed underneath (another admin acted first). */
export async function approveAllPending() {
  const rows = await all("UPDATE accounts SET status = 'approved' WHERE status = 'pending' RETURNING id");
  return { count: rows.length };
}

export async function rejectAllPending() {
  const rows = await all("UPDATE accounts SET status = 'rejected' WHERE status = 'pending' RETURNING id");
  return { count: rows.length };
}

export async function updateAccount(id, patch) {
  const existing = await get("SELECT * FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  const username = patch.username !== undefined ? String(patch.username).trim() : existing.username;
  const name = patch.name !== undefined ? String(patch.name).trim() || username : existing.name;
  const role = patch.role !== undefined ? cleanRole(patch.role) : cleanRole(existing.role);
  const readOnly = role === "admin" ? !!(patch.readOnly !== undefined ? patch.readOnly : existing.readOnly) : false;
  const perms = role === "admin"
    ? defaultPermsForRole("admin", readOnly)
    : (patch.permissions ? cleanPerms(patch.permissions) : accountPermissions(existing));

  let password = existing.password;
  if (patch.password) {
    const pwProblem = passwordProblem(String(patch.password));
    if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
    password = await hashPassword(String(patch.password));
  }

  // Only validated/changed if explicitly in the patch — NOT force-required,
  // so a legacy account with no email can still be edited (e.g. role change).
  let email = existing.email;
  if (patch.email !== undefined) {
    const nextEmail = String(patch.email).trim();
    const emailErr = emailProblem(nextEmail);
    if (emailErr) return { error: "EMAIL_REQUIRED", message: emailErr };
    email = nextEmail;
  }

  const phone = patch.phone !== undefined ? String(patch.phone).trim() : existing.phone;

  if (!username) return { error: "USERNAME_REQUIRED" };
  const clash = await getAccountByUsername(username);
  if (clash && clash.id !== id) return { error: "USERNAME_TAKEN" };
  if (email && email !== existing.email) {
    const emailClash = await getAccountByEmail(email);
    if (emailClash && emailClash.id !== id) return { error: "EMAIL_TAKEN" };
  }

  // Block demoting the last FULL admin (to staff, OR to read-only) — either
  // way would lock everyone out of Account control (a read-only admin can
  // view the page but has no manageAccounts permission to act on it).
  const wasFullAdmin = cleanRole(existing.role) === "admin" && !existing.readOnly;
  const staysFullAdmin = role === "admin" && !readOnly;
  if (wasFullAdmin && !staysFullAdmin && (await countAdmins()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run(`UPDATE accounts SET username=$1, name=$2, email=$3, phone=$4, password=$5, role=$6, permissions=$7, "readOnly"=$8 WHERE id=$9`, [
    username, name, email, phone || null, password, role, JSON.stringify(perms), readOnly, id,
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/**
 * Self-service "edit my own profile" (Settings page). SECURITY: deliberately
 * NOT a wrapper around updateAccount() — this is reachable by ANY signed-in
 * account (requireAuth only, no manageAccounts — see PATCH /api/auth/me), so
 * it must NEVER touch role or permissions. A password change here requires
 * the CURRENT password, since the caller could be someone at an unlocked
 * device on a live session.
 */
export async function updateOwnAccount(id, patch) {
  const existing = await get("SELECT * FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  const username = patch.username !== undefined ? String(patch.username).trim() : existing.username;
  const name = patch.name !== undefined ? String(patch.name).trim() || username : existing.name;

  let email = existing.email;
  if (patch.email !== undefined) {
    const nextEmail = String(patch.email).trim();
    const emailErr = emailProblem(nextEmail);
    if (emailErr) return { error: "EMAIL_REQUIRED", message: emailErr };
    email = nextEmail;
  }

  const phone = patch.phone !== undefined ? String(patch.phone).trim() : existing.phone;

  let password = existing.password;
  if (patch.newPassword) {
    if (!(await verifyPassword(patch.currentPassword, existing.password))) {
      return { error: "CURRENT_PASSWORD_INCORRECT" };
    }
    const pwProblem = passwordProblem(String(patch.newPassword));
    if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };
    password = await hashPassword(String(patch.newPassword));
  }

  if (!username) return { error: "USERNAME_REQUIRED" };
  const clash = await getAccountByUsername(username);
  if (clash && clash.id !== id) return { error: "USERNAME_TAKEN" };
  if (email && email !== existing.email) {
    const emailClash = await getAccountByEmail(email);
    if (emailClash && emailClash.id !== id) return { error: "EMAIL_TAKEN" };
  }

  await run(`UPDATE accounts SET username=$1, name=$2, email=$3, phone=$4, password=$5 WHERE id=$6`, [
    username, name, email, phone || null, password, id,
  ]);
  return { account: accountPublic(await get("SELECT * FROM accounts WHERE id = $1", [id])) };
}

/** Own-profile photo — mirrors setDelegatePhoto()/clearDelegatePhoto() in
 *  db/delegates.js on the accounts table. Returns the previous photoPublicId
 *  so the caller can clean up the old Cloudinary asset. */
export async function setAccountPhoto(id, url, publicId) {
  const existing = await get('SELECT "photoPublicId" FROM accounts WHERE id = $1', [id]);
  if (!existing) return null;
  await run('UPDATE accounts SET "photoUrl" = $1, "photoPublicId" = $2 WHERE id = $3', [url, publicId, id]);
  return existing.photoPublicId || null;
}
export async function clearAccountPhoto(id) {
  const existing = await get('SELECT "photoPublicId" FROM accounts WHERE id = $1', [id]);
  if (!existing) return null;
  await run('UPDATE accounts SET "photoUrl" = NULL, "photoPublicId" = NULL WHERE id = $1', [id]);
  return existing.photoPublicId || null;
}

/**
 * "Forgot password" reset — username + new password, NO identity
 * verification (no old password, no email/OTP). WARNING: only acceptable for
 * this project's small trusted-team context; NOT safe for a public
 * deployment, where knowing a username is enough to take over the account.
 * Bumps token_version so existing sessions are invalidated.
 */
export async function resetPassword(username, newPassword) {
  const pwProblem = passwordProblem(newPassword);
  if (pwProblem) return { error: "WEAK_PASSWORD", message: pwProblem };

  const existing = await getAccountByUsername(username);
  if (!existing) {
    // Generic error either way — avoids confirming which usernames exist.
    return { error: "RESET_FAILED" };
  }

  await run(`UPDATE accounts SET password = $1, token_version = token_version + 1 WHERE id = $2`, [
    await hashPassword(newPassword), existing.id,
  ]);
  return { ok: true };
}

export async function deleteAccount(id) {
  const existing = await get("SELECT * FROM accounts WHERE id = $1", [id]);
  if (!existing) return { error: "NOT_FOUND" };

  if (cleanRole(existing.role) === "admin" && (await countAdmins()) <= 1) {
    return { error: "LAST_MAIN" };
  }

  await run("DELETE FROM accounts WHERE id = $1", [id]);
  return { deleted: true };
}

/* ---- Role templates ------------------------------------------------------
 * Admin-managed named permission presets (Account control's "Apply template"
 * quick-fill + "Access role" filter). Never a stored tag on an account:
 * matchRoleTemplate() compares CURRENT stored permissions against current
 * templates, so editing/deleting a template can never retroactively change
 * what an existing account can do — only which bucket it displays in.
 * -------------------------------------------------------------------------- */
function roleTemplatePublic(row) {
  if (!row) return null;
  let permissions = {};
  try { permissions = JSON.parse(row.permissions || "{}"); } catch { /* corrupt row — treat as empty */ }
  return { id: row.id, label: row.label, permissions: cleanPermissions(permissions), createdAt: row.createdAt };
}

export async function listRoleTemplates() {
  return (await all(`SELECT * FROM role_templates ORDER BY "createdAt"`)).map(roleTemplatePublic);
}

async function nextRoleTemplateId() {
  const base = "role";
  const existing = new Set((await all(`SELECT id FROM role_templates`)).map((r) => r.id));
  let n = 1;
  while (existing.has(`${base}-${n}`)) n++;
  return `${base}-${n}`;
}

export async function createRoleTemplate(input) {
  const label = String(input?.label || "").trim();
  if (!label) return { error: "LABEL_REQUIRED" };
  const id = await nextRoleTemplateId();
  const permissions = cleanPermissions(input?.permissions);
  await run(`INSERT INTO role_templates (id, label, permissions, "createdAt") VALUES ($1,$2,$3,$4)`, [
    id, label, JSON.stringify(permissions), new Date().toISOString(),
  ]);
  return { template: roleTemplatePublic(await get(`SELECT * FROM role_templates WHERE id = $1`, [id])) };
}

export async function updateRoleTemplate(id, patch) {
  const existing = await get(`SELECT * FROM role_templates WHERE id = $1`, [id]);
  if (!existing) return { error: "NOT_FOUND" };
  const label = patch?.label !== undefined ? String(patch.label).trim() : existing.label;
  if (!label) return { error: "LABEL_REQUIRED" };
  const permissions = patch?.permissions !== undefined
    ? cleanPermissions(patch.permissions)
    : JSON.parse(existing.permissions || "{}");
  await run(`UPDATE role_templates SET label = $1, permissions = $2 WHERE id = $3`, [label, JSON.stringify(permissions), id]);
  return { template: roleTemplatePublic(await get(`SELECT * FROM role_templates WHERE id = $1`, [id])) };
}

export async function deleteRoleTemplate(id) {
  const existing = await get(`SELECT id FROM role_templates WHERE id = $1`, [id]);
  if (!existing) return { error: "NOT_FOUND" };
  await run(`DELETE FROM role_templates WHERE id = $1`, [id]);
  return { deleted: true };
}

/** Which template a STAFF account's current permissions match — Account
 *  control's "Access role" filter/badge. null means "Custom". Only meaningful
 *  for role="staff" (admins bypass permissions); callers skip admins. */
export function matchRoleTemplate(permissions, templates) {
  for (const tpl of templates) {
    if (Object.entries(tpl.permissions).every(([k, v]) => !!permissions?.[k] === v)) return tpl.id;
  }
  return null;
}
