/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * History tracker (persisted activity log) — split out of the old
 * monolithic data.js (2026-07-21). Was an in-memory array capped at 8
 * entries and wiped on every restart; now stored in activity_log so history
 * survives restarts and accumulates over time.
 *
 * No dependency on db/delegates.js — logActivity() just writes a row, it
 * doesn't need to know anything about a delegate beyond the id/changes
 * metadata the caller hands it. (delegates.js imports logActivity FROM here,
 * not the other way around, so there's no import cycle.)
 */

import { all, get, run } from "./connection.js";

export async function logActivity(text, kind, actor = null, meta = null) {
  const id = `a-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  const delegateId = meta?.delegateId || null;
  const changes = meta?.changes && Object.keys(meta.changes).length ? meta.changes : null;
  await run(
    `INSERT INTO activity_log (id, text, kind, actor, delegate_id, changes) VALUES ($1,$2,$3,$4,$5,$6)`,
    [id, text, kind, actor || null, delegateId, changes ? JSON.stringify(changes) : null]
  );
}

function rowToActivity(row) {
  return {
    id: row.id,
    text: row.text,
    kind: row.kind,
    time: new Date(row.createdAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }),
    // Who did it — the acting account's name. Legacy rows (and writes with no
    // actor) have none; fall back to "you" (the frontend translates that).
    via: row.actor || "you",
    createdAt: row.createdAt,
    // Rollback support — present only on delegate-edit entries that changed
    // at least one field (see updateDelegate() in db/delegates.js). The
    // frontend only offers a Rollback button when both are set.
    delegateId: row.delegate_id || null,
    changes: row.changes || null,
  };
}

/** Most recent activity entries, newest first. `limit` defaults to a small
 *  preview (matches the old in-memory cap) — the Dashboard's History tracker
 *  card asks for a much larger limit to show real history. */
export async function getActivity(limit = 8) {
  const rows = await all(`SELECT * FROM activity_log ORDER BY "createdAt" DESC LIMIT $1`, [limit]);
  return rows.map(rowToActivity);
}

export async function deleteActivity(id) {
  const existing = await get("SELECT id FROM activity_log WHERE id = $1", [id]);
  if (!existing) return false;
  await run("DELETE FROM activity_log WHERE id = $1", [id]);
  return true;
}

export async function deleteAllActivity() {
  const count = Number((await get("SELECT COUNT(*) AS c FROM activity_log"))?.c || 0);
  await run("DELETE FROM activity_log");
  return count;
}
