/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * Schema creation + seed data — split out of the old monolithic data.js
 * (2026-07-21). The database schema and seed data (first admin account,
 * trip, coaches) are created automatically on first run — nobody sets those
 * up by hand. Depends on db/accounts.js (hashPassword, defaultPermsForRole)
 * and db/constants.js (TRIP, COACHES) — one-directional, neither depends
 * back on this file.
 *
 * Postgres syntax notes vs. MySQL: VARCHAR sizes are optional but kept for
 * clarity, TINYINT(1) -> BOOLEAN, and reserved words `lead`/`localTime` still
 * need double-quoting (Postgres lower-cases unquoted identifiers, and our
 * columns are camelCase, so every mixed-case column name is quoted).
 */

import { all, get, run } from "./connection.js";
import { TRIP, COACHES } from "./constants.js";
import { hashPassword, defaultPermsForRole } from "./accounts.js";

export async function createSchema() {
  /* ---- JQ base tables (Dashboard / Auth / Accounts) --------------------- */
  await run(`CREATE TABLE IF NOT EXISTS trips (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), "dateRange" VARCHAR(255), "dayOf" INT,
    "totalDays" INT, "lead" VARCHAR(255), status VARCHAR(255), "localTime" VARCHAR(64), "departsIn" VARCHAR(64)
  )`);
  await run(`CREATE TABLE IF NOT EXISTS coaches (
    id VARCHAR(64) PRIMARY KEY, label VARCHAR(64), name VARCHAR(255), city VARCHAR(255), capacity INT
  )`);
  await run(`CREATE TABLE IF NOT EXISTS delegates (
    id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), initials VARCHAR(16), "coachId" VARCHAR(64),
    status VARCHAR(32), vip BOOLEAN, "lastSeen" VARCHAR(255)
  )`);
  // When each delegate was first added (upload/creation time) — powers the
  // "Uploaded" column + "recently added" sort on the Dashboard. Additive: a
  // NOT NULL DEFAULT now() means existing rows get the migration time and new
  // rows default to their insert time (createDelegate doesn't set it).
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()`);
  // Profile photo — set only via POST /api/delegates/:id/photo (uploads
  // through Cloudinary, see uploadDelegatePhoto in server.js), never via the
  // plain PATCH /api/delegates/:id JSON route, so a client can't just PATCH
  // in an arbitrary external URL and bypass the upload validation entirely.
  // photoPublicId is Cloudinary's asset id, kept so the old image can be
  // destroyed on Cloudinary when replaced or removed (otherwise it's an
  // orphaned asset forever).
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "photoUrl" TEXT`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "photoPublicId" TEXT`);
  // Last known location — a free-text place/address (e.g. "Novotel Beijing,
  // Lobby" or a full street address), staff-entered, separate from
  // "lastSeen" (which is a time/note, not a lookup-able place). Rendered as
  // an embedded Google Map (Maps Embed API — a static <iframe>, no live
  // tracking) wherever a delegate's location matters, especially the
  // missing-delegates list. Not geocoded/validated server-side; the Embed
  // API's `q=` param accepts free text and looks it up itself.
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "lastLocation" VARCHAR(255)`);
  // Who added this delegate — the account's display name at creation time
  // (a snapshot, not a live FK to accounts, so it stays correct even if that
  // account is later renamed or deleted). Powers the Dashboard's "Created By"
  // column. NULL for rows created before this column existed, or by a route
  // that doesn't pass an actor (e.g. teammate check-in modules importing a
  // roster directly) — those show "—" in the UI rather than a guessed name.
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS "createdBy" VARCHAR(255)`);
  await run(`CREATE TABLE IF NOT EXISTS accounts (
    id VARCHAR(64) PRIMARY KEY, username VARCHAR(191) UNIQUE, name VARCHAR(255),
    password VARCHAR(255), role VARCHAR(32), permissions TEXT, "createdAt" VARCHAR(64)
  )`);
  // Single active session per account: each login bumps this, and a token is
  // only valid while its embedded version matches. So signing in on a new
  // browser invalidates the token held by any older one (which then gets
  // logged out by the session poll in the frontend Layout).
  await run(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS token_version INT NOT NULL DEFAULT 0`);
  // Stamped on every GET /api/auth/session call — every signed-in client
  // already polls that endpoint every 15s for the force-logout guard, so this
  // piggybacks on existing traffic instead of adding new polling. Powers the
  // Staff Operations dashboard's "active now" list (accounts seen in the last
  // ~45s, comfortably wider than the 15s poll interval).
  await run(`ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ`);

  /* ---- Desmond "TransitFlow" schema (Trip Booking & Coach Management) ----
   * Folded in from what originally shipped as database/003_*.sql + 004_*.sql.
   * ALL ADDITIVE: new tables + `ADD COLUMN IF NOT EXISTS` on the base tables
   * above — it never changes/drops anything the base app relies on (trips.id,
   * coaches.id, delegates.id all stay VARCHAR text like "t-1"/"c1"), and every
   * statement is idempotent so it re-runs harmlessly on each startup.
   * --------------------------------------------------------------------- */
  await run(`CREATE EXTENSION IF NOT EXISTS pgcrypto`); // for gen_random_uuid()

  // trips: a parallel UUID identity. The base trips.id stays "t-1"; every new
  // table/column below references this uuid_id instead, so they're real UUIDs.
  await run(`ALTER TABLE trips ADD COLUMN IF NOT EXISTS uuid_id UUID UNIQUE DEFAULT gen_random_uuid()`);
  await run(`UPDATE trips SET uuid_id = gen_random_uuid() WHERE uuid_id IS NULL`);
  // Per-trip Late-status cutoff ("HH:MM", 24-hour, server-local) — was a
  // single hardcoded 10:00 global constant in applyLateCutoff() (db/delegates
  // .js); admins can now set this per trip (desmond.js's PATCH /api/trips/:id/
  // late-cutoff). DEFAULT '10:00' both for brand-new trips AND backfills
  // every existing trip row to the same value this used to be hardcoded to,
  // so nothing's behavior silently changes for a trip nobody has touched.
  await run(`ALTER TABLE trips ADD COLUMN IF NOT EXISTS "lateCutoffTime" VARCHAR(8) DEFAULT '10:00'`);

  // users: a lightweight staff directory for coach assignment ONLY (a "guide"
  // per coach). Separate from `accounts` — these rows never sign in anywhere.
  await run(`CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE,
    role VARCHAR(32) NOT NULL DEFAULT 'staff', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`);

  // coaches: trip link, assigned guide, board order, driver name.
  // sort_order is intentionally added WITHOUT a default so seed() can tell
  // "never positioned" (NULL) apart and backfill a stable order first.
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS trip_id       UUID REFERENCES trips(uuid_id)`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS staff_user_id UUID REFERENCES users(id)`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS sort_order    INT`);
  await run(`ALTER TABLE coaches ADD COLUMN IF NOT EXISTS driver_name   VARCHAR(255)`);

  // delegates: trip link + optional free-text fields shown on the board.
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS trip_id             UUID REFERENCES trips(uuid_id)`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS notes               TEXT`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS company             VARCHAR(255)`);
  await run(`ALTER TABLE delegates ADD COLUMN IF NOT EXISTS accessibility_notes TEXT`);

  // itinerary_items: per-trip schedule strip driving the journey timeline.
  await run(`CREATE TABLE IF NOT EXISTS itinerary_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID NOT NULL REFERENCES trips(uuid_id) ON DELETE CASCADE,
    day_number INT NOT NULL, start_time TIME NOT NULL, title TEXT NOT NULL,
    location TEXT, sort_order INT NOT NULL DEFAULT 0,
    category VARCHAR(24) NOT NULL DEFAULT 'other'
      CHECK (category IN ('hotel','attraction','meal','factory','airport','transport','other'))
  )`);

  // Indexes for the trip-scoped lookups desmond.js runs.
  await run(`CREATE INDEX IF NOT EXISTS idx_coaches_trip   ON coaches(trip_id)`);
  await run(`CREATE INDEX IF NOT EXISTS idx_delegates_trip ON delegates(trip_id)`);
  await run(`CREATE INDEX IF NOT EXISTS idx_itinerary_trip ON itinerary_items(trip_id, day_number, sort_order)`);

  // History tracker: the Dashboard's activity feed. Previously an in-memory
  // array capped at 8 entries — wiped on every backend restart. Now a real
  // table so past activity survives restarts and accumulates indefinitely.
  await run(`CREATE TABLE IF NOT EXISTS activity_log (
    id VARCHAR(64) PRIMARY KEY, text TEXT NOT NULL, kind VARCHAR(32),
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
  )`);
  // actor = the account name that performed the action, so the History
  // tracker can show WHO made each change instead of a generic "you".
  // Nullable: rows created before this column (and any write that doesn't
  // pass an actor) fall back to "you" in rowToActivity() (db/history.js).
  await run(`ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS actor TEXT`);
  // Field-level rollback support: delegate_id ties an entry back to the row
  // it changed; changes is {field: {from, to}} for whatever actually
  // differed in that one update (see updateDelegate()'s diff in
  // db/delegates.js). Only ever set on delegate-edit entries — add/remove
  // entries stay non-rollbackable (out of scope for this pass; see AI Log).
  await run(`ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS delegate_id VARCHAR(64)`);
  await run(`ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS changes JSONB`);
  await run(`CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log("createdAt" DESC)`);
}

export async function seed() {
  // First "admin" account (once) — was seeded as role "main" before the RBAC
  // simplification to exactly Admin/Staff; see the migration right below this
  // for existing shared-DB rows still holding the retired "main" value.
  if (!(await get("SELECT id FROM accounts LIMIT 1"))) {
    const perms = defaultPermsForRole("admin");
    await run(`INSERT INTO accounts (id, username, name, password, role, permissions, "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7)`, [
      "u-1", "staff_194", "Staff 194", await hashPassword("password123!"), "admin", JSON.stringify(perms), new Date().toISOString(),
    ]);
  }
  // Migration: the team's shared Neon DB has real accounts already seeded
  // with the retired "main" role from before RBAC was simplified to exactly
  // Admin/Staff. Runs on every startup (idempotent — a no-op once none are
  // left) so every deploy picks it up without a manual DB fix.
  await run(`UPDATE accounts SET role = 'admin' WHERE role = 'main'`);
  // Passwordless-kiosk backing account. The entrance scanner (KioskScannerPage
  // .jsx) mints a scoped {kiosk:true} token (auth.js signKioskToken) that grants
  // ONLY the two camera check-in endpoints; requireKioskOrAuth() maps those
  // requests to THIS row so writes that FK onto accounts.id (check_in_logs
  // .checked_in_by) still resolve. It has an unguessable random password and is
  // never meant to be logged into via the password flow. Role "staff" (its
  // stored permissions are moot — requireKioskOrAuth never checks them, and no
  // password login can reach it).
  if (!(await get("SELECT id FROM accounts WHERE username = $1", ["__kiosk__"]))) {
    const throwaway = `kiosk-${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
    await run(`INSERT INTO accounts (id, username, name, password, role, permissions, "createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7)`, [
      "u-kiosk", "__kiosk__", "Entrance Kiosk", await hashPassword(throwaway), "staff", JSON.stringify(defaultPermsForRole("staff")), new Date().toISOString(),
    ]);
  }
  // Trip (once).
  if (!(await get("SELECT id FROM trips LIMIT 1"))) {
    await run(
      `INSERT INTO trips (id, name, "dateRange", "dayOf", "totalDays", "lead", status, "localTime", "departsIn") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
      [TRIP.id, TRIP.name, TRIP.dateRange, TRIP.dayOf, TRIP.totalDays, TRIP.lead, TRIP.status, TRIP.localTime, TRIP.departsIn]
    );
  }
  // Coaches (once).
  if (!(await get("SELECT id FROM coaches LIMIT 1"))) {
    for (const c of COACHES) {
      await run("INSERT INTO coaches (id, label, name, city, capacity) VALUES ($1,$2,$3,$4,$5)", [c.id, c.label, c.name, c.city, c.capacity]);
    }
  }

  // Desmond "TransitFlow" seed + backfill (folded from database/003_*.sql).
  await seedTransitFlow();
}

/* Seed the staff directory and attach existing coaches/delegates to the
 * Beijing trip so nothing "disappears" once the trip board filters by trip_id.
 * Everything here is idempotent (ON CONFLICT / WHERE ... IS NULL), so it runs
 * safely on every startup — it only ever fills gaps, never overwrites edits. */
async function seedTransitFlow() {
  // 1. Staff directory (6 people) — assignment targets only, not login accounts.
  await run(`
    INSERT INTO users (name, email, role) VALUES
      ('Rachel Tan Hui Min',       'rachel.tan@example.com',   'staff'),
      ('Marcus Lim Wei Jie',       'marcus.lim@example.com',   'staff'),
      ('Priya Suresh',             'priya.suresh@example.com', 'staff'),
      ('Muhammad Hafiz Bin Rosli', 'hafiz.rosli@example.com',  'staff'),
      ('Jonathan Koh Zhi Hao',     'jonathan.koh@example.com', 'admin'),
      ('Serene Ng Xin Yi',         'serene.ng@example.com',    'admin')
    ON CONFLICT (email) DO NOTHING
  `);

  // 2. Attach existing coaches + delegates to the Beijing trip (t-1).
  await run(`UPDATE coaches   SET trip_id = (SELECT uuid_id FROM trips WHERE id = 't-1')
             WHERE trip_id IS NULL AND EXISTS (SELECT 1 FROM trips WHERE id = 't-1')`);
  await run(`UPDATE delegates SET trip_id = (SELECT uuid_id FROM trips WHERE id = 't-1')
             WHERE trip_id IS NULL AND EXISTS (SELECT 1 FROM trips WHERE id = 't-1')`);

  // 3. Give every coach a stable board position (by id order) if it has none,
  //    then set a default for future inserts.
  await run(`
    WITH ordered AS (
      SELECT id, ROW_NUMBER() OVER (ORDER BY id) - 1 AS rn FROM coaches WHERE sort_order IS NULL
    )
    UPDATE coaches SET sort_order = ordered.rn FROM ordered WHERE coaches.id = ordered.id
  `);
  await run(`ALTER TABLE coaches ALTER COLUMN sort_order SET DEFAULT 0`);

  // 4. Round-robin a guide onto any coach that has none, so "every coach has a
  //    staff member" holds immediately (done in JS rather than a plpgsql block).
  const staff = await all("SELECT id FROM users ORDER BY email");
  if (staff.length) {
    const unassigned = await all(`SELECT id FROM coaches WHERE staff_user_id IS NULL ORDER BY sort_order NULLS LAST, id`);
    for (let i = 0; i < unassigned.length; i++) {
      await run("UPDATE coaches SET staff_user_id = $1 WHERE id = $2", [staff[i % staff.length].id, unassigned[i].id]);
    }
  }
}
