/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see OWNSHIP.md at the project root.
 * ============================================================================= */
/** Delegate CRUD + profile photo routes — split out of server.js. */
import { Router } from "express";
import multer from "multer";
import { wrap } from "../../lib/wrap.js";
import { actorOf } from "../../lib/actor.js";
import { requireAuth, requirePermission } from "../../lib/auth.js";
import { isConfigured as photoStorageConfigured, uploadImage, destroyImage } from "../../lib/cloudinary.js";
import {
  resolveTripUuid,
  listDelegates,
  getDelegateById,
  createDelegate,
  updateDelegate,
  deleteDelegate,
  deleteAllDelegates,
  setDelegatePhoto,
  clearDelegatePhoto,
  getVisibleCoachIds,
  canModifyDelegate,
  canLockDelegate,
} from "../../data.js";
import { syncCurrentCheckpointStatus } from "./checkpoints.js";

const router = Router();

// Memory storage — the buffer goes straight to Cloudinary, never to disk. The
// 5MB cap and MIME filter are only the first layer; Cloudinary's image decode
// (resource_type: "image" in cloudinary.js) is the real check, since a client
// can claim any MIME type.
const photoUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    if (!file.mimetype.startsWith("image/")) return cb(new Error("UNSUPPORTED_TYPE"));
    cb(null, true);
  },
});

router.get("/api/trips/:id/delegates", requireAuth(), wrap(async (req, res) => {
  const tripUuid = await resolveTripUuid(req.params.id);
  const visibleCoachIds = await getVisibleCoachIds(tripUuid, req.account);
  const delegates = await listDelegates(tripUuid);
  res.json({ delegates: visibleCoachIds ? delegates.filter((d) => visibleCoachIds.has(d.coachId)) : delegates });
}));

// "Delete all" — scoped to the selected trip; the base t-1 view
// (resolveTripUuid -> null) still means "clear everything".
router.delete("/api/trips/:id/delegates", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const { count, blocked } = await deleteAllDelegates(await resolveTripUuid(req.params.id), actorOf(req), req.account);
  res.json({ deleted: count, ...(blocked ? { blocked } : {}) });
}));

router.post("/api/trips/:id/delegates", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const body = req.body || {};
  if (!body.name || !body.name.trim()) {
    return res.status(400).json({ error: "NAME_REQUIRED", message: "A name is required." });
  }
  // A coach is required unless the delegate is explicitly Unassigned.
  if (body.status && body.status !== "UNASSIGNED" && !body.coachId) {
    return res.status(400).json({ error: "COACH_REQUIRED", message: "Please select a coach, or set status to Unassigned." });
  }
  const tripUuid = await resolveTripUuid(req.params.id);
  // Coach-scoped staff (see getVisibleCoachIds' doc) can only add onto a coach
  // they can see, else they'd create someone they can't find again.
  const visibleCoachIds = await getVisibleCoachIds(tripUuid, req.account);
  if (visibleCoachIds && (!body.coachId || !visibleCoachIds.has(body.coachId))) {
    return res.status(403).json({ error: "FORBIDDEN", message: "You can only add delegates to your own coach." });
  }
  const delegate = await createDelegate(body, tripUuid, actorOf(req), req.account?.id || null);
  res.status(201).json(delegate);
}));

router.patch("/api/delegates/:id", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const patch = req.body || {};
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });
  // Ownership + lock. A `locked` change uses canLockDelegate (creator or
  // full-access admin), independent of the CURRENT locked state — that's the
  // point of "unlock". Every OTHER field uses canModifyDelegate against the
  // EXISTING state, deliberately NOT the post-unlock state: unlock-and-edit in
  // one request is unsupported, the frontend sends two PATCHes. Don't "fix"
  // this — it avoids a patch that changes its own preconditions mid-request.
  if (patch.locked !== undefined) {
    const lockCheck = canLockDelegate(existing, req.account);
    if (!lockCheck.ok) return res.status(403).json({ error: lockCheck.code, message: lockCheck.message });
  }
  const otherFields = Object.keys(patch).filter((k) => k !== "locked");
  if (otherFields.length) {
    const modCheck = canModifyDelegate(existing, req.account);
    if (!modCheck.ok) return res.status(403).json({ error: modCheck.code, message: modCheck.message });
  }
  // Validate the RESULT of the patch, not the patch alone — changing only the
  // status on an unassigned delegate still needs a coach.
  const nextStatus = patch.status !== undefined ? patch.status : existing.status;
  const nextCoachId = patch.coachId !== undefined ? patch.coachId : existing.coachId;
  if (nextStatus !== "UNASSIGNED" && !nextCoachId) {
    return res.status(400).json({ error: "COACH_REQUIRED", message: "Please select a coach, or set status to Unassigned." });
  }
  // Coach-scoped staff can only touch a delegate on a coach they can see, and
  // can't reassign one OUT to a coach they can't. Releasing to Unassigned is
  // allowed — that's a release, not handing them to another captain's roster.
  const visibleCoachIds = await getVisibleCoachIds(existing.trip_id, req.account);
  if (visibleCoachIds) {
    if (!visibleCoachIds.has(existing.coachId)) {
      return res.status(403).json({ error: "FORBIDDEN", message: "You can only edit delegates on your own coach." });
    }
    if (nextCoachId && nextCoachId !== existing.coachId && !visibleCoachIds.has(nextCoachId)) {
      return res.status(403).json({ error: "FORBIDDEN", message: "You can only reassign delegates to your own coach." });
    }
  }
  const updated = await updateDelegate(req.params.id, patch, actorOf(req));
  if (!updated) return res.status(404).json({ error: "NOT_FOUND" });
  // Keeps checkpoint_checkins honest on a manual status correction — see
  // syncCurrentCheckpointStatus() in routes/checkpoints.js for why.
  if (patch.status !== undefined) {
    syncCurrentCheckpointStatus(req.params.id, existing.trip_id, updated.status, actorOf(req));
  }
  res.json(updated);
}));

router.delete("/api/delegates/:id", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });
  const ownerCheck = canModifyDelegate(existing, req.account);
  if (!ownerCheck.ok) return res.status(403).json({ error: ownerCheck.code, message: ownerCheck.message });
  const visibleCoachIds = await getVisibleCoachIds(existing.trip_id, req.account);
  if (visibleCoachIds && !visibleCoachIds.has(existing.coachId)) {
    return res.status(403).json({ error: "FORBIDDEN", message: "You can only delete delegates on your own coach." });
  }
  const ok = await deleteDelegate(req.params.id, actorOf(req));
  if (!ok) return res.status(404).json({ error: "NOT_FOUND" });
  if (existing?.photoPublicId) await destroyImage(existing.photoPublicId); // clean up Cloudinary too
  res.json({ deleted: true });
}));

/* ---- Delegate profile photo (Cloudinary) ----------------------------------
 * Separate from the JSON PATCH route above on purpose — see the "photoUrl"
 * column comment in data.js's createSchema(). multer parses the multipart body
 * into req.file (memory buffer, never written to disk).
 * ------------------------------------------------------------------------- */
router.post("/api/delegates/:id/photo", requirePermission("manageDelegates"), (req, res, next) => {
  photoUpload.single("photo")(req, res, (err) => {
    if (err) {
      const code = err.message === "UNSUPPORTED_TYPE" ? "UNSUPPORTED_TYPE" : "UPLOAD_FAILED";
      const message = code === "UNSUPPORTED_TYPE" ? "Please upload an image file." : "Upload too large (5MB max) or failed.";
      return res.status(400).json({ error: code, message });
    }
    next();
  });
}, wrap(async (req, res) => {
  if (!photoStorageConfigured()) {
    return res.status(503).json({ error: "PHOTO_STORAGE_NOT_CONFIGURED", message: "Photo storage isn't set up on this server yet." });
  }
  if (!req.file) return res.status(400).json({ error: "FILE_REQUIRED", message: "Please choose an image." });
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });
  const ownerCheck = canModifyDelegate(existing, req.account);
  if (!ownerCheck.ok) return res.status(403).json({ error: ownerCheck.code, message: ownerCheck.message });
  const visibleCoachIds = await getVisibleCoachIds(existing.trip_id, req.account);
  if (visibleCoachIds && !visibleCoachIds.has(existing.coachId)) {
    return res.status(403).json({ error: "FORBIDDEN", message: "You can only edit delegates on your own coach." });
  }

  const { url, publicId } = await uploadImage(req.file.buffer, "mustergo/delegates");
  const oldPublicId = await setDelegatePhoto(req.params.id, url, publicId);
  if (oldPublicId) await destroyImage(oldPublicId); // replacing a photo — clean up the old asset

  res.json({ photoUrl: url });
}));

router.delete("/api/delegates/:id/photo", requirePermission("manageDelegates"), wrap(async (req, res) => {
  const existing = await getDelegateById(req.params.id);
  if (!existing) return res.status(404).json({ error: "NOT_FOUND" });
  const ownerCheck = canModifyDelegate(existing, req.account);
  if (!ownerCheck.ok) return res.status(403).json({ error: ownerCheck.code, message: ownerCheck.message });
  const visibleCoachIds = await getVisibleCoachIds(existing.trip_id, req.account);
  if (visibleCoachIds && !visibleCoachIds.has(existing.coachId)) {
    return res.status(403).json({ error: "FORBIDDEN", message: "You can only edit delegates on your own coach." });
  }
  const oldPublicId = await clearDelegatePhoto(req.params.id);
  if (oldPublicId === null) return res.status(404).json({ error: "NOT_FOUND" });
  if (oldPublicId) await destroyImage(oldPublicId);
  res.json({ deleted: true });
}));

export default router;
