/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  README/INTEGRATION_NOTES.md for what's yours vs. what's off-limits.
 * ============================================================================= */
import { useEffect, useState, useCallback, useMemo, useRef } from "react";
import { UserPlus, Pencil, Trash2, X, ShieldCheck, AlertTriangle, Search, Eye, EyeOff, Check } from "lucide-react";
import { apiGet, apiPost, apiPatch, apiDelete, getUser, updateSession } from "../../../lib/api.js";
import { PERMISSIONS, DEFAULT_PERMISSIONS } from "../../../lib/permissions.js";
import { useLang } from "../../../lib/i18n.jsx";
// Modularization pass (2026-08-02) — see pages/desktop/accountcontrol/ for
// what used to be defined inline in this file.
import { accessLevelFor, applyAccessLevels, matchRoleTemplate, passwordProblem, PW_HINT } from "../../../lib/accountcontrol/accountHelpers.js";
import { S } from "../../../lib/accountcontrol/accountControlStyles.js";
import { PermissionCheckboxGroups } from "./PermissionControls.jsx";
import { RoleTemplatesModal } from "./RoleTemplatesModal.jsx";

/**
 * Account control (requires the "manage accounts" permission).
 *
 * Create / edit / delete accounts, each with an explicit set of permissions
 * (tickboxes). The list of permissions comes from the shared permissions.js at
 * the project root — add one entry there and the checkbox + chip appear here
 * automatically. The backend enforces every permission.
 */

// Simplified New/Edit account form (2026-07-31 — "when I add new account,
// just need 2 dropdown: Desktop web view [CRUD/Read-only], Mobile view
// [CRUD/Read-only]. Keep it simple.") — replaces the "Apply an access role"
// template picker + full per-permission checkbox tree that used to be the
// ONLY way to set a Staff account's access, with two dropdowns. The detailed
// checkbox tree still exists and is unchanged — it's what "Manage roles"
// (the named access-TEMPLATE editor) uses to build a template in the first
// place; this is just no longer how an individual ACCOUNT's access is set.
//
// Every desktopView/mobileView permission is always granted (an account can
// always SEE every page/tab) — the two dropdowns only ever control WRITE
// capability, which is what "CRUD" vs "Read-only" actually means. Action
// permissions split into which surface can exercise them: some pages
// (Trips board, Onboarding, Announcements, delegate CRUD) only exist on
// desktop; Scanner and Exceptions have a real UI on BOTH desktop and mobile,
// so either dropdown alone can grant them, and both must say Read-only to
// revoke them.
const EMPTY_FORM = {
  username: "",
  name: "",
  email: "",
  phone: "",
  password: "",
  role: "staff",
  readOnly: false,
  // Read-only/Read-only — the conservative starting point for the two
  // dropdowns; an admin explicitly grants write access per surface rather
  // than a new account starting with any create/edit/delete capability.
  perms: applyAccessLevels(DEFAULT_PERMISSIONS, "readonly", "readonly"),
};

// Exactly two roles — role is now an independent field, submitted as-is
// alongside the permission checkboxes (see backend/data.js's createAccount/
// updateAccount). Picking "Admin" here pre-fills every checkbox ticked as a
// preview, but it's cosmetic: an Admin account bypasses every permission
// check regardless of what's stored (accountPermissions() in data.js always
// returns all-true for role="admin"), so the checkboxes are hidden entirely
// once Admin is selected — see the form below. Staff's checkboxes are the
// real, enforced access grant, defaulting to EMPTY_FORM's perms (each
// permission's own `default` from permissions.js — action permissions
// mostly closed, view permissions open; see that file's group doc).
// Derived from PERMISSIONS rather than hardcoded so a new permission entry
// there is automatically included here too — nothing to update by hand.
const ROLE_PRESETS = {
  staff: DEFAULT_PERMISSIONS,
  admin: Object.fromEntries(PERMISSIONS.map((p) => [p.key, true])),
};

// Named STAFF access templates (2026-07-24) — a real SCCCI deployment has
// many staff with only a couple of real job shapes, not 50 individually
// hand-ticked permission sets. Persisted server-side now (GET/POST/PATCH/
// DELETE /api/role-templates — see "Manage roles" below), so admins can
// rename/edit/delete the 2 defaults or add their own, not just the 2
// hardcoded ones this started as. "Apply" quick-fills the checkboxes below
// (the permission set is still what's actually enforced/stored — a template
// is just a starting point, fully editable after applying); the Accounts
// list's "Access role" filter shows which template each staff account's
// CURRENT permissions exactly match, so you can see who's in charge of what
// at a glance. An account whose permissions don't exactly match any template
// (including a template account someone has since hand-edited, or a
// template that's since been deleted) shows as "Custom" — this is
// intentionally a DERIVED label (computed fresh from the permission set),
// not a stored tag, so it can never drift out of sync with what's actually
// enforced, and deleting/editing a template can never retroactively change
// what an existing account can do.
const ERR_TEXT = {
  USERNAME_TAKEN: "That username is already taken.",
  USERNAME_REQUIRED: "Username is required.",
  PASSWORD_REQUIRED: "Password is required.",
  WEAK_PASSWORD: "Password must be at least 8 characters, with a letter and a number.",
  LAST_MAIN: "You can't remove or demote the last Admin account.",
  NOT_FOUND: "That account no longer exists.",
  EMAIL_REQUIRED: "A valid email address is required.",
  EMAIL_TAKEN: "That email is already registered to another account.",
};

export default function AccountControlPage() {
  const { t, lang } = useLang();
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(EMPTY_FORM);
  const [formErr, setFormErr] = useState("");
  const [saving, setSaving] = useState(false);
  const [showPw, setShowPw] = useState(false);
  // Only dismiss if the WHOLE click gesture started on the backdrop, not
  // wherever the mouse was released after dragging to select text in a
  // username/password field.
  const downOnBackdrop = useRef(false);

  // Search / filter / sort for the accounts table.
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("ALL"); // ALL | admin | staff
  // Which named access template (fetched from the server, see roleTemplates
  // state below / "Manage roles") a STAFF account's
  // permissions currently match — "so I can see who's in charge of what" at
  // a glance, instead of reading each account's individual permission chips.
  const [templateFilter, setTemplateFilter] = useState("ALL"); // ALL | <templateId> | custom
  const [sortMode, setSortMode] = useState("username"); // username | name | role

  // Pagination for the accounts table — mirrors the All-delegates table's
  // own pattern (DashboardPage.jsx) since a real SCCCI deployment has 50+
  // staff accounts and one long unpaginated list read as messy (2026-07-24).
  const [accountPage, setAccountPage] = useState(0);
  const [accountPageSize, setAccountPageSize] = useState(10);

  // Role templates — fetched from the server (see "Manage roles" modal
  // below), not hardcoded, so admins can rename/edit/delete/add them.
  const [roleTemplates, setRoleTemplates] = useState([]);
  const [rolesModalOpen, setRolesModalOpen] = useState(false);
  const loadRoleTemplates = useCallback(async () => {
    try { setRoleTemplates((await apiGet("/role-templates")).templates || []); } catch { /* non-fatal — quick-fill/filter just show empty */ }
  }, []);

  // Batch selection — Set of account ids. Your OWN account is never
  // selectable (see visibleAccounts below and the row checkbox), so a batch
  // delete can't lock you out of your own session mid-loop.
  const [selectedIds, setSelectedIds] = useState(new Set());
  const [deletingSelected, setDeletingSelected] = useState(false);

  const me = getUser() || {};

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await apiGet("/accounts");
      setAccounts(data.accounts || []);
    } catch (e) {
      setError(e.message || "Could not load accounts.");
    } finally {
      setLoading(false);
    }
  }, []);

  // Self-registration approval queue (2026-07-24) — accounts that signed up
  // via the public /register page and are stuck "pending" until approved or
  // rejected here. Loaded alongside the main account list.
  const [pendingAccounts, setPendingAccounts] = useState([]);
  const [pendingBusyId, setPendingBusyId] = useState(null);
  // Search — real registration volume can easily get messy at 50+ pending
  // requests (2026-07-24 feedback), same fix pattern as everywhere else in
  // this app: a search box + a bounded, independently-scrollable list.
  const [pendingSearch, setPendingSearch] = useState("");
  const loadPending = useCallback(async () => {
    try { setPendingAccounts((await apiGet("/accounts/pending")).accounts || []); } catch { /* non-fatal — banner just shows empty */ }
  }, []);

  async function approvePending(id) {
    setPendingBusyId(id);
    try {
      await apiPost(`/accounts/${id}/approve`, {});
      await Promise.all([loadPending(), load()]);
    } catch (e) {
      setError(e.message || "Could not approve this account.");
    } finally {
      setPendingBusyId(null);
    }
  }

  async function rejectPending(id) {
    setPendingBusyId(id);
    try {
      await apiPost(`/accounts/${id}/reject`, {});
      await Promise.all([loadPending(), load()]);
    } catch (e) {
      setError(e.message || "Could not reject this account.");
    } finally {
      setPendingBusyId(null);
    }
  }

  const visiblePendingAccounts = useMemo(() => {
    const q = pendingSearch.trim().toLowerCase();
    if (!q) return pendingAccounts;
    return pendingAccounts.filter((a) => `${a.username} ${a.email || ""}`.toLowerCase().includes(q));
  }, [pendingAccounts, pendingSearch]);

  // Real pagination (2026-08-03 — "organise into smaller part so if got 50
  // account created it won't be messy"), same Rows-per-page + Prev/Next
  // pattern as the main Accounts table below, rather than just an internal
  // scrollbar — a genuine 50-request volume is easier to work through 5/10
  // at a time than by scrolling one long bounded list.
  const [pendingPage, setPendingPage] = useState(0);
  const [pendingPageSize, setPendingPageSize] = useState(5);
  const pendingPageCount = Math.max(1, Math.ceil(visiblePendingAccounts.length / pendingPageSize));
  const clampedPendingPage = Math.min(pendingPage, pendingPageCount - 1);
  useEffect(() => { if (clampedPendingPage !== pendingPage) setPendingPage(clampedPendingPage); }, [clampedPendingPage, pendingPage]);
  useEffect(() => { setPendingPage(0); }, [pendingSearch, pendingPageSize, pendingAccounts.length]);
  const pendingShown = visiblePendingAccounts.slice(clampedPendingPage * pendingPageSize, (clampedPendingPage + 1) * pendingPageSize);

  // "Approve all"/"Reject all" (2026-07-24, requested while clearing 50 demo
  // pending accounts by hand) — a single bulk request instead of looping the
  // per-account endpoint. Asks for confirmation first since acting on every
  // pending account at once (especially Approve all) isn't easily undone.
  const [bulkPendingBusy, setBulkPendingBusy] = useState(false);
  const [bulkPendingConfirm, setBulkPendingConfirm] = useState(null); // "approve" | "reject" | null

  async function runBulkPending(action) {
    setBulkPendingConfirm(null);
    setBulkPendingBusy(true);
    try {
      await apiPost(`/accounts/pending/${action}-all`, {});
      await Promise.all([loadPending(), load()]);
    } catch (e) {
      setError(e.message || `Could not ${action} all pending accounts.`);
    } finally {
      setBulkPendingBusy(false);
    }
  }

  useEffect(() => {
    load();
    loadRoleTemplates();
    loadPending();
  }, [load, loadRoleTemplates, loadPending]);

  // Search + role filter + sort, applied in that order. Search matches
  // username or display name (case-insensitive substring).
  const visibleAccounts = useMemo(() => {
    const q = search.trim().toLowerCase();
    let list = accounts.filter((a) => {
      const role = a.role === "admin" ? "admin" : "staff";
      if (roleFilter !== "ALL" && role !== roleFilter) return false;
      if (templateFilter !== "ALL") {
        if (role === "admin") return false; // templates are a staff-only concept
        const matched = matchRoleTemplate(a.permissions, roleTemplates) || "custom";
        if (matched !== templateFilter) return false;
      }
      if (q) {
        const hay = `${a.username || ""} ${a.name || ""}`.toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
    const byUsername = (a, b) => (a.username || "").localeCompare(b.username || "");
    list = [...list].sort((a, b) => {
      if (sortMode === "name") return (a.name || "").localeCompare(b.name || "") || byUsername(a, b);
      if (sortMode === "role") return (a.role || "").localeCompare(b.role || "") || byUsername(a, b);
      return byUsername(a, b); // username
    });
    return list;
  }, [accounts, search, roleFilter, templateFilter, sortMode, roleTemplates]);

  const pageCount = Math.max(1, Math.ceil(visibleAccounts.length / accountPageSize));
  // Search/filter/sort/page-size changing can leave accountPage pointing
  // past the new (smaller) result set — clamp back into range rather than
  // showing an empty page.
  const clampedAccountPage = Math.min(accountPage, pageCount - 1);
  useEffect(() => { if (clampedAccountPage !== accountPage) setAccountPage(clampedAccountPage); }, [clampedAccountPage, accountPage]);
  // Any filter/sort change resets to page 1 — otherwise you could end up on
  // page 4 of a filter that now only has 1 page of results.
  useEffect(() => { setAccountPage(0); }, [search, roleFilter, templateFilter, sortMode, accountPageSize]);
  const accountsShown = visibleAccounts.slice(clampedAccountPage * accountPageSize, (clampedAccountPage + 1) * accountPageSize);

  const clearAccountFilters = () => { setSearch(""); setRoleFilter("ALL"); setTemplateFilter("ALL"); };
  const accountFiltersActive = search.trim() !== "" || roleFilter !== "ALL" || templateFilter !== "ALL";

  const roleCounts = useMemo(() => {
    let admin = 0, staff = 0;
    for (const a of accounts) { if (a.role === "admin") admin++; else staff++; }
    return { admin, staff };
  }, [accounts]);

  const templateCounts = useMemo(() => {
    const counts = { custom: 0 };
    for (const tpl of roleTemplates) counts[tpl.id] = 0;
    for (const a of accounts) {
      if (a.role === "admin") continue;
      const key = matchRoleTemplate(a.permissions, roleTemplates) || "custom";
      counts[key] = (counts[key] || 0) + 1;
    }
    return counts;
  }, [accounts, roleTemplates]);

  // Every visible account EXCEPT your own — your own account is never
  // selectable for batch delete (see the row checkbox below).
  // Scoped to the current PAGE, not every filtered result — matches the
  // All-delegates table's own "select all" (2026-07-24 pagination pass), so
  // ticking the header checkbox never silently selects rows you can't see.
  const selectableVisible = useMemo(() => accountsShown.filter((a) => a.username !== me.username), [accountsShown, me.username]);
  const allSelectableChecked = selectableVisible.length > 0 && selectableVisible.every((a) => selectedIds.has(a.id));

  function toggleSelected(id) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  }

  function toggleSelectAll() {
    setSelectedIds((prev) => {
      if (allSelectableChecked) return new Set();
      return new Set(selectableVisible.map((a) => a.id));
    });
  }

  async function deleteSelected() {
    const count = selectedIds.size;
    if (count === 0) return;
    const msg = lang === "zh"
      ? `确定删除选中的 ${count} 个账户？此操作无法撤销。`
      : `Delete ${count} selected account${count === 1 ? "" : "s"}? This cannot be undone.`;
    if (!window.confirm(msg)) return;

    setDeletingSelected(true);
    setError("");
    const ids = [...selectedIds];
    const results = await Promise.allSettled(ids.map((id) => apiDelete(`/accounts/${id}`)));
    const failed = results.filter((r) => r.status === "rejected");
    if (failed.length > 0) {
      // Most likely cause: the "last admin" guard blocked one of them —
      // show the first failure's message rather than a generic one.
      setError(mapError(failed[0].reason, "LAST_MAIN"));
    }
    setSelectedIds(new Set());
    setDeletingSelected(false);
    await load();
  }

  // Deletes every account EXCEPT your own (never itself deletable — same
  // rule as the row checkboxes). The backend's "last admin" guard still
  // blocks removing the only remaining admin, so at minimum your own account
  // survives this.
  async function deleteAllAccounts() {
    const targets = accounts.filter((a) => a.username !== me.username);
    if (targets.length === 0) return;
    const msg = lang === "zh"
      ? `确定删除除您以外的全部 ${targets.length} 个账户？此操作无法撤销。`
      : `Delete ALL ${targets.length} other account${targets.length === 1 ? "" : "s"} (everyone except you)? This cannot be undone.`;
    if (!window.confirm(msg)) return;

    setDeletingSelected(true);
    setError("");
    const results = await Promise.allSettled(targets.map((a) => apiDelete(`/accounts/${a.id}`)));
    const failed = results.filter((r) => r.status === "rejected");
    if (failed.length > 0) {
      setError(mapError(failed[0].reason, "LAST_MAIN"));
    }
    setSelectedIds(new Set());
    setDeletingSelected(false);
    await load();
  }

  function openCreate() {
    setEditingId(null);
    setForm({ ...EMPTY_FORM, perms: { ...EMPTY_FORM.perms } });
    setFormErr("");
    setModalOpen(true);
  }

  function openEdit(a) {
    setEditingId(a.id);
    const perms = Object.fromEntries(PERMISSIONS.map((p) => [p.key, !!a.permissions?.[p.key]]));
    setForm({
      username: a.username,
      name: a.name || "",
      email: a.email || "",
      phone: a.phone || "",
      password: "",
      perms,
      role: a.role === "admin" ? "admin" : "staff",
      readOnly: !!a.readOnly,
    });
    setFormErr("");
    setModalOpen(true);
  }

  function selectRole(role) {
    setForm((f) => ({
      ...f,
      role,
      readOnly: role === "admin" ? f.readOnly : false,
      // Switching TO staff always lands on the clean Read-only/Read-only
      // starting point (see applyAccessLevels above) rather than
      // ROLE_PRESETS' raw per-key defaults, so the two dropdowns always show
      // a predictable state right after a role switch.
      perms: role === "admin" ? { ...f.perms, ...ROLE_PRESETS.admin } : applyAccessLevels(f.perms, "readonly", "readonly"),
    }));
  }

  function toggleReadOnly() {
    setForm((f) => ({ ...f, readOnly: !f.readOnly }));
  }

  // The two access dropdowns (2026-07-31 — see applyAccessLevels above).
  function setDesktopAccess(level) {
    setForm((f) => ({ ...f, perms: applyAccessLevels(f.perms, level, accessLevelFor(f.perms, "mobile")) }));
  }
  function setMobileAccess(level) {
    setForm((f) => ({ ...f, perms: applyAccessLevels(f.perms, accessLevelFor(f.perms, "desktop"), level) }));
  }

  // "Access role" quick-fill dropdown (2026-07-31 — "add back the role to
  // the permission") — re-added as a third dropdown, ABOVE the two simple
  // ones: applies a named template's full, fine-grained permission set in
  // one pick, same as before this was simplified, just a <select> instead
  // of a row of buttons. The two Desktop/Mobile dropdowns below still work
  // afterward — accessLevelFor() reads whatever ends up in form.perms
  // regardless of whether a template or a dropdown set it, and re-picking
  // either dropdown still fully overrides the template's fine print for
  // that surface's actions.
  function applyTemplate(templateId) {
    if (!templateId) return;
    const tpl = roleTemplates.find((r) => r.id === templateId);
    if (!tpl) return;
    setForm((f) => ({ ...f, perms: { ...f.perms, ...tpl.permissions } }));
  }

  function mapError(e, fallbackCode) {
    // Prefer the backend's error code (now carried on the Error), then fall back
    // to matching the message text or a 409 conflict.
    const code =
      (e.code && ERR_TEXT[e.code] ? e.code : "") ||
      Object.keys(ERR_TEXT).find((k) => String(e.message).includes(k)) ||
      (e.status === 409 || String(e.message).includes("409") ? fallbackCode : "");
    // For weak passwords the backend sends a specific message — show it verbatim.
    if (e.code === "WEAK_PASSWORD" && e.message) return e.message;
    return ERR_TEXT[code] || "Something went wrong. Please try again.";
  }

  async function save() {
    setFormErr("");
    if (!form.username.trim()) return setFormErr(ERR_TEXT.USERNAME_REQUIRED);
    if (!editingId && !form.password) return setFormErr(ERR_TEXT.PASSWORD_REQUIRED);
    // Email is compulsory for a brand-new account (2026-07-24 — "need email
    // for each staff and admin now"), but NOT force-required when editing an
    // existing pre-2026-07-24 account that never had one on file — see the
    // payload note below on why it's simply omitted rather than sent blank.
    if (!editingId && !form.email.trim()) return setFormErr(ERR_TEXT.EMAIL_REQUIRED);
    // Enforce the password rule when creating, or when editing AND a new
    // password was typed (blank on edit = keep the current one).
    if (form.password) {
      const pw = passwordProblem(form.password);
      if (pw) return setFormErr(pw);
    }

    setSaving(true);
    const payload = {
      username: form.username.trim(),
      name: form.name.trim(),
      role: form.role,
      readOnly: form.role === "admin" && form.readOnly,
      permissions: form.perms,
    };
    if (form.password) payload.password = form.password; // blank on edit = keep current
    // Only sent if actually filled in — an edit that leaves this blank on an
    // account with no email yet should still be able to save (e.g. just
    // changing a permission), not get blocked into backfilling an email
    // that account never had. A brand-new account already required it above.
    if (form.email.trim()) payload.email = form.email.trim();
    if (form.phone.trim()) payload.phone = form.phone.trim();

    try {
      if (editingId) {
        const resp = await apiPatch(`/accounts/${editingId}`, payload);
        // If you edited your OWN account, refresh the saved session (new token +
        // name/permissions) and reload so everything (including the sidebar and
        // the auth token) reflects the change without a re-login.
        if (resp?.self) {
          updateSession({
            token: resp.token,
            user: {
              username: resp.account.username,
              staffId: resp.account.username,
              name: resp.account.name,
              role: resp.account.role,
              permissions: resp.account.permissions,
            },
          });
          window.location.reload();
          return;
        }
      } else {
        await apiPost("/accounts", payload);
      }
      setModalOpen(false);
      await load();
    } catch (e) {
      setFormErr(mapError(e, "USERNAME_TAKEN"));
    } finally {
      setSaving(false);
    }
  }

  async function remove(a) {
    const msg = lang === "zh"
      ? `确定删除账户 "${a.username}"？此操作无法撤销。`
      : `Delete account "${a.username}"? This cannot be undone.`;
    if (!window.confirm(msg)) return;
    setError("");
    try {
      await apiDelete(`/accounts/${a.id}`);
      await load();
    } catch (e) {
      setError(mapError(e, "LAST_MAIN"));
    }
  }

  return (
    <div className="page">
      <div className="row between" style={{ alignItems: "flex-start", flexWrap: "wrap", gap: 16 }}>
        <div>
          <div className="page-eyebrow">{t("Administration")}</div>
          <h1 className="page-title">{t("Account control")}</h1>
          <p className="page-sub">{t("Create accounts and choose exactly what each one can do.")}</p>
        </div>
        <div className="row" style={{ gap: 10 }}>
          {selectedIds.size > 0 && (
            <button
              className="btn btn-ghost"
              style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }}
              onClick={deleteSelected}
              disabled={deletingSelected}
            >
              <Trash2 size={16} /> {deletingSelected ? t("Deleting…") : `${t("Delete selected")} (${selectedIds.size})`}
            </button>
          )}
          {accounts.length > 1 && (
            <button
              className="btn btn-ghost"
              style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }}
              onClick={deleteAllAccounts}
              disabled={deletingSelected}
            >
              <Trash2 size={16} /> {t("Delete all")}
            </button>
          )}
          <button className="btn btn-primary" onClick={openCreate}>
            <UserPlus size={16} /> {t("New account")}
          </button>
        </div>
      </div>

      {error && (
        <div className="card" style={{ marginTop: 20, padding: 14, borderColor: "var(--st-missing)", background: "var(--st-missing-bg)" }}>
          <div className="row" style={{ gap: 8, color: "var(--st-missing)", fontWeight: 600, fontSize: 14 }}>
            <AlertTriangle size={16} /> {t(error)}
          </div>
        </div>
      )}

      {/* ---- Pending approval (2026-07-24) ---------------------------------
       * "add a ui for admin to accept or reject the new account creation on
       * account control page." Self-registered accounts (see RegisterPage.jsx)
       * sit here, unable to sign in, until an admin approves or rejects them.
       * Only rendered when there's actually something to review. */}
      {pendingAccounts.length > 0 && (
        <div className="card" style={{ marginTop: 20, padding: 20, borderColor: "var(--st-review)", background: "var(--st-review-bg)" }}>
          <div className="row between" style={{ marginBottom: 14, flexWrap: "wrap", gap: 10 }}>
            <div className="row" style={{ gap: 8 }}>
              <UserPlus size={18} color="var(--st-review)" />
              <h2 style={{ fontSize: 16 }}>{t("Pending approval")}</h2>
              <span className="badge badge-review" style={{ padding: "2px 8px" }}>{pendingAccounts.length}</span>
            </div>
            <div className="row" style={{ gap: 8, flexWrap: "wrap", alignItems: "center" }}>
              {/* Bulk actions (2026-07-24) — a single confirm-gated request
                  instead of clicking Approve/Reject one-by-one down a long
                  list. Reject all is the safer of the two (rejected accounts
                  just can't log in — nothing is deleted), Approve all is
                  more consequential since it lets every one of them sign in
                  immediately, so both go through the same confirm step. */}
              <button
                className="btn btn-ghost"
                style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }}
                onClick={() => setBulkPendingConfirm("reject")}
                disabled={bulkPendingBusy}
              >
                {t("Reject all")}
              </button>
              <button
                className="btn btn-ghost"
                onClick={() => setBulkPendingConfirm("approve")}
                disabled={bulkPendingBusy}
              >
                {t("Approve all")}
              </button>
              {/* Search — real registration volume gets messy fast otherwise
                  (2026-07-24 feedback, live-demoed at 50 pending requests). */}
              {pendingAccounts.length > 6 && (
                <div style={{ position: "relative", maxWidth: 240, flex: "1 1 200px" }}>
                  <Search size={15} style={{ position: "absolute", left: 10, top: "50%", transform: "translateY(-50%)", color: "var(--ink-3)" }} />
                  <input
                    className="input"
                    style={{ paddingLeft: 32, background: "var(--surface)" }}
                    placeholder={t("Search name or email…")}
                    value={pendingSearch}
                    onChange={(e) => setPendingSearch(e.target.value)}
                  />
                </div>
              )}
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {visiblePendingAccounts.length === 0 && (
              <div className="muted" style={{ fontSize: 13, textAlign: "center", padding: "12px 0" }}>
                {t("No pending requests match your search.")}
              </div>
            )}
            {pendingShown.map((a) => (
              <div key={a.id} className="row between" style={{ padding: "10px 12px", background: "var(--surface)", border: "1px solid var(--line)", borderRadius: "var(--r-sm)", flexWrap: "wrap", gap: 10 }}>
                <div style={{ minWidth: 0 }}>
                  <div className="row" style={{ gap: 8 }}>
                    <span className="mono" style={{ fontWeight: 600 }}>{a.username}</span>
                  </div>
                  <div className="muted" style={{ fontSize: 12.5, marginTop: 2 }}>{a.email || t("No email on file")}</div>
                </div>
                <div className="row" style={{ gap: 8, flexShrink: 0 }}>
                  <button
                    className="btn btn-ghost"
                    style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }}
                    onClick={() => rejectPending(a.id)}
                    disabled={pendingBusyId === a.id}
                  >
                    {t("Reject")}
                  </button>
                  <button
                    className="btn btn-primary"
                    onClick={() => approvePending(a.id)}
                    disabled={pendingBusyId === a.id}
                  >
                    {pendingBusyId === a.id ? t("Saving…") : t("Approve")}
                  </button>
                </div>
              </div>
            ))}
          </div>
          {visiblePendingAccounts.length > 0 && (
            <div className="row between" style={{ marginTop: 14, paddingTop: 12, borderTop: "1px solid var(--line)", flexWrap: "wrap", gap: 10 }}>
              <span className="muted" style={{ fontSize: 12.5 }}>
                {t("Showing")} {clampedPendingPage * pendingPageSize + 1}–{Math.min((clampedPendingPage + 1) * pendingPageSize, visiblePendingAccounts.length)} {t("of")} {visiblePendingAccounts.length}
              </span>
              <div className="row" style={{ gap: 8, alignItems: "center" }}>
                <span className="muted" style={{ fontSize: 12.5 }}>{t("Rows per page")}</span>
                <select className="select" style={{ width: 76, padding: "4px 8px" }} value={pendingPageSize}
                  onChange={(e) => setPendingPageSize(Number(e.target.value))}>
                  {[5, 10, 25, 50].map((n) => <option key={n} value={n}>{n}</option>)}
                </select>
              </div>
              <div className="row" style={{ gap: 8, alignItems: "center" }}>
                <button className="btn btn-ghost" style={{ padding: "4px 10px" }} disabled={clampedPendingPage === 0}
                  onClick={() => setPendingPage((p) => Math.max(0, p - 1))}>
                  {t("Prev")}
                </button>
                <span className="muted" style={{ fontSize: 12.5 }}>{t("Page")} {clampedPendingPage + 1} {t("of")} {pendingPageCount}</span>
                <button className="btn btn-ghost" style={{ padding: "4px 10px" }} disabled={clampedPendingPage >= pendingPageCount - 1}
                  onClick={() => setPendingPage((p) => Math.min(pendingPageCount - 1, p + 1))}>
                  {t("Next")}
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {bulkPendingConfirm && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(16,24,40,0.45)", display: "grid", placeItems: "center", padding: 20, zIndex: 60 }}>
          <div className="card" style={{ width: "min(400px, 100%)", padding: 22 }}>
            <h2 style={{ fontSize: 16, marginBottom: 8 }}>
              {bulkPendingConfirm === "approve" ? t("Approve all pending accounts?") : t("Reject all pending accounts?")}
            </h2>
            <p className="muted" style={{ fontSize: 13, marginBottom: 18 }}>
              {bulkPendingConfirm === "approve"
                ? t("Every pending account below will be approved and able to sign in immediately.")
                : t("Every pending account below will be rejected. They'll stay in the system but won't be able to sign in.")}
            </p>
            <div className="row" style={{ gap: 10, justifyContent: "flex-end" }}>
              <button className="btn btn-ghost" onClick={() => setBulkPendingConfirm(null)} disabled={bulkPendingBusy}>{t("Cancel")}</button>
              <button
                className={bulkPendingConfirm === "reject" ? "btn btn-ghost" : "btn btn-primary"}
                style={bulkPendingConfirm === "reject" ? { color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" } : undefined}
                onClick={() => runBulkPending(bulkPendingConfirm)}
                disabled={bulkPendingBusy}
              >
                {bulkPendingBusy ? t("Saving…") : (bulkPendingConfirm === "approve" ? t("Approve all") : t("Reject all"))}
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="card" style={{ marginTop: 20, overflow: "hidden" }}>
        <div className="row" style={{ padding: "16px 20px", borderBottom: "1px solid var(--line)", gap: 8 }}>
          <ShieldCheck size={18} color="var(--ink-3)" />
          <h2 style={{ fontSize: 16 }}>{t("Accounts")}</h2>
          <span className="muted" style={{ fontSize: 13, marginLeft: "auto" }}>{accounts.length} {t("total")}</span>
        </div>

        {accounts.length > 0 && (
          <>
            {/* Admin/Staff tabs — a real SCCCI deployment has far more staff
                than admins, so splitting by role (instead of one long mixed
                list behind a filter dropdown) makes each group easier to
                scan (2026-07-24). */}
            <div className="row" style={{ gap: 8, padding: "14px 20px 0" }}>
              {[
                ["ALL", t("All"), accounts.length],
                ["admin", t("Admin"), roleCounts.admin],
                ["staff", t("Staff"), roleCounts.staff],
              ].map(([k, label, count]) => (
                <button key={k} onClick={() => { setRoleFilter(k); if (k === "admin") setTemplateFilter("ALL"); }} className="btn"
                  style={{
                    background: roleFilter === k ? "var(--scc-red-tint)" : "transparent",
                    color: roleFilter === k ? "var(--scc-red)" : "var(--ink-2)",
                    border: `1px solid ${roleFilter === k ? "var(--scc-red-tint-2)" : "var(--line)"}`,
                    fontWeight: 600,
                  }}>
                  {label} <span className="muted" style={{ marginLeft: 4 }}>{count}</span>
                </button>
              ))}
            </div>

            <div className="row" style={{ gap: 10, padding: "12px 20px", borderBottom: "1px solid var(--line)", flexWrap: "wrap" }}>
              <div style={{ position: "relative", maxWidth: 240, flex: "1 1 180px" }}>
                <Search size={15} style={{ position: "absolute", left: 10, top: "50%", transform: "translateY(-50%)", color: "var(--ink-3)" }} />
                <input
                  className="input"
                  style={{ paddingLeft: 32 }}
                  placeholder={t("Search accounts…")}
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>
              {roleFilter !== "admin" && (
                // Staff-only concept — which named access template (fetched
                // from the server, see "Manage roles") each staff account's
                // permissions currently match, so you can see "who's in
                // charge of what" at a glance instead of reading individual
                // permission chips (2026-07-24).
                <select className="select" style={{ maxWidth: 210 }} value={templateFilter} onChange={(e) => setTemplateFilter(e.target.value)}>
                  <option value="ALL">{t("All access roles")}</option>
                  {roleTemplates.map((tpl) => (
                    <option key={tpl.id} value={tpl.id}>{tpl.label} ({templateCounts[tpl.id] || 0})</option>
                  ))}
                  <option value="custom">{t("Custom")} ({templateCounts.custom})</option>
                </select>
              )}
              <select className="select" style={{ maxWidth: 190 }} value={sortMode} onChange={(e) => setSortMode(e.target.value)}>
                <option value="username">{t("Sort: Username")}</option>
                <option value="name">{t("Sort: Name")}</option>
                <option value="role">{t("Sort: Role")}</option>
              </select>
              {accountFiltersActive && (
                <button className="btn btn-ghost" style={{ padding: "6px 10px", fontSize: 12.5 }} onClick={clearAccountFilters}>
                  {t("Clear filters")}
                </button>
              )}
              {/* Moved here from inside the account modal (2026-07-24) — managing
                  the list of roles is a standalone admin task, not something that
                  only makes sense while creating/editing one particular account,
                  and it belongs next to the filter it directly controls. */}
              <button type="button" className="btn btn-ghost" style={{ marginLeft: "auto" }} onClick={() => setRolesModalOpen(true)}>
                <ShieldCheck size={15} /> {t("Manage roles")}
              </button>
            </div>
          </>
        )}

        {loading ? (
          <div className="muted" style={{ padding: 24, fontSize: 14 }}>{t("Loading…")}</div>
        ) : accounts.length === 0 ? (
          <div className="muted" style={{ padding: 24, fontSize: 14 }}>{t("No accounts yet.")}</div>
        ) : (
          <>
          {/* Fixed-height scroll area with a sticky header — mirrors the
              All-delegates table (2026-07-24). Without this, 50+ staff
              accounts rendered as one long unpaginated list, which was the
              "too messy" complaint. overflowX added (2026-07-24, mobile
              responsiveness pass) so this many-column table scrolls
              horizontally on a narrow screen instead of clipping/squishing
              columns — the sidebar/page shell already collapses correctly
              below 1024px, but the table itself had no horizontal-scroll
              safety net. */}
          <div style={{ maxHeight: 640, overflowY: "auto", overflowX: "auto" }}>
          <table className="table" style={{ minWidth: 640 }}>
            <thead style={{ position: "sticky", top: 0, zIndex: 1, background: "var(--surface)" }}>
              <tr>
                <th style={{ width: 36 }}>
                  <input
                    type="checkbox"
                    checked={allSelectableChecked}
                    onChange={toggleSelectAll}
                    disabled={selectableVisible.length === 0}
                    aria-label={t("Select all")}
                  />
                </th>
                <th>{t("Username")}</th><th>{t("Name")}</th><th>{t("Role")}</th><th>{t("Access")}</th><th>{t("Status")}</th><th style={{ width: 90 }} />
              </tr>
            </thead>
            <tbody>
              {visibleAccounts.length === 0 && (
                <tr>
                  <td colSpan={7} className="muted" style={{ padding: 24, fontSize: 14, textAlign: "center" }}>
                    {t("No accounts match your filters.")}
                  </td>
                </tr>
              )}
              {accountsShown.map((a) => {
                const isMe = a.username === me.username;
                const isAdmin = a.role === "admin";
                // Access column shows the named role template this account's
                // permissions currently match (same computation as the
                // Access-role filter above) instead of raw permission chips —
                // one clear label ("Onsite Headcount Staff") reads faster
                // than a wrapped row of 7+ near-identical chips, and stays
                // consistent with how the filter groups accounts (2026-07-24).
                const matchedTplId = isAdmin ? null : matchRoleTemplate(a.permissions, roleTemplates);
                const matchedTpl = matchedTplId ? roleTemplates.find((tp) => tp.id === matchedTplId) : null;
                return (
                  <tr key={a.id}>
                    <td>
                      <input
                        type="checkbox"
                        checked={selectedIds.has(a.id)}
                        onChange={() => toggleSelected(a.id)}
                        disabled={isMe}
                        title={isMe ? t("You can't select your own account for batch delete.") : undefined}
                        aria-label={`${t("Select")} ${a.username}`}
                      />
                    </td>
                    <td>
                      <div className="row" style={{ gap: 10 }}>
                        {a.photoUrl ? (
                          <img className="avatar" src={a.photoUrl} alt="" style={{ objectFit: "cover" }} />
                        ) : (
                          <span className="avatar" style={{ background: "var(--st-neutral-bg)", color: "var(--ink-2)" }}>
                            {a.username.slice(0, 2).toUpperCase()}
                          </span>
                        )}
                        <div style={{ minWidth: 0 }}>
                          <div className="row" style={{ gap: 6 }}>
                            <span className="mono" style={{ fontWeight: 500 }}>{a.username}</span>
                            {isMe && <span className="badge badge-present" style={{ padding: "2px 8px" }}>{t("You")}</span>}
                          </div>
                          {/* Email (2026-07-24) — added going forward for every
                              new account; pre-existing accounts predate this
                              field and simply show nothing here. */}
                          {a.email && (
                            <div className="muted" style={{ fontSize: 11.5, marginTop: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                              {a.email}
                            </div>
                          )}
                        </div>
                      </div>
                    </td>
                    <td>{a.name || "—"}</td>
                    <td>
                      <span className={"badge " + (isAdmin ? "badge-missing" : "badge-neutral")} style={{ padding: "2px 8px" }}>
                        {isAdmin ? t("Admin") : t("Staff")}
                      </span>
                    </td>
                    <td>
                      {isAdmin ? (
                        a.readOnly
                          ? <span className="badge badge-normal">{t("Read-only")}</span>
                          : <span className="badge badge-missing">{t("Full access")}</span>
                      ) : matchedTpl ? (
                        <span className="badge badge-normal" style={{ padding: "2px 8px" }}>{matchedTpl.label}</span>
                      ) : (
                        <span className="badge badge-neutral">{t("Custom")}</span>
                      )}
                    </td>
                    {/* Status (2026-08-03 — "i reject this account why is it
                        still here?"): rejecting/approving updates the row's
                        status in place rather than deleting it (see
                        rejectAccount()'s own comment — kept for an audit
                        trail; a real delete is the separate trash icon), but
                        the table had no way to SEE that, so a rejected row
                        looked identical to a normal active one. Blank for
                        the default "approved" case to avoid cluttering every
                        row with a badge that's true 95%+ of the time. */}
                    <td>
                      {a.status === "rejected" ? (
                        <span className="badge badge-missing" style={{ padding: "2px 8px" }}>{t("Rejected")}</span>
                      ) : a.status === "pending" ? (
                        <span className="badge badge-review" style={{ padding: "2px 8px" }}>{t("Pending")}</span>
                      ) : null}
                    </td>
                    <td>
                      <div className="row" style={{ gap: 6 }}>
                        {/* Undo a rejection (2026-08-04 — "if i rejected this
                            account. is there a way for me to reapprove...?").
                            A rejected row was a dead end in the UI: the only
                            Approve button lives in the "Pending approval"
                            card, which lists status='pending' ONLY, so a
                            rejection (often just a misclick) could only be
                            resolved by hard-deleting the account. The backend
                            already supported this — approveAccount() has no
                            pending-only guard, it flips ANY id to 'approved' —
                            so this is purely the missing UI path. Deliberately
                            NOT auto-deleting rejected rows instead: keeping
                            the row is what blocks that person from simply
                            re-registering the same username/email straight
                            back into the pending queue (see registerAccount()'s
                            USERNAME_TAKEN/EMAIL_TAKEN checks). */}
                        {a.status === "rejected" && (
                          <button
                            onClick={() => approvePending(a.id)}
                            disabled={pendingBusyId === a.id}
                            aria-label={`${t("Re-approve")} ${a.username}`}
                            title={t("Re-approve — let this account sign in again")}
                            style={{ ...S.iconBtn, color: "var(--st-present)" }}
                          >
                            <Check size={16} />
                          </button>
                        )}
                        <button onClick={() => openEdit(a)} aria-label={`${t("Edit")} ${a.username}`} style={S.iconBtn}>
                          <Pencil size={16} />
                        </button>
                        <button onClick={() => remove(a)} aria-label={`${t("Delete")} ${a.username}`} style={{ ...S.iconBtn, color: "var(--st-missing)" }}>
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          </div>
          {visibleAccounts.length > 0 && (
            <div className="row between" style={{ padding: "12px 20px", borderTop: "1px solid var(--line)", flexWrap: "wrap", gap: 10 }}>
              <span className="muted" style={{ fontSize: 12.5 }}>
                {t("Showing")} {clampedAccountPage * accountPageSize + 1}–{Math.min((clampedAccountPage + 1) * accountPageSize, visibleAccounts.length)} {t("of")} {visibleAccounts.length}
              </span>
              <div className="row" style={{ gap: 8, alignItems: "center" }}>
                <span className="muted" style={{ fontSize: 12.5 }}>{t("Rows per page")}</span>
                <select className="select" style={{ width: 76, padding: "4px 8px" }} value={accountPageSize}
                  onChange={(e) => setAccountPageSize(Number(e.target.value))}>
                  {[10, 25, 50, 100].map((n) => <option key={n} value={n}>{n}</option>)}
                </select>
              </div>
              <div className="row" style={{ gap: 8, alignItems: "center" }}>
                <button className="btn btn-ghost" style={{ padding: "4px 10px" }} disabled={clampedAccountPage === 0}
                  onClick={() => setAccountPage((p) => Math.max(0, p - 1))}>
                  {t("Prev")}
                </button>
                <span className="muted" style={{ fontSize: 12.5 }}>{t("Page")} {clampedAccountPage + 1} {t("of")} {pageCount}</span>
                <button className="btn btn-ghost" style={{ padding: "4px 10px" }} disabled={clampedAccountPage >= pageCount - 1}
                  onClick={() => setAccountPage((p) => Math.min(pageCount - 1, p + 1))}>
                  {t("Next")}
                </button>
              </div>
            </div>
          )}
          </>
        )}
      </div>

      {/* Create / edit modal */}
      {modalOpen && (
        <div style={S.overlay}
          onMouseDown={(e) => { downOnBackdrop.current = e.target === e.currentTarget; }}
          onClick={(e) => { if (!saving && downOnBackdrop.current && e.target === e.currentTarget) setModalOpen(false); }}>
          <div className="card" style={S.modal} onClick={(e) => e.stopPropagation()}>
            <div className="row between" style={{ marginBottom: 18 }}>
              <h2 style={{ fontSize: 18 }}>{editingId ? t("Edit account") : t("New account")}</h2>
              <button onClick={() => setModalOpen(false)} style={S.iconBtn} aria-label={t("Close")}><X size={18} /></button>
            </div>

            <label className="field-label">{t("Username")}</label>
            <input className="input mono" autoFocus value={form.username}
              placeholder={t("e.g. staff_123")}
              onChange={(e) => setForm({ ...form, username: e.target.value })} />

            <label className="field-label" style={{ marginTop: 14 }}>{t("Name")} <span className="muted">({t("display only")})</span></label>
            <input className="input" value={form.name}
              placeholder={t("e.g. John Tan")}
              onChange={(e) => setForm({ ...form, name: e.target.value })} />

            {/* Compulsory for a brand-new account; optional when editing one
                that predates this field (2026-07-24). */}
            <label className="field-label" style={{ marginTop: 14 }}>
              {t("Email")} {!editingId && <span style={{ color: "var(--scc-red)" }}>*</span>}
            </label>
            <input className="input" type="email" value={form.email}
              placeholder={t("e.g. john.tan@sccci.org.sg")}
              onChange={(e) => setForm({ ...form, email: e.target.value })} />

            <label className="field-label" style={{ marginTop: 14 }}>
              {t("Contact number")} <span className="muted">({t("optional")})</span>
            </label>
            <input className="input" type="tel" value={form.phone}
              placeholder={t("e.g. +65 9123 4567")}
              onChange={(e) => setForm({ ...form, phone: e.target.value })} />

            <label className="field-label" style={{ marginTop: 14 }}>
              {t("Password")} {editingId && <span className="muted">({t("leave blank to keep current")})</span>}
            </label>
            <div style={{ position: "relative" }}>
              <input className="input" type={showPw ? "text" : "password"} value={form.password}
                placeholder={editingId ? "••••••••" : t("Set a password")}
                style={{ paddingRight: 42 }}
                onChange={(e) => setForm({ ...form, password: e.target.value })} />
              <button
                type="button"
                onClick={() => setShowPw((v) => !v)}
                aria-label={showPw ? t("Hide password") : t("Show password")}
                style={{ position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", background: "none", border: "none", color: "var(--scc-red)", display: "flex" }}
              >
                {showPw ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
            {(!editingId || form.password) && (
              <p className="muted" style={{ fontSize: 12, marginTop: 6,
                color: form.password && passwordProblem(form.password) ? "var(--st-missing)" : undefined }}>
                {t(PW_HINT)}
              </p>
            )}

            <label className="field-label" style={{ marginTop: 18 }}>{t("Role")}</label>
            <div className="row" style={{ gap: 8 }}>
              {["staff", "admin"].map((r) => (
                <button
                  key={r}
                  type="button"
                  className={"btn " + (form.role === r ? "btn-primary" : "btn-ghost")}
                  style={{ flex: 1 }}
                  onClick={() => selectRole(r)}
                >
                  {t(r === "staff" ? "Staff" : "Admin")}
                </button>
              ))}
            </div>
            <p className="muted" style={{ fontSize: 12, marginTop: 6 }}>
              {form.role === "admin"
                ? t("Admins bypass every check below — full access to every tab and feature.")
                : t("Staff are limited to exactly what's ticked below.")}
            </p>

            {form.role === "admin" && (
              <label className="row" style={{ gap: 8, marginTop: 10, alignItems: "flex-start", cursor: "pointer" }}>
                <input type="checkbox" checked={form.readOnly} onChange={toggleReadOnly} style={{ marginTop: 3 }} />
                <span>
                  <span style={{ fontWeight: 600 }}>{t("Read-only access")}</span>
                  <p className="muted" style={{ fontSize: 12, margin: 0 }}>
                    {t("Sees every tab and feature like a normal Admin, but can't create, edit, delete, or check anyone in — including creating new accounts here.")}
                  </p>
                </span>
              </label>
            )}

            {/* Simplified to 3 dropdowns (2026-07-31 — "when I add new
                account, just need 2 dropdown ... keep it simple", then "add
                back the role to the permission") — replaces the access-role
                template picker BUTTONS + full per-permission checkbox tree
                that used to live here with a template SELECT plus the two
                simple Desktop/Mobile ones. The detailed checkbox tree still
                exists unchanged in "Manage roles" (PermissionCheckboxGroups
                below), which is what BUILDS a named template in the first
                place. Every page/tab stays visible regardless of dropdown
                state; only write (create/edit/delete) capability is what
                "Read-only" revokes — see applyAccessLevels above. */}
            {form.role === "staff" && (
              <>
                <label className="field-label" style={{ marginTop: 14 }}>{t("Access role")}</label>
                <select className="input" value={matchRoleTemplate(form.perms, roleTemplates) || ""}
                  onChange={(e) => applyTemplate(e.target.value)}>
                  <option value="" disabled>{t("Custom")}</option>
                  {roleTemplates.map((tpl) => (
                    <option key={tpl.id} value={tpl.id}>{tpl.label}</option>
                  ))}
                </select>
                <p className="muted" style={{ fontSize: 12, marginTop: 6 }}>
                  {t("Quick-fills the two dropdowns below from a named template (edit templates under \"Manage roles\") — still fully overridable per surface afterward.")}
                </p>

                <label className="field-label" style={{ marginTop: 14 }}>{t("Desktop web view")}</label>
                <select className="input" value={accessLevelFor(form.perms, "desktop")}
                  onChange={(e) => setDesktopAccess(e.target.value)}>
                  <option value="crud">{t("Full access (create, edit, delete)")}</option>
                  <option value="readonly">{t("Read-only")}</option>
                </select>

                <label className="field-label" style={{ marginTop: 14 }}>{t("Mobile view")}</label>
                <select className="input" value={accessLevelFor(form.perms, "mobile")}
                  onChange={(e) => setMobileAccess(e.target.value)}>
                  <option value="crud">{t("Full access (create, edit, delete)")}</option>
                  <option value="readonly">{t("Read-only")}</option>
                </select>

                <p className="muted" style={{ fontSize: 12, marginTop: 6, marginBottom: 4 }}>
                  {t("Read-only can see every page and tab, but can't create, edit, delete, or check anyone in. For finer per-feature control, build a named template under \"Manage roles\" instead.")}
                </p>
              </>
            )}

            {formErr && (
              <div style={S.formErr}><AlertTriangle size={15} /> {t(formErr)}</div>
            )}

            <div className="row" style={{ gap: 10, marginTop: 22, justifyContent: "flex-end" }}>
              <button className="btn btn-ghost" onClick={() => setModalOpen(false)} disabled={saving}>{t("Cancel")}</button>
              <button className="btn btn-primary" onClick={save} disabled={saving}>
                {saving ? t("Saving…") : editingId ? t("Save changes") : t("Create account")}
              </button>
            </div>
          </div>
        </div>
      )}

      {rolesModalOpen && (
        <RoleTemplatesModal
          templates={roleTemplates}
          onClose={() => setRolesModalOpen(false)}
          onChanged={loadRoleTemplates}
          t={t}
        />
      )}
    </div>
  );
}

