/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
import { useEffect, useState, useCallback } from "react";
import {
  Download,
  RefreshCw,
  AlertTriangle,
  UserCheck,
  HelpCircle,
  Bell,
  Activity,
  Crown,
  Plus,
  Pencil,
  Trash2,
  X,
  BarChart3,
} from "lucide-react";
import { apiGet, apiPost, apiPatch, apiDelete, getPermissions } from "../lib/api.js";
import StatusBadge from "../components/StatusBadge.jsx";
import AnalyticsPanel from "../components/AnalyticsPanel.jsx";
import { useLang } from "../lib/i18n.jsx";

/**
 * Screen 2 — Admin Dashboard & Analytics (Jun Qi).
 *
 * Use Case 5 — Real-Time "Missing Person" Identification & Analytics.
 *
 * CRUD build: the delegate list starts empty. Create / edit / delete delegates
 * from the "All delegates" card and every read view above it (KPI tiles, coach
 * bars, live activity, reverse-headcount missing list) recomputes live.
 *
 * Endpoints:
 *   GET    /api/trips/:id/dashboard    → KPIs + coach status + activity
 *   GET    /api/trips/:id/missing      → reverse-headcount list
 *   GET    /api/trips/:id/delegates    → all delegates (read)
 *   POST   /api/trips/:id/delegates    → create
 *   PATCH  /api/delegates/:id          → update
 *   DELETE /api/delegates/:id          → delete
 *   GET    /api/trips/:id/export       → Excel download
 */

const TRIP_ID = "t-1";
const API_BASE = import.meta.env.VITE_API_URL || "/api";

const EMPTY_FORM = { name: "", coachId: "", status: "PRESENT", vip: false, lastSeen: "" };

export default function DashboardPage() {
  const perms = getPermissions();
  const { t } = useLang();
  const [tab, setTab] = useState("overview"); // "overview" | "analytics"
  const [data, setData] = useState(null);
  const [missing, setMissing] = useState([]);
  const [delegates, setDelegates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // modal state
  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null); // null = creating
  const [form, setForm] = useState(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [formErr, setFormErr] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [dash, miss, dels] = await Promise.all([
        apiGet(`/trips/${TRIP_ID}/dashboard`),
        apiGet(`/trips/${TRIP_ID}/missing`),
        apiGet(`/trips/${TRIP_ID}/delegates`),
      ]);
      setData(dash);
      setMissing(miss.missing || []);
      setDelegates(dels.delegates || []);
    } catch (e) {
      setError(e.message || "Could not reach the backend.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  function exportXlsx() {
    window.open(`${API_BASE}/trips/${TRIP_ID}/export?format=xlsx`, "_blank");
  }

  /* ---- CRUD handlers ---------------------------------------------------- */
  function openCreate() {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setFormErr("");
    setModalOpen(true);
  }

  function openEdit(d) {
    setEditingId(d.id);
    setForm({
      name: d.name || "",
      coachId: d.coachId || "",
      status: d.status || "PRESENT",
      vip: !!d.vip,
      lastSeen: d.lastSeen || "",
    });
    setFormErr("");
    setModalOpen(true);
  }

  async function saveForm() {
    if (!form.name.trim()) return;
    // A coach is required unless the delegate is explicitly Unassigned.
    if (form.status !== "UNASSIGNED" && !form.coachId) {
      setFormErr("Please select a coach, or set status to Unassigned.");
      return;
    }
    setFormErr("");
    setSaving(true);
    const payload = {
      name: form.name.trim(),
      coachId: form.status === "UNASSIGNED" ? null : form.coachId || null,
      status: form.status,
      vip: form.vip,
      lastSeen: form.lastSeen.trim(),
    };
    try {
      if (editingId) {
        await apiPatch(`/delegates/${editingId}`, payload);
      } else {
        await apiPost(`/trips/${TRIP_ID}/delegates`, payload);
      }
      setModalOpen(false);
      await load();
    } catch (e) {
      setFormErr(e.message || "Save failed.");
    } finally {
      setSaving(false);
    }
  }

  async function remove(d) {
    if (!window.confirm(`Delete ${d.name}? This cannot be undone.`)) return;
    try {
      await apiDelete(`/delegates/${d.id}`);
      await load();
    } catch (e) {
      setError(e.message || "Delete failed.");
    }
  }

  async function deleteAll() {
    if (!window.confirm(`Delete ALL ${delegates.length} delegates? This cannot be undone.`)) return;
    try {
      await apiDelete(`/trips/${TRIP_ID}/delegates`);
      await load();
    } catch (e) {
      setError(e.message || "Delete all failed.");
    }
  }

  const trip = data?.trip;
  const k = data?.kpis;
  const coaches = data?.coaches || [];
  const coachName = (id) => {
    const c = coaches.find((x) => x.id === id);
    return c ? `${c.name} · ${c.city}` : t("Unassigned");
  };

  return (
    <div className="page">
      {/* ---- Header ------------------------------------------------------- */}
      <div className="row between" style={{ alignItems: "flex-start", flexWrap: "wrap", gap: 16 }}>
        <div>
          <div className="page-eyebrow">{t("Active trip")}</div>
          <h1 className="page-title">{t("Dashboard")}</h1>
          {trip ? (
            <p className="page-sub">
              {trip.name} · Day {trip.dayOf} of {trip.totalDays} · {trip.localTime} local ·{" "}
              {k?.total} delegates
            </p>
          ) : (
            <p className="page-sub">{t("Live present / missing / unassigned visibility.")}</p>
          )}
        </div>

        <div className="row" style={{ gap: 10 }}>
          {data && (
            <span className="badge badge-present">
              <span style={S.dot} /> {t("Live · synced")}
            </span>
          )}
          <button className="btn btn-ghost" onClick={load} title={t("Refresh")}>
            <RefreshCw size={16} className={loading ? "spin" : ""} /> {t("Refresh")}
          </button>
          <button className="btn btn-primary" onClick={exportXlsx} disabled={!data} style={{ display: perms.exportData ? undefined : "none" }}>
            <Download size={16} /> {t("Export")}
          </button>
        </div>
      </div>

      {/* ---- Tabs ----------------------------------------------------------- */}
      <div className="row" style={{ gap: 8, marginTop: 18 }}>
        <button
          className="btn"
          onClick={() => setTab("overview")}
          style={{
            background: tab === "overview" ? "var(--scc-red-tint)" : "transparent",
            color: tab === "overview" ? "var(--scc-red)" : "var(--ink-2)",
            border: `1px solid ${tab === "overview" ? "var(--scc-red-tint-2)" : "var(--line)"}`,
          }}
        >
          {t("Overview")}
        </button>
        <button
          className="btn"
          onClick={() => setTab("analytics")}
          style={{
            background: tab === "analytics" ? "var(--scc-red-tint)" : "transparent",
            color: tab === "analytics" ? "var(--scc-red)" : "var(--ink-2)",
            border: `1px solid ${tab === "analytics" ? "var(--scc-red-tint-2)" : "var(--line)"}`,
          }}
        >
          <BarChart3 size={16} /> {t("Analytics")}
        </button>
      </div>

      {tab === "analytics" && (
        <div style={{ marginTop: 20 }}>
          <AnalyticsPanel />
        </div>
      )}

      {tab === "overview" && (
      <>
      {/* ---- Error banner ------------------------------------------------- */}
      {error && (
        <div
          className="card"
          style={{ marginTop: 20, padding: 16, borderColor: "var(--st-missing)", background: "var(--st-missing-bg)" }}
        >
          <div className="row" style={{ gap: 10, color: "var(--st-missing)", fontWeight: 600 }}>
            <AlertTriangle size={18} /> {t("Couldn't reach the backend")}
          </div>
          <p className="muted" style={{ fontSize: 13, marginTop: 6 }}>
            {error} — make sure it’s running (<code>cd backend &amp;&amp; npm run dev</code>), then hit Refresh.
          </p>
        </div>
      )}

      {loading && !data && (
        <div className="muted" style={{ marginTop: 24 }}>{t("Loading…")}</div>
      )}

      {/* ---- KPI tiles ---------------------------------------------------- */}
      {k && (
        <div style={S.kpiGrid}>
          <Kpi tone="missing" icon={AlertTriangle} label={t("Missing right now")} value={`${k.missing}`}
            suffix={`${t("of")} ${k.total}`} foot={trip ? `Departure in ${trip.departsIn}` : null} big />
          <Kpi tone="present" icon={UserCheck} label={t("Present")} value={`${k.present}`}
            foot={`+${k.presentDelta} in last 5 mins`} />
          <Kpi tone="unassigned" icon={HelpCircle} label={t("Unassigned")} value={`${k.unassigned}`}
            foot={t("No coach yet")} />
          <Kpi tone="normal" icon={Bell} label={t("Open exceptions")} value={`${k.openExceptions}`}
            foot={`${k.criticalExceptions} critical · ${k.normalExceptions} normal`} />
        </div>
      )}

      {/* ---- Coach status + Live activity -------------------------------- */}
      {data && (
        <div style={S.twoCol}>
          <div className="card" style={{ padding: 22 }}>
            <div className="row between" style={{ marginBottom: 16 }}>
              <h2 style={{ fontSize: 16 }}>{t("Coach status")}</h2>
              <span className="muted" style={{ fontSize: 13 }}>{coaches.length} {t("coaches")}</span>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {coaches.map((c) => (
                <CoachBar key={c.id} coach={c} />
              ))}
            </div>
          </div>

          <div className="card" style={{ padding: 22 }}>
            <div className="row" style={{ marginBottom: 16, gap: 8 }}>
              <Activity size={18} color="var(--ink-3)" />
              <h2 style={{ fontSize: 16 }}>{t("Live activity")}</h2>
            </div>
            {data.activity.length === 0 ? (
              <div className="muted" style={{ fontSize: 13 }}>
                {t("No activity yet. Add or update a delegate to see events here.")}
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                {data.activity.map((a) => (
                  <div key={a.id} className="row" style={{ gap: 12, alignItems: "flex-start" }}>
                    <span style={{ ...S.dot, background: activityColor(a.kind), marginTop: 6 }} />
                    <div>
                      <div style={{ fontSize: 14 }}>{a.text}</div>
                      <div className="muted" style={{ fontSize: 12 }}>{a.time} · {a.via}</div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ---- Reverse-headcount missing list ------------------------------ */}
      {data && (
        <div className="card" style={{ marginTop: 20, overflow: "hidden" }}>
          <div className="row between" style={{ padding: "18px 20px", borderBottom: "1px solid var(--line)" }}>
            <div>
              <h2 style={{ fontSize: 16 }}>{t("Missing right now")}</h2>
              <p className="muted" style={{ fontSize: 13, marginTop: 2 }}>
                {t("Reverse headcount — delegates who haven't boarded yet")}
              </p>
            </div>
            <span className="badge badge-missing">{missing.length} {t("missing")}</span>
          </div>

          {missing.length === 0 ? (
            <div className="muted" style={{ padding: 24, fontSize: 14 }}>
              {k?.total ? t("Everyone's accounted for. 🎉") : t("No delegates yet.")}
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr><th>{t("Delegate")}</th><th>{t("Coach")}</th><th>{t("Last seen")}</th><th style={{ width: 90 }} /></tr>
              </thead>
              <tbody>
                {missing.map((m) => (
                  <tr key={m.id}>
                    <td>
                      <div className="row" style={{ gap: 10 }}>
                        <span className="avatar" style={{ background: "var(--st-missing-bg)", color: "var(--st-missing)" }}>
                          {m.initials}
                        </span>
                        <span style={{ fontWeight: 500 }}>{m.name}</span>
                        {m.vip && (
                          <span className="badge badge-review" style={{ padding: "2px 8px" }}>
                            <Crown size={12} /> VIP
                          </span>
                        )}
                      </div>
                    </td>
                    <td>{m.coach}</td>
                    <td className="muted">{m.lastSeen || "—"}</td>
                    <td><span className="badge badge-missing">{t("Missing")}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* ---- All delegates (CRUD surface) -------------------------------- */}
      {data && (
        <div className="card" style={{ marginTop: 20, overflow: "hidden" }}>
          <div className="row between" style={{ padding: "18px 20px", borderBottom: "1px solid var(--line)" }}>
            <div>
              <h2 style={{ fontSize: 16 }}>{t("All delegates")}</h2>
              <p className="muted" style={{ fontSize: 13, marginTop: 2 }}>
                {t("Create, edit, and remove attendance records")}
              </p>
            </div>
            <div className="row" style={{ gap: 10 }}>
              {perms.manageDelegates && delegates.length > 0 && (
                <button className="btn btn-ghost" style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }} onClick={deleteAll}>
                  <Trash2 size={16} /> {t("Delete all")}
                </button>
              )}
              {perms.manageDelegates && (
                <button className="btn btn-primary" onClick={openCreate}>
                  <Plus size={16} /> {t("Add delegate")}
                </button>
              )}
            </div>
          </div>

          {delegates.length === 0 ? (
            <div className="muted" style={{ padding: 24, fontSize: 14 }}>
              {t("No delegates yet. Click")} <strong>{t("Add delegate")}</strong> {t("to create your first record.")}
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr>
                  <th>{t("Delegate")}</th><th>{t("Coach")}</th><th>{t("Status")}</th><th>{t("Last seen")}</th>
                  <th style={{ width: 90 }} />
                </tr>
              </thead>
              <tbody>
                {delegates.map((d) => (
                  <tr key={d.id}>
                    <td>
                      <div className="row" style={{ gap: 10 }}>
                        <span className="avatar">{d.initials}</span>
                        <span style={{ fontWeight: 500 }}>{d.name}</span>
                        {d.vip && (
                          <span className="badge badge-review" style={{ padding: "2px 8px" }}>
                            <Crown size={12} /> VIP
                          </span>
                        )}
                      </div>
                    </td>
                    <td>{coachName(d.coachId)}</td>
                    <td><StatusBadge state={d.status} /></td>
                    <td className="muted">{d.lastSeen || "—"}</td>
                    <td>
                      {perms.manageDelegates ? (
                        <div className="row" style={{ gap: 6 }}>
                          <button onClick={() => openEdit(d)} aria-label={`Edit ${d.name}`}
                            style={S.iconBtn}>
                            <Pencil size={16} />
                          </button>
                          <button onClick={() => remove(d)} aria-label={`Delete ${d.name}`}
                            style={{ ...S.iconBtn, color: "var(--st-missing)" }}>
                            <Trash2 size={16} />
                          </button>
                        </div>
                      ) : (
                        <span className="muted" style={{ fontSize: 12 }}>—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* ---- Create / Edit modal ----------------------------------------- */}
      {modalOpen && (
        <div style={S.overlay} onClick={() => !saving && setModalOpen(false)}>
          <div className="card" style={S.modal} onClick={(e) => e.stopPropagation()}>
            <div className="row between" style={{ marginBottom: 18 }}>
              <h2 style={{ fontSize: 18 }}>{editingId ? t("Edit delegate") : t("Add delegate")}</h2>
              <button onClick={() => setModalOpen(false)} style={S.iconBtn} aria-label="Close">
                <X size={18} />
              </button>
            </div>

            <label className="field-label">{t("Full name")}</label>
            <input className="input" autoFocus value={form.name}
              placeholder="e.g. Lim Wei Jie"
              onChange={(e) => setForm({ ...form, name: e.target.value })} />

            <label className="field-label" style={{ marginTop: 14 }}>{t("Status")}</label>
            <select className="select" value={form.status}
              onChange={(e) => setForm({ ...form, status: e.target.value })}>
              <option value="PRESENT">{t("Present")}</option>
              <option value="MISSING">{t("Missing")}</option>
              <option value="UNASSIGNED">{t("Unassigned")}</option>
            </select>

            <label className="field-label" style={{ marginTop: 14 }}>
              {t("Coach")} {form.status !== "UNASSIGNED" && <span className="muted">(required)</span>}
            </label>
            <select className="select" value={form.coachId}
              disabled={form.status === "UNASSIGNED"}
              onChange={(e) => setForm({ ...form, coachId: e.target.value })}>
              <option value="">{form.status === "UNASSIGNED" ? t("No coach (unassigned)") : t("Select a coach…")}</option>
              {coaches.map((c) => (
                <option key={c.id} value={c.id}>{c.name} · {c.city}</option>
              ))}
            </select>

            <label className="field-label" style={{ marginTop: 14 }}>{t("Last seen (optional)")}</label>
            <input className="input" value={form.lastSeen}
              placeholder="e.g. Lobby · 14:08"
              onChange={(e) => setForm({ ...form, lastSeen: e.target.value })} />

            <label className="row" style={{ gap: 8, marginTop: 16, fontSize: 14, cursor: "pointer" }}>
              <input type="checkbox" checked={form.vip}
                onChange={(e) => setForm({ ...form, vip: e.target.checked })} />
              {t("Mark as VIP")}
            </label>

            {formErr && (
              <div style={{
                display: "flex", alignItems: "center", gap: 8, marginTop: 16, padding: "10px 12px",
                background: "var(--st-missing-bg)", color: "var(--st-missing)", borderRadius: "var(--r-sm)",
                fontSize: 13, fontWeight: 600,
              }}>
                {formErr}
              </div>
            )}

            <div className="row" style={{ gap: 10, marginTop: 24, justifyContent: "flex-end" }}>
              <button className="btn btn-ghost" onClick={() => setModalOpen(false)} disabled={saving}>
                {t("Cancel")}
              </button>
              <button className="btn btn-primary" onClick={saveForm} disabled={saving || !form.name.trim()}>
                {saving ? t("Saving…") : editingId ? t("Save changes") : t("Add delegate")}
              </button>
            </div>
          </div>
        </div>
      )}
      </>
      )}

      <style>{`.spin{animation:mg-spin 0.9s linear infinite}@keyframes mg-spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}

/* ---- KPI tile ----------------------------------------------------------- */
function Kpi({ tone, icon: Icon, label, value, suffix, foot, big }) {
  return (
    <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column", gap: 10 }}>
      <div className="row between">
        <span className="page-eyebrow" style={{ color: `var(--st-${tone})` }}>{label}</span>
        <Icon size={18} color={`var(--st-${tone})`} />
      </div>
      <div className="row" style={{ alignItems: "baseline", gap: 8 }}>
        <span className="mono"
          style={{ fontSize: big ? 44 : 40, fontWeight: 700, color: `var(--st-${tone})`, lineHeight: 1 }}>
          {value}
        </span>
        {suffix && <span className="muted" style={{ fontSize: 16 }}>{suffix}</span>}
      </div>
      {foot && <div className="muted" style={{ fontSize: 13 }}>{foot}</div>}
    </div>
  );
}

/* ---- Coach progress bar ------------------------------------------------- */
function CoachBar({ coach }) {
  const { t } = useLang();
  const pct = coach.capacity ? Math.round((coach.boarded / coach.capacity) * 100) : 0;
  const allIn = coach.total > 0 && coach.missing === 0;
  const barColor = coach.missing > 0 ? "var(--st-missing)" : "var(--st-present)";
  return (
    <div>
      <div className="row between" style={{ marginBottom: 6 }}>
        <div className="row" style={{ gap: 10 }}>
          <span className="avatar" style={{ background: "var(--st-neutral-bg)", color: "var(--ink-2)" }}>
            {coach.label}
          </span>
          <span style={{ fontWeight: 500, fontSize: 14 }}>{coach.name} · {coach.city}</span>
        </div>
        {coach.missing > 0 ? (
          <span className="badge badge-missing">{coach.missing} {t("missing")}</span>
        ) : allIn ? (
          <span className="badge badge-present">{t("All in")}</span>
        ) : (
          <span className="badge badge-neutral">{t("Empty")}</span>
        )}
      </div>
      <div style={S.track}>
        <div style={{ ...S.fill, width: `${pct}%`, background: barColor }} />
      </div>
      <div className="muted mono" style={{ fontSize: 12, marginTop: 4 }}>
        {coach.boarded}/{coach.capacity} {t("boarded")}
      </div>
    </div>
  );
}

function activityColor(kind) {
  if (kind === "exception") return "var(--st-missing)";
  if (kind === "reassign") return "var(--st-unassigned)";
  return "var(--st-present)";
}

/* ---- Local styles ------------------------------------------------------- */
const S = {
  dot: { width: 10, height: 10, borderRadius: 999, background: "var(--st-present)", display: "inline-block", flexShrink: 0 },
  kpiGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(210px, 1fr))", gap: 16, marginTop: 22 },
  twoCol: { display: "grid", gridTemplateColumns: "1.3fr 1fr", gap: 16, marginTop: 20 },
  track: { height: 8, borderRadius: 999, background: "var(--line)", overflow: "hidden" },
  fill: { height: "100%", borderRadius: 999, transition: "width 0.4s ease" },
  iconBtn: { background: "none", border: "none", color: "var(--ink-3)", display: "flex", padding: 4, borderRadius: 6 },
  overlay: { position: "fixed", inset: 0, background: "rgba(16,24,40,0.45)", display: "grid", placeItems: "center", padding: 20, zIndex: 50 },
  modal: { width: "min(440px, 100%)", padding: 24, background: "#fff" },
};
