/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
import { useState } from "react";
import { ClipboardCheck, Eye, EyeOff, Fingerprint, AlertCircle, Languages } from "lucide-react";
import { apiPost, setToken, setUser } from "../lib/api.js";
import { useLang } from "../lib/i18n.jsx";

const REMEMBER_KEY = "mg_remember_v2";

// One-time cleanup: an earlier build always kept "Keep me signed in" ticked
// and could save your password even when you didn't intend it. Remove any value
// left under the old key so a fresh start never prefills a password unexpectedly.
// (Values saved by the current build use the new key and are unaffected.)
try { localStorage.removeItem("mg_remember"); } catch { /* ignore */ }

// Read remembered login (used to prefill the form). Stored only when the user
// ticked "Keep me signed in". NOTE: this includes the password in localStorage,
// which is fine for a school demo but is NOT production-safe.
function readRemembered() {
  try {
    return JSON.parse(localStorage.getItem(REMEMBER_KEY)) || null;
  } catch {
    return null;
  }
}

/**
 * Screen 1 — Login / Authentication (shared across team; Vance leads).
 * Split layout: SCCCI-Red brand panel + sign-in form.
 *
 * Login validates against the backend (POST /api/auth/login) using accounts
 * managed on the Account control page. If "Keep me signed in" was ticked, the
 * previous username + password are pre-filled so you can re-login in one click.
 */
export default function LoginPage({ onSignIn }) {
  const { lang, toggleLang, t } = useLang();
  const remembered = readRemembered();
  const [staffId, setStaffId] = useState(remembered?.staffId || "");
  const [password, setPassword] = useState(remembered?.password || "");
  const [showPw, setShowPw] = useState(false);
  const [keep, setKeep] = useState(!!remembered); // ticked only if a login was remembered
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function handleSignIn() {
    setError("");

    if (!staffId.trim() || !password) {
      setError("Please enter your Staff ID and password.");
      return;
    }

    setSubmitting(true);
    try {
      const { token, name, role, username, permissions } = await apiPost("/auth/login", {
        staffId: staffId.trim(),
        password,
      });
      if (token) {
        setToken(token, keep); // keep = "Keep me signed in" checkbox
        setUser({ staffId: username || staffId.trim(), username: username || staffId.trim(), name, role, permissions }, keep);
        // Remember (or forget) the login for one-click re-login next time.
        if (keep) {
          localStorage.setItem(REMEMBER_KEY, JSON.stringify({ staffId: staffId.trim(), password }));
        } else {
          localStorage.removeItem(REMEMBER_KEY);
        }
      }
      onSignIn?.(); // success -> enter the app
    } catch (e) {
      const msg = String(e?.message || "");
      if (msg.includes("401")) {
        setError("Incorrect Staff ID or password.");
      } else if (msg.includes("400")) {
        setError("Please enter your Staff ID and password.");
      } else {
        setError("Can't reach the server. Make sure the backend is running.");
      }
    } finally {
      setSubmitting(false);
    }
  }

  function handleWorkpass() {
    setError("Workpass sign-in isn't set up in this build — please use your Staff ID and password.");
  }

  function onKeyDown(e) {
    if (e.key === "Enter") handleSignIn();
  }

  return (
    <div style={S.wrap}>
      <button
        onClick={toggleLang}
        className="btn btn-ghost"
        style={{ position: "absolute", top: 20, right: 20, background: "#fff" }}
      >
        <Languages size={16} /> {lang === "en" ? "中文" : "English"}
      </button>
      <div className="login-card" style={S.card}>
        {/* Brand panel */}
        <div className="login-panel" style={S.brand}>
          <div className="wordmark" style={{ color: "#fff", fontSize: 30 }}>
            <ClipboardCheck size={30} strokeWidth={2.4} /> MusterGo
          </div>
          <div>
            <h2 style={S.brandH}>{t("No one gets left behind.")}</h2>
            <p style={S.brandP}>{t("Real-time delegation attendance for SCCCI overseas trips.")}</p>
          </div>
          <p style={S.brandFoot}>{t("A Singapore Chinese Chamber of Commerce & Industry initiative")}</p>
        </div>

        {/* Form panel */}
        <div className="login-panel" style={S.form}>
          <h1 style={{ fontSize: 26 }}>{t("Sign in")}</h1>
          <p className="muted" style={{ marginTop: 4, marginBottom: 24, fontSize: 14 }}>
            {t("SCCCI secretariat & on-ground staff")}
          </p>

          <label className="field-label" htmlFor="staffId">{t("Staff ID")}</label>
          <input
            id="staffId"
            className="input"
            placeholder="e.g. SCCCI132"
            value={staffId}
            onChange={(e) => setStaffId(e.target.value)}
            onKeyDown={onKeyDown}
          />

          <label className="field-label" htmlFor="pw" style={{ marginTop: 16 }}>{t("Password")}</label>
          <div style={{ position: "relative" }}>
            <input
              id="pw"
              className="input"
              type={showPw ? "text" : "password"}
              placeholder="............"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              onKeyDown={onKeyDown}
              style={{ paddingRight: 42 }}
            />
            <button
              type="button"
              onClick={() => setShowPw((v) => !v)}
              aria-label={showPw ? "Hide password" : "Show password"}
              style={S.eye}
            >
              {showPw ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>

          {/* Inline error */}
          {error && (
            <div style={S.error} role="alert">
              <AlertCircle size={16} /> {error}
            </div>
          )}

          <div className="row between" style={{ margin: "14px 0 22px" }}>
            <label className="row" style={{ gap: 8, fontSize: 13, cursor: "pointer" }}>
              <input type="checkbox" checked={keep} onChange={(e) => setKeep(e.target.checked)} />
              {t("Keep me signed in")}
            </label>
            <a href="#" style={{ color: "var(--scc-red)", fontSize: 13, fontWeight: 600, textDecoration: "none" }}>
              {t("Forgot password?")}
            </a>
          </div>

          <button className="btn btn-primary btn-block" onClick={handleSignIn} disabled={submitting}>
            {submitting ? t("Signing in…") : t("Sign in")}
          </button>
          <button className="btn btn-ghost btn-block" style={{ marginTop: 10 }} onClick={handleWorkpass} disabled={submitting}>
            <Fingerprint size={18} color="var(--scc-red)" /> {t("Sign in with Workpass")}
          </button>

          <p className="muted" style={{ fontSize: 11, textAlign: "center", marginTop: 16 }}>
            {t("By signing in, you accept the SCCCI data handling policy.")}
          </p>
        </div>
      </div>

      <style>{`
        .login-card { display: grid; grid-template-columns: 1fr 1fr; }
        @media (max-width: 720px) {
          .login-card { grid-template-columns: 1fr; }
          .login-panel { padding: 24px !important; }
        }
      `}</style>
    </div>
  );
}

const S = {
  wrap: { minHeight: "100vh", display: "grid", placeItems: "center", padding: 24, background: "var(--bg)" },
  card: {
    width: "min(880px, 100%)",
    maxHeight: "calc(100vh - 48px)",
    background: "#fff",
    borderRadius: "var(--r-lg)",
    overflow: "hidden",
    overflowY: "auto",
    boxShadow: "var(--shadow-lg)",
  },
  brand: {
    background: "var(--scc-red)",
    color: "#fff",
    padding: 40,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 40,
  },
  brandH: { fontSize: 28, lineHeight: 1.2, fontWeight: 700 },
  brandP: { marginTop: 10, opacity: 0.9, fontSize: 15, lineHeight: 1.5 },
  brandFoot: { fontSize: 12, opacity: 0.8, fontWeight: 600 },
  form: { padding: 40 },
  eye: {
    position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)",
    background: "none", border: "none", color: "var(--scc-red)", display: "flex",
  },
  error: {
    display: "flex", alignItems: "center", gap: 8,
    marginTop: 14, padding: "10px 12px",
    background: "var(--st-missing-bg)", color: "var(--st-missing)",
    borderRadius: "var(--r-sm)", fontSize: 13, fontWeight: 600,
  },
};
