/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  OWNERSHIP.md at the project root for what's yours vs. what's off-limits.
 * ============================================================================= */
import { useEffect, useState, useCallback, useMemo, useRef } from "react";
import { useNavigate } from "react-router-dom";
import {
  Download,
  RefreshCw,
  AlertTriangle,
  UserCheck,
  HelpCircle,
  Clock,
  Activity,
  Crown,
  Plus,
  Pencil,
  Trash2,
  X,
  BarChart3,
  ChevronRight,
  MapPin,
  Users,
  Radio,
} from "lucide-react";
import { apiGet, apiPost, apiPatch, apiDelete, getPermissions } from "../../lib/api.js";
import StatusBadge from "../../components/StatusBadge.jsx";
import AnalyticsPanel from "../../components/AnalyticsPanel.jsx";
import DelegateAvatar, { statusTone } from "../../components/DelegateAvatar.jsx";
import DelegateLocationMap from "../../components/DelegateLocationMap.jsx";
import ExportModal from "../../components/ExportModal.jsx";
import { useLang } from "../../lib/i18n.jsx";

/**
 * Screen 2 — Admin Dashboard & Analytics (Jun Qi).
 *
 * Use Case 5 — Real-Time "Missing Person" Identification & Analytics.
 *
 * CRUD build: the delegate list starts empty. Create / edit / delete delegates
 * from the "All delegates" card and every read view above it (KPI tiles, coach
 * bars, live activity, reverse-headcount missing list) recomputes live.
 *
 * Endpoints:
 *   GET    /api/trips/:id/dashboard    → KPIs + coach status + activity
 *   GET    /api/trips/:id/missing      → reverse-headcount list
 *   GET    /api/trips/:id/delegates    → all delegates (read)
 *   POST   /api/trips/:id/delegates    → create
 *   PATCH  /api/delegates/:id          → update
 *   DELETE /api/delegates/:id          → delete
 *   GET    /api/trips/:id/export       → Excel download
 */

const TRIP_ID = "t-1";

const EMPTY_FORM = {
  name: "", coachId: "", status: "ARRIVED", vip: false, lastSeen: "", lastLocation: "",
  company: "", role: "", industry: "", email: "", phone: "", website: "",
  passportNumber: "", nationality: "", passportExpiry: "", accessibilityNotes: "", notes: "",
};

export default function DashboardPage() {
  const perms = getPermissions();
  // Two-role RBAC: Admin sees every tab (bypasses every permission check —
  // accountPermissions() returns all-true for role="admin"). Staff sees the
  // Analytics tab based on the viewAnalytics permission (2026-07-21 — was
  // hardcoded role==="admin" only; now a real per-account toggle, defaulting
  // closed since it's a genuinely new capability being unlocked, not one
  // being narrowed). Staff operations stays gated on manageAccounts, which
  // perms.manageAccounts only carries for admins now (see permissions.js's
  // adminOnly doc — Staff can never be individually granted it).
  const { t, lang } = useLang();
  const navigate = useNavigate();

  // The page is tall (KPIs, coach status, history, the full delegate table),
  // and browsers restore the previous scroll position on SPA route re-entry
  // by default — landing back on Dashboard scrolled to the bottom instead of
  // showing a fresh top-of-page view. Reset once on mount only (not on every
  // 2s poll re-render, which doesn't remount this component).
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // Default to the first tab this account can actually see — viewDelegates
  // gates the Delegate tab the same way Analytics is gated on viewAnalytics
  // and Staff operations on manageAccounts (see the tab buttons below); an
  // account with none of the three still needs SOME initial value, so it
  // falls back to "delegate" (its content block is itself gated, so nothing
  // renders — same "no visible tabs" edge case the desktop/mobile route
  // fallbacks in App.jsx already accept).
  const [tab, setTab] = useState(() => {
    if (perms.viewDelegates) return "delegate";
    if (perms.viewAnalytics) return "analytics";
    if (perms.manageAccounts) return "staffops";
    return "delegate";
  }); // "delegate" | "analytics" | "headcount" | "staffops"
  const [data, setData] = useState(null);
  const [missing, setMissing] = useState([]);
  const [delegates, setDelegates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Trip switcher — the whole dashboard re-points to the selected trip.
  // "t-1" = the default Beijing trip (unfiltered); anything else is a trip uuid.
  const [selectedTripId, setSelectedTripId] = useState(TRIP_ID);
  const [trips, setTrips] = useState([]);            // all trips (for the dropdown)
  const [mainTrip, setMainTrip] = useState(null);    // { uuid, name } of the base trip

  // "All delegates" table filter + sort
  const [delegateQuery, setDelegateQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [coachFilter, setCoachFilter] = useState("ALL"); // ALL | <coachId> | UNASSIGNED
  const [sortMode, setSortMode] = useState("name"); // name | recent | status | coach
  const [showAllDelegates, setShowAllDelegates] = useState(false);
  const [showAllCoaches, setShowAllCoaches] = useState(false);

  // Batch selection for "All delegates" — replaces the old blanket "Delete
  // all" button with per-row checkboxes + a "Delete selected" action.
  const [selectedDelegateIds, setSelectedDelegateIds] = useState(new Set());
  const [deletingSelectedDelegates, setDeletingSelectedDelegates] = useState(false);
  const [history, setHistory] = useState([]);

  // "Staff operations" tab — admin-only (manageAccounts), lives on this same
  // page rather than a separate route so admins don't have to leave the
  // Dashboard to see who's currently signed in.
  const [staffOps, setStaffOps] = useState(null); // { totalStaff, activeCount, active }
  const [staffOpsError, setStaffOpsError] = useState(null);

  // Reverse headcount — opened on demand from a button on the "Coach status"
  // card, not a persistent tab (was one; the user liked the content but not
  // that UX, so it moved to an on-demand modal instead).
  const [headcountOpen, setHeadcountOpen] = useState(false);
  const [exportOpen, setExportOpen] = useState(false);
  const delegateTableRef = useRef(null);


  // modal state
  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState(null); // null = creating
  const [form, setForm] = useState(EMPTY_FORM);
  const [showMoreFields, setShowMoreFields] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formErr, setFormErr] = useState("");
  const [editingPhotoUrl, setEditingPhotoUrl] = useState(null);
  const [photoBusy, setPhotoBusy] = useState(false);
  const [photoErr, setPhotoErr] = useState("");
  const [mapDelegate, setMapDelegate] = useState(null); // delegate whose location map is open, or null

  // Guards against overlapping polls (e.g. a slow response still in flight
  // when the next 2s tick fires) — same pattern as useSessionGuard's
  // checkingRef, so a late response can't stomp a more recent one.
  const loadingRef = useRef(false);
  const load = useCallback(async () => {
    if (loadingRef.current) return;
    loadingRef.current = true;
    setLoading(true);
    setError(null);
    try {
      const [dash, miss, dels, hist] = await Promise.all([
        apiGet(`/trips/${selectedTripId}/dashboard`),
        apiGet(`/trips/${selectedTripId}/missing`),
        apiGet(`/trips/${selectedTripId}/delegates`),
        apiGet(`/activity?limit=200`),
      ]);
      setData(dash);
      setMissing(miss.missing || []);
      setDelegates(dels.delegates || []);
      setHistory(hist.activity || []);
      // Remember the base trip's uuid the first time we load it, so the trip
      // dropdown can list the OTHER trips without duplicating it.
      if (selectedTripId === TRIP_ID && dash.trip?.uuid_id) {
        setMainTrip({ uuid: dash.trip.uuid_id, name: dash.trip.name });
      }
    } catch (e) {
      setError(e.message || "Could not reach the backend.");
    } finally {
      setLoading(false);
      loadingRef.current = false;
    }
  }, [selectedTripId]);

  // Auto-refresh every 2s so a change made by another signed-in staff member
  // (a status edit, a new upload, a coach reassignment, etc.) shows up here
  // without anyone having to hit the manual Refresh button. Safe against the
  // create/edit delegate modal's own form state, which is a separate local
  // copy seeded once when the modal opens — a background refresh of the
  // underlying `delegates` list doesn't touch it.
  useEffect(() => {
    load();
    const id = setInterval(load, 2000);
    return () => clearInterval(id);
  }, [load]);

  // Trip list for the switcher (Desmond's all-trips), fetched once.
  useEffect(() => {
    apiGet("/all-trips").then((r) => setTrips(r.trips || [])).catch(() => {});
  }, []);

  // "Staff operations" tab data — only polled while that tab is open (no
  // point hitting the endpoint for admins looking at Delegate/Analytics),
  // and only for accounts that can actually see the tab. Pulled out of the
  // effect (rather than defined inline) so the top "Refresh" button can also
  // call it directly instead of only refreshing dashboard/missing/delegates.
  const loadStaffOps = useCallback(() => {
    if (!perms.manageAccounts) return;
    apiGet("/staff/active-sessions")
      .then((r) => { setStaffOps(r); setStaffOpsError(null); })
      .catch((e) => setStaffOpsError(e.message || "Could not reach the backend."));
  }, [perms.manageAccounts]);

  useEffect(() => {
    if (tab !== "staffops" || !perms.manageAccounts) return;
    loadStaffOps();
    // 2s so a login/logout elsewhere shows up here almost immediately —
    // scoped to only fire while an admin actually has this tab open, so it
    // doesn't add load for anyone else.
    const id = setInterval(loadStaffOps, 2000);
    return () => clearInterval(id);
  }, [tab, perms.manageAccounts, loadStaffOps]);

  // Excel export now runs through the ExportModal (opened by the Export
  // button), which lets the user pick status/coach/VIP/columns + an AI filter
  // before downloading — see components/ExportModal.jsx.

  // KPI tile drill-down → jump to the delegate table filtered to that status
  // and scroll it into view. Shared by all 4 primary tiles (Missing/Present/
  // Unassigned/Late) so every one of them behaves the same way.
  function showDelegatesFiltered(status) {
    setTab("delegate");
    setStatusFilter(status);
    requestAnimationFrame(() =>
      delegateTableRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })
    );
  }

  /* ---- CRUD handlers ---------------------------------------------------- */
  function openCreate() {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setFormErr("");
    setEditingPhotoUrl(null);
    setPhotoErr("");
    setShowMoreFields(false);
    setModalOpen(true);
  }

  function openEdit(d) {
    setEditingId(d.id);
    setForm({
      name: d.name || "",
      coachId: d.coachId || "",
      // Legacy rows may still say "PRESENT" (some check-in routes haven't
      // migrated to writing "ARRIVED" yet) — alias it here so the status
      // <select> (which only lists the 5 current values) always has a
      // matching option instead of silently showing blank.
      status: d.status === "PRESENT" ? "ARRIVED" : (d.status || "UNASSIGNED"),
      vip: !!d.vip,
      lastSeen: d.lastSeen || "",
      lastLocation: d.lastLocation || "",
      company: d.company || "", role: d.role || "", industry: d.industry || "",
      email: d.email || "", phone: d.phone || "", website: d.website || "",
      // GET returns raw DB column names (snake_case) for these three — the
      // rest are already single-word/camelCase-compatible either way.
      passportNumber: d.passport_no || "", nationality: d.nationality || "", passportExpiry: d.passport_expiry || "",
      accessibilityNotes: d.accessibility_notes || "", notes: d.notes || "",
    });
    setEditingPhotoUrl(d.photoUrl || null);
    setFormErr("");
    setShowMoreFields(false);
    setModalOpen(true);
  }

  async function handlePhotoChange(file) {
    if (!file || !editingId) return;
    setPhotoErr("");
    setPhotoBusy(true);
    try {
      const fd = new FormData();
      fd.append("photo", file);
      const { photoUrl } = await apiPost(`/delegates/${editingId}/photo`, fd, true);
      setEditingPhotoUrl(photoUrl);
      await load();
    } catch (e) {
      setPhotoErr(e.message || "Upload failed.");
    } finally {
      setPhotoBusy(false);
    }
  }

  async function handleRemovePhoto() {
    if (!editingId) return;
    setPhotoErr("");
    setPhotoBusy(true);
    try {
      await apiDelete(`/delegates/${editingId}/photo`);
      setEditingPhotoUrl(null);
      await load();
    } catch (e) {
      setPhotoErr(e.message || "Remove failed.");
    } finally {
      setPhotoBusy(false);
    }
  }

  async function saveForm() {
    if (!form.name.trim()) return;
    // A coach is required unless the delegate is explicitly Unassigned.
    if (form.status !== "UNASSIGNED" && !form.coachId) {
      setFormErr("Please select a coach, or set status to Unassigned.");
      return;
    }
    // A last known location is required once a delegate is marked Missing —
    // it's the whole point of the field (finding them), so it can't be left
    // blank the way "Last seen" (a free-text note) can.
    if (form.status === "MISSING" && !form.lastLocation.trim()) {
      setFormErr("Please enter a last known location for a missing delegate.");
      return;
    }
    setFormErr("");
    setSaving(true);
    const payload = {
      name: form.name.trim(),
      coachId: form.status === "UNASSIGNED" ? null : form.coachId || null,
      status: form.status,
      vip: form.vip,
      // Last seen / location only ever apply while a delegate is missing —
      // cleared on save otherwise so switching status away from Missing
      // doesn't silently carry stale data forward into a later Missing spell.
      lastSeen: form.status === "MISSING" ? form.lastSeen.trim() : "",
      lastLocation: form.status === "MISSING" ? form.lastLocation.trim() : "",
      company: form.company.trim(), role: form.role.trim(), industry: form.industry.trim(),
      email: form.email.trim(), phone: form.phone.trim(), website: form.website.trim(),
      passportNumber: form.passportNumber.trim(), nationality: form.nationality.trim(),
      passportExpiry: form.passportExpiry.trim(),
      accessibilityNotes: form.accessibilityNotes.trim(), notes: form.notes.trim(),
    };
    try {
      if (editingId) {
        await apiPatch(`/delegates/${editingId}`, payload);
      } else {
        await apiPost(`/trips/${selectedTripId}/delegates`, payload);
      }
      setModalOpen(false);
      await load();
    } catch (e) {
      setFormErr(e.message || "Save failed.");
    } finally {
      setSaving(false);
    }
  }

  async function remove(d) {
    const msg = lang === "zh"
      ? `确定删除 ${d.name}？此操作无法撤销。`
      : `Delete ${d.name}? This cannot be undone.`;
    if (!window.confirm(msg)) return;
    try {
      await apiDelete(`/delegates/${d.id}`);
      await load();
    } catch (e) {
      setError(e.message || "Delete failed.");
    }
  }

  function toggleDelegateSelected(id) {
    setSelectedDelegateIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  }

  async function deleteSelectedDelegates() {
    const count = selectedDelegateIds.size;
    if (count === 0) return;
    const msg = lang === "zh"
      ? `确定删除选中的 ${count} 位代表？此操作无法撤销。`
      : `Delete ${count} selected delegate${count === 1 ? "" : "s"}? This cannot be undone.`;
    if (!window.confirm(msg)) return;

    setDeletingSelectedDelegates(true);
    setError(null);
    const ids = [...selectedDelegateIds];
    const results = await Promise.allSettled(ids.map((id) => apiDelete(`/delegates/${id}`)));
    const failed = results.filter((r) => r.status === "rejected");
    if (failed.length > 0) {
      setError(failed[0].reason?.message || "Delete failed.");
    }
    setSelectedDelegateIds(new Set());
    setDeletingSelectedDelegates(false);
    await load();
  }

  async function deleteAll() {
    const msg = lang === "zh"
      ? `确定删除全部 ${delegates.length} 位代表？此操作无法撤销。`
      : `Delete ALL ${delegates.length} delegates? This cannot be undone.`;
    if (!window.confirm(msg)) return;
    try {
      await apiDelete(`/trips/${selectedTripId}/delegates`);
      setSelectedDelegateIds(new Set());
      await load();
    } catch (e) {
      setError(e.message || "Delete all failed.");
    }
  }

  async function removeHistoryEntry(id) {
    try {
      await apiDelete(`/activity/${id}`);
      setHistory((h) => h.filter((a) => a.id !== id));
    } catch (e) {
      setError(e.message || "Delete failed.");
    }
  }

  async function clearHistory() {
    const msg = lang === "zh"
      ? `确定清空全部 ${history.length} 条历史记录？此操作无法撤销。`
      : `Clear ALL ${history.length} history entries? This cannot be undone.`;
    if (!window.confirm(msg)) return;
    try {
      await apiDelete(`/activity`);
      setHistory([]);
    } catch (e) {
      setError(e.message || "Delete all failed.");
    }
  }

  const trip = data?.trip;
  const k = data?.kpis;
  const coaches = data?.coaches || [];
  const coachName = (id) => {
    const c = coaches.find((x) => x.id === id);
    return c ? coachDisplayName(c) : t("Unassigned");
  };

  // Legacy rows may still hold "PRESENT" (routes that haven't migrated to
  // writing "ARRIVED" yet) — alias for filtering/sorting so those rows show
  // up under "Arrived" instead of silently vanishing from that filter.
  const effectiveStatus = (d) => (d.status === "PRESENT" ? "ARRIVED" : d.status);

  // The "All delegates" table, after the search box, status filter and sort.
  const visibleDelegates = useMemo(() => {
    const query = delegateQuery.trim().toLowerCase();
    let list = delegates.filter((d) => {
      if (statusFilter !== "ALL" && effectiveStatus(d) !== statusFilter) return false;
      // Coach filter: a real coach id matches that coach; "UNASSIGNED" matches
      // delegates with no coach (coachId null/empty).
      if (coachFilter === "UNASSIGNED") {
        if (d.coachId) return false;
      } else if (coachFilter !== "ALL" && d.coachId !== coachFilter) {
        return false;
      }
      if (query) {
        const hay = `${d.name || ""} ${d.company || ""}`.toLowerCase();
        if (!hay.includes(query)) return false;
      }
      return true;
    });
    const byName = (a, b) => (a.name || "").localeCompare(b.name || "");
    list = [...list].sort((a, b) => {
      if (sortMode === "recent") return new Date(b.createdAt || 0) - new Date(a.createdAt || 0);
      if (sortMode === "status") return (a.status || "").localeCompare(b.status || "") || byName(a, b);
      if (sortMode === "coach") return coachName(a.coachId).localeCompare(coachName(b.coachId)) || byName(a, b);
      return byName(a, b); // name
    });
    return list;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [delegates, delegateQuery, statusFilter, coachFilter, sortMode, coaches]);

  /* ---- Trip switcher derived state -------------------------------------- */
  // The uuid of the trip currently shown (for the "open in Trips board" links).
  const currentTripUuid = selectedTripId === TRIP_ID ? (trip?.uuid_id || mainTrip?.uuid) : selectedTripId;
  // Dropdown: the base trip (as "t-1", unfiltered) + every other trip by uuid.
  const tripOptions = useMemo(() => {
    const opts = [{ id: TRIP_ID, name: mainTrip?.name || trip?.name || "Beijing study mission" }];
    for (const tr of trips) {
      if (mainTrip && tr.id === mainTrip.uuid) continue; // skip the base (it's the t-1 option)
      opts.push({ id: tr.id, name: tr.name });
    }
    return opts;
  }, [trips, mainTrip, trip]);

  const TOP_N = 10;
  const COACH_TOP_N = 4;
  const openCoachBoard = () => { if (currentTripUuid) navigate(`/trips?tripId=${currentTripUuid}`); };

  // The delegate rows actually rendered in the table right now (respects the
  // "Show all" toggle) — the "select all" checkbox scopes to exactly this
  // set, matching the same convention as the Trips/Onboarding pages.
  const rowsShown = showAllDelegates ? visibleDelegates : visibleDelegates.slice(0, TOP_N);

  return (
    <div className="page">
      {/* ---- Header ------------------------------------------------------- */}
      <div className="row between" style={{ alignItems: "flex-start", flexWrap: "wrap", gap: 16 }}>
        <div>
          <div className="page-eyebrow">{t("Active trip")}</div>
          <h1 className="page-title">{t("Dashboard")}</h1>
          {trip ? (
            <p className="page-sub">
              {lang === "zh"
                ? `${trip.name} · 第 ${trip.dayOf}/${trip.totalDays} 天${trip.localTime ? ` · 当地时间 ${trip.localTime}` : ""} · ${k?.total} 位代表`
                : `${trip.name} · Day ${trip.dayOf} of ${trip.totalDays}${trip.localTime ? ` · ${trip.localTime} local` : ""} · ${k?.total} delegates`}
            </p>
          ) : (
            <p className="page-sub">{t("Live present / missing / unassigned visibility.")}</p>
          )}
        </div>

        <div className="row" style={{ gap: 10, flexWrap: "wrap" }}>
          {data && (
            <span className="badge badge-present">
              <span style={S.dot} /> {t("Live · synced")}
            </span>
          )}
          <button
            className="btn btn-ghost"
            onClick={() => { load(); if (tab === "staffops") loadStaffOps(); }}
            title={t("Refresh")}
          >
            <RefreshCw size={16} className={loading ? "spin" : ""} /> {t("Refresh")}
          </button>
          <button className="btn btn-primary" onClick={() => setExportOpen(true)} disabled={!data} style={{ display: perms.exportData ? undefined : "none" }}>
            <Download size={16} /> {t("Export")}
          </button>
        </div>
      </div>

      {/* ---- Trip switcher bar (its own row, so its position never shifts) - */}
      {tripOptions.length > 1 && (
        <div className="row" style={{ gap: 8, marginTop: 16, alignItems: "center", flexWrap: "wrap" }}>
          <span className="muted" style={{ fontSize: 13 }}>{t("Viewing trip")}</span>
          <select
            className="select"
            style={{ maxWidth: 260 }}
            value={selectedTripId}
            onChange={(e) => { setSelectedTripId(e.target.value); setShowAllDelegates(false); setShowAllCoaches(false); setSelectedDelegateIds(new Set()); }}
            title={t("Switch trip")}
          >
            {tripOptions.map((tr) => (
              <option key={tr.id} value={tr.id}>{tr.name}</option>
            ))}
          </select>
        </div>
      )}

      {/* ---- Tabs ----------------------------------------------------------- */}
      <div className="row" style={{ gap: 8, marginTop: 18 }}>
        {perms.viewDelegates && (
          <button
            className="btn"
            onClick={() => setTab("delegate")}
            style={{
              background: tab === "delegate" ? "var(--scc-red-tint)" : "transparent",
              color: tab === "delegate" ? "var(--scc-red)" : "var(--ink-2)",
              border: `1px solid ${tab === "delegate" ? "var(--scc-red-tint-2)" : "var(--line)"}`,
            }}
          >
            {t("Delegate")}
          </button>
        )}
        {perms.viewAnalytics && (
          <button
            className="btn"
            onClick={() => setTab("analytics")}
            style={{
              background: tab === "analytics" ? "var(--scc-red-tint)" : "transparent",
              color: tab === "analytics" ? "var(--scc-red)" : "var(--ink-2)",
              border: `1px solid ${tab === "analytics" ? "var(--scc-red-tint-2)" : "var(--line)"}`,
            }}
          >
            <BarChart3 size={16} /> {t("Analytics")}
          </button>
        )}
        {perms.manageAccounts && (
          <button
            className="btn"
            onClick={() => setTab("staffops")}
            style={{
              background: tab === "staffops" ? "var(--scc-red-tint)" : "transparent",
              color: tab === "staffops" ? "var(--scc-red)" : "var(--ink-2)",
              border: `1px solid ${tab === "staffops" ? "var(--scc-red-tint-2)" : "var(--line)"}`,
            }}
          >
            <Radio size={16} /> {t("Staff operations")}
          </button>
        )}
      </div>

      {/* ---- Error banner (shared by both tabs) --------------------------- */}
      {error && (
        <div
          className="card"
          style={{ marginTop: 20, padding: 16, borderColor: "var(--st-missing)", background: "var(--st-missing-bg)" }}
        >
          <div className="row" style={{ gap: 10, color: "var(--st-missing)", fontWeight: 600 }}>
            <AlertTriangle size={18} /> {t("Couldn't reach the backend")}
          </div>
          <p className="muted" style={{ fontSize: 13, marginTop: 6 }}>
            {t(error)} — {t("make sure it’s running (")}<code>cd backend &amp;&amp; npm run dev</code>{t("), then hit Refresh.")}
          </p>
        </div>
      )}

      {loading && !data && (
        <div className="muted" style={{ marginTop: 24 }}>{t("Loading…")}</div>
      )}

      {tab === "analytics" && perms.viewAnalytics && (
        <div style={{ marginTop: 20 }}>
          <AnalyticsPanel data={data} missing={missing} delegates={delegates} />
        </div>
      )}

      {exportOpen && <ExportModal tripId={selectedTripId} onClose={() => setExportOpen(false)} />}

      {headcountOpen && (
        <div style={S.overlay} onClick={() => setHeadcountOpen(false)}>
          <div className="card" style={{ ...S.modal, width: "min(1000px, 100%)" }} onClick={(e) => e.stopPropagation()}>
            <div className="row between" style={{ marginBottom: 4 }}>
              <h2 style={{ fontSize: 17 }}>{t("Reverse headcount")}</h2>
              <button onClick={() => setHeadcountOpen(false)} style={S.iconBtn} aria-label={t("Close")}>
                <X size={18} />
              </button>
            </div>
            <p className="page-sub" style={{ margin: 0 }}>
              {t("Who's still missing, per coach — the same view staff see on the Check-in screen.")}
            </p>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 16, marginTop: 16 }}>
            {coaches.map((c) => {
              // "Missing" folds in LATE too (per the simplified status logic),
              // so this list shows everyone not yet accounted for — pulled from
              // the full delegate list since the `missing` array is MISSING-only.
              const coachMissing = delegates.filter((d) => d.coachId === c.id && (d.status === "MISSING" || d.status === "LATE"));
              const boardedPct = c.capacity ? Math.round((c.boarded / c.capacity) * 100) : 0;
              return (
                <div key={c.id} className="card" style={{ padding: 20 }}>
                  <div className="row between" style={{ alignItems: "flex-start" }}>
                    <div>
                      <div style={{ fontWeight: 600, fontSize: 15 }}>{coachDisplayName(c)}</div>
                      <div className="muted" style={{ fontSize: 12 }}>{c.boarded}/{c.capacity} {t("boarded")}</div>
                    </div>
                    {coachMissing.length === 0 ? (
                      <span className="badge badge-present">{t("Arrived")}</span>
                    ) : (
                      <span className="badge badge-missing">{coachMissing.length} {t("missing")}</span>
                    )}
                  </div>
                  <div style={S.track}>
                    <div style={{ ...S.fill, width: `${boardedPct}%`, background: coachMissing.length > 0 ? "var(--st-missing)" : "var(--st-present)" }} />
                  </div>

                  {coachMissing.length === 0 ? (
                    <div className="muted" style={{ fontSize: 13, marginTop: 14 }}>{t("Everyone on this coach is accounted for.")}</div>
                  ) : (
                    <div style={{ display: "flex", flexDirection: "column", gap: 10, marginTop: 14 }}>
                      {coachMissing.map((m) => (
                        <div key={m.id} className="row between" style={{ gap: 10 }}>
                          <div className="row" style={{ gap: 10, minWidth: 0 }}>
                            <DelegateAvatar delegate={m} style={{ flexShrink: 0 }} />
                            <div style={{ minWidth: 0 }}>
                              <div className="row" style={{ gap: 6 }}>
                                <span style={{ fontWeight: 500, fontSize: 13.5, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{m.name}</span>
                                {m.vip && <Crown size={13} color="var(--st-review)" style={{ flexShrink: 0 }} />}
                              </div>
                              {/* Everyone here is missing or late, so the subtitle is their
                                  last known location rather than a generic status label. */}
                              <div className="muted" style={{ fontSize: 12 }}>{m.lastLocation || t("Last known location")}</div>
                            </div>
                          </div>
                          {m.lastLocation && (
                            <button
                              onClick={() => setMapDelegate(m)}
                              aria-label={`${t("View location")} — ${m.name}`}
                              title={t("View location")}
                              style={{ ...S.iconBtn, color: "var(--st-missing)", flexShrink: 0 }}
                            >
                              <MapPin size={16} />
                            </button>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
            {coaches.length === 0 && (
              <div className="muted" style={{ fontSize: 14 }}>{t("No coaches for this trip yet.")}</div>
            )}
          </div>
          </div>
        </div>
      )}

      {tab === "staffops" && perms.manageAccounts && (
        <div style={{ marginTop: 20 }}>
          <p className="page-sub" style={{ margin: 0 }}>
            {t("Who's signed in right now, across the whole team.")}
          </p>

          {staffOpsError && (
            <div className="card" style={{ marginTop: 16, padding: 16, borderColor: "var(--st-missing)", background: "var(--st-missing-bg)" }}>
              <p style={{ fontSize: 13, color: "var(--st-missing)", fontWeight: 600 }}>{t(staffOpsError)}</p>
            </div>
          )}

          {!staffOps && !staffOpsError && (
            <div className="muted" style={{ marginTop: 24 }}>{t("Loading…")}</div>
          )}

          {staffOps && (
            <>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16, marginTop: 16 }}>
                <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column", gap: 10 }}>
                  <div className="row" style={{ gap: 8 }}>
                    <span style={{ ...S.iconBadge, background: "var(--st-present-bg)", color: "var(--st-present)" }}>
                      <Radio size={16} />
                    </span>
                    <span className="muted" style={{ fontSize: 13, fontWeight: 600 }}>{t("Active now")}</span>
                  </div>
                  <div style={{ fontSize: 30, fontWeight: 700 }}>{staffOps.activeCount}</div>
                </div>
                <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column", gap: 10 }}>
                  <div className="row" style={{ gap: 8 }}>
                    <span style={{ ...S.iconBadge, background: "var(--scc-red-tint)", color: "var(--scc-red)" }}>
                      <Users size={16} />
                    </span>
                    <span className="muted" style={{ fontSize: 13, fontWeight: 600 }}>{t("Total staff accounts")}</span>
                  </div>
                  <div style={{ fontSize: 30, fontWeight: 700 }}>{staffOps.totalStaff}</div>
                  {(staffOps.adminCount != null && staffOps.staffCount != null) && (
                    <div className="muted" style={{ fontSize: 13 }}>
                      {staffOps.adminCount} {t("Admin")} · {staffOps.staffCount} {t("Staff")}
                    </div>
                  )}
                </div>
              </div>

              <div className="card" style={{ marginTop: 16, padding: 20 }}>
                <h2 style={{ fontSize: 15, marginBottom: 14 }}>{t("Active sessions")}</h2>
                {staffOps.active.length === 0 ? (
                  <div className="muted" style={{ fontSize: 13 }}>{t("No one is currently active.")}</div>
                ) : (
                  <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                    {staffOps.active.map((acc) => (
                      <div key={acc.id} className="row between">
                        <div className="row" style={{ gap: 10 }}>
                          <span className="avatar" style={{ background: "var(--st-present-bg)", color: "var(--st-present)" }}>
                            {(acc.name || acc.username).trim().split(/\s+/).map((w) => w[0]).slice(0, 2).join("").toUpperCase()}
                          </span>
                          <div>
                            <div style={{ fontSize: 14, fontWeight: 500 }}>{acc.name || acc.username}</div>
                            <div className="muted" style={{ fontSize: 12 }}>
                              {t(acc.role ? acc.role.charAt(0).toUpperCase() + acc.role.slice(1) : "Staff")}
                            </div>
                          </div>
                        </div>
                        <div className="row" style={{ gap: 6 }}>
                          <span style={{ width: 7, height: 7, borderRadius: "50%", background: "var(--st-present)", flexShrink: 0 }} />
                          <span className="muted" style={{ fontSize: 12 }}>{staffOpsTimeAgo(acc.last_seen_at, t)}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </>
          )}
        </div>
      )}

      {tab === "delegate" && perms.viewDelegates && (
      <>
      {/* ---- KPI tiles ------------------------------------------------------
       * Missing + Late keep the full attention-grabbing tile treatment — they're
       * the two statuses that need someone to actually DO something. Arrived /
       * Assigned / Unassigned are calmer "where is everyone" counts, so they're
       * folded into one compact Roster breakdown card (a proportional bar +
       * 3 small stats) instead of 3 more full-size tiles — 5 equal-weight
       * cards in a row was reads as visual noise when only 2 of them are
       * actually urgent (2026-07-22 redesign, was a flat 5-tile kpi-grid).
       * ---------------------------------------------------------------------- */}
      {k && (
        <div className="kpi-row">
          <Kpi tone="missing" icon={AlertTriangle} label={t("Missing right now")} value={`${k.missing}`}
            suffix={`${t("of")} ${k.total}`} foot={trip ? `${t("Departure in")} ${trip.departsIn}` : null} big
            onClick={() => showDelegatesFiltered("MISSING")} />
          <Kpi tone="late" icon={Clock} label={t("Late")} value={`${k.late ?? 0}`}
            foot={t("Past cut-off, not checked in")}
            onClick={() => showDelegatesFiltered("LATE")} />
          <RosterCard t={t} k={k} onFilter={showDelegatesFiltered} />
        </div>
      )}

      {/* ---- Coach status + Live activity -------------------------------- */}
      {data && (
        <div className="dash-two-col" style={S.twoCol}>
          <div className="card" style={{ padding: 22, display: "flex", flexDirection: "column" }}>
            <div className="row between" style={{ marginBottom: 16 }}>
              <h2 style={{ fontSize: 16 }}>{t("Coach status")}</h2>
              <div className="row" style={{ gap: 10 }}>
                <span className="muted" style={{ fontSize: 13 }}>{coaches.length} {t("coaches")}</span>
                <button
                  className="btn btn-ghost"
                  style={{ padding: "4px 10px", fontSize: 12.5 }}
                  onClick={() => setHeadcountOpen(true)}
                  title={t("Who's still missing, per coach — the same view staff see on the Check-in screen.")}
                >
                  <Users size={13} /> {t("More details")}
                </button>
              </div>
            </div>
            {coaches.length === 0 ? (
              <div className="muted" style={{ fontSize: 13 }}>{t("No coaches for this trip yet.")}</div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
                {(showAllCoaches ? coaches : coaches.slice(0, COACH_TOP_N)).map((c) => (
                  <CoachBar key={c.id} coach={c} onOpen={currentTripUuid ? openCoachBoard : undefined} />
                ))}
              </div>
            )}
            {coaches.length > COACH_TOP_N && (
              <div style={{ marginTop: "auto", paddingTop: 16, textAlign: "center" }}>
                <button className="btn btn-ghost" onClick={() => setShowAllCoaches((v) => !v)}>
                  {showAllCoaches ? t("Show less") : `${t("Show all")} ${coaches.length}`}
                </button>
              </div>
            )}
          </div>

          <div className="card" style={{ padding: 22, display: "flex", flexDirection: "column" }}>
            <div className="row between" style={{ marginBottom: 16 }}>
              <div className="row" style={{ gap: 8 }}>
                <Activity size={18} color="var(--ink-3)" />
                <h2 style={{ fontSize: 16 }}>{t("History tracker")}</h2>
              </div>
              <div className="row" style={{ gap: 8 }}>
                <button
                  className="btn btn-ghost"
                  style={{ padding: "4px 10px", fontSize: 12.5 }}
                  onClick={() => navigate("/history")}
                  title={t("Open the full date-stamped audit log")}
                >
                  <ChevronRight size={13} /> {t("View full log")}
                </button>
                {perms.manageDelegates && history.length > 0 && (
                  <button className="btn btn-ghost" style={{ padding: "4px 10px", fontSize: 12.5 }} onClick={clearHistory}>
                    <Trash2 size={13} /> {t("Clear all")}
                  </button>
                )}
              </div>
            </div>
            {history.length === 0 ? (
              <div className="muted" style={{ fontSize: 13 }}>
                {t("No activity yet. Add or update a delegate to see events here.")}
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: 14, maxHeight: 360, overflowY: "auto", paddingRight: 4 }}>
                {history.map((a) => (
                  <div key={a.id} className="row between" style={{ gap: 12, alignItems: "flex-start", flexShrink: 0 }}>
                    <div className="row" style={{ gap: 12, alignItems: "flex-start" }}>
                      <span style={{ ...S.dot, background: activityColor(a.kind), marginTop: 6 }} />
                      <div>
                        <div style={{ fontSize: 14 }}>{translateActivityText(a.text, t)}</div>
                        <div className="muted" style={{ fontSize: 12 }}>{a.time} · {a.via === "you" ? t("you") : a.via}</div>
                      </div>
                    </div>
                    {perms.manageDelegates && (
                      <button onClick={() => removeHistoryEntry(a.id)} aria-label="Delete" style={{ ...S.iconBtn, color: "var(--st-missing)" }}>
                        <Trash2 size={14} />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ---- All delegates (CRUD surface) -------------------------------- */}
      {data && (
        <div ref={delegateTableRef} className="card" style={{ marginTop: 20, overflow: "hidden" }}>
          <div className="row between" style={{ padding: "18px 20px", borderBottom: "1px solid var(--line)" }}>
            <div>
              <h2 style={{ fontSize: 16 }}>{t("All delegates")}</h2>
              <p className="muted" style={{ fontSize: 13, marginTop: 2 }}>
                {t("Create, edit, and remove attendance records")}
              </p>
            </div>
            <div className="row" style={{ gap: 10 }}>
              {perms.manageDelegates && selectedDelegateIds.size > 0 && (
                <button
                  className="btn btn-ghost"
                  style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }}
                  onClick={deleteSelectedDelegates}
                  disabled={deletingSelectedDelegates}
                >
                  <Trash2 size={16} /> {deletingSelectedDelegates ? t("Deleting…") : `${t("Delete selected")} (${selectedDelegateIds.size})`}
                </button>
              )}
              {perms.manageDelegates && delegates.length > 0 && (
                <button className="btn btn-ghost" style={{ color: "var(--st-missing)", borderColor: "var(--st-missing-bg)" }} onClick={deleteAll}>
                  <Trash2 size={16} /> {t("Delete all")}
                </button>
              )}
              {perms.manageDelegates && (
                <button className="btn btn-primary" onClick={openCreate}>
                  <Plus size={16} /> {t("Add delegate")}
                </button>
              )}
            </div>
          </div>

          {delegates.length > 0 && (
            <div className="row" style={{ gap: 10, padding: "12px 20px", borderBottom: "1px solid var(--line)", flexWrap: "wrap" }}>
              <input
                className="input"
                style={{ maxWidth: 240, flex: "1 1 180px" }}
                placeholder={t("Search delegates…")}
                value={delegateQuery}
                onChange={(e) => setDelegateQuery(e.target.value)}
              />
              <select className="select" style={{ maxWidth: 170 }} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>
                <option value="ALL">{t("All statuses")}</option>
                <option value="UNASSIGNED">{t("Unassigned")}</option>
                <option value="ASSIGNED">{t("Assigned")}</option>
                <option value="ARRIVED">{t("Arrived")}</option>
                <option value="LATE">{t("Late")}</option>
                <option value="MISSING">{t("Missing")}</option>
              </select>
              {/* Coach-assignment filter — matches the mobile Attendance
                  page's coach filter. Options come from the live coach list
                  plus an explicit "Unassigned" (delegates with no coach). */}
              <select className="select" style={{ maxWidth: 190 }} value={coachFilter} onChange={(e) => setCoachFilter(e.target.value)}>
                <option value="ALL">{t("All coaches")}</option>
                {coaches.map((c) => (
                  <option key={c.id} value={c.id}>{coachDisplayName(c)}</option>
                ))}
                <option value="UNASSIGNED">{t("Unassigned")}</option>
              </select>
              <select className="select" style={{ maxWidth: 190 }} value={sortMode} onChange={(e) => setSortMode(e.target.value)}>
                <option value="name">{t("Sort: Name")}</option>
                <option value="recent">{t("Sort: Recently added")}</option>
                <option value="status">{t("Sort: Status")}</option>
                <option value="coach">{t("Sort: Coach")}</option>
              </select>
            </div>
          )}

          {delegates.length === 0 ? (
            <div className="muted" style={{ padding: 24, fontSize: 14 }}>
              {t("No delegates yet. Click")} <strong>{t("Add delegate")}</strong> {t("to create your first record.")}
            </div>
          ) : (
            <table className="table">
              <thead>
                <tr>
                  {perms.manageDelegates && (
                    <th style={{ width: 36 }}>
                      <input
                        type="checkbox"
                        checked={rowsShown.length > 0 && rowsShown.every((d) => selectedDelegateIds.has(d.id))}
                        onChange={() => setSelectedDelegateIds((prev) => {
                          const allChecked = rowsShown.length > 0 && rowsShown.every((d) => prev.has(d.id));
                          return allChecked ? new Set() : new Set(rowsShown.map((d) => d.id));
                        })}
                        disabled={rowsShown.length === 0}
                        aria-label={t("Select all")}
                      />
                    </th>
                  )}
                  <th>{t("Delegate")}</th><th>{t("Coach")}</th><th>{t("Status")}</th><th>{t("Last seen")}</th><th>{t("Uploaded")}</th><th>{t("Created by")}</th>
                  <th style={{ width: 90 }} />
                </tr>
              </thead>
              <tbody>
                {rowsShown.map((d) => (
                  <tr key={d.id}>
                    {perms.manageDelegates && (
                      <td>
                        <input
                          type="checkbox"
                          checked={selectedDelegateIds.has(d.id)}
                          onChange={() => toggleDelegateSelected(d.id)}
                          aria-label={`${t("Select")} ${d.name}`}
                        />
                      </td>
                    )}
                    <td>
                      <div className="row" style={{ gap: 10 }}>
                        <DelegateAvatar delegate={d} />
                        <span style={{ fontWeight: 500 }}>{d.name}</span>
                        {d.vip && (
                          <span className="badge badge-review" style={{ padding: "2px 8px" }}>
                            <Crown size={12} /> {t("VIP")}
                          </span>
                        )}
                      </div>
                    </td>
                    <td>{coachName(d.coachId)}</td>
                    <td><StatusBadge state={d.status} /></td>
                    <td className="muted">{d.status === "MISSING" ? (d.lastSeen || "—") : "—"}</td>
                    <td className="muted">{fmtUploadDate(d.createdAt)}</td>
                    <td className="muted">{d.createdBy || "—"}</td>
                    <td>
                      <div className="row" style={{ gap: 6 }}>
                        <button
                          onClick={() => d.status === "MISSING" && setMapDelegate(d)}
                          disabled={d.status !== "MISSING"}
                          aria-label={`${t("View location")} — ${d.name}`}
                          title={d.status === "MISSING" ? t("View location") : t("Only available while a delegate is Missing")}
                          style={{
                            ...S.iconBtn,
                            color: d.status === "MISSING" ? "var(--st-missing)" : "var(--ink-3)",
                            opacity: d.status === "MISSING" ? 1 : 0.35,
                            cursor: d.status === "MISSING" ? "pointer" : "not-allowed",
                          }}>
                          <MapPin size={16} />
                        </button>
                        {perms.manageDelegates && (
                          <>
                            <button onClick={() => openEdit(d)} aria-label={`${t("Edit")} ${d.name}`}
                              style={S.iconBtn}>
                              <Pencil size={16} />
                            </button>
                            <button onClick={() => remove(d)} aria-label={`${t("Delete")} ${d.name}`}
                              style={{ ...S.iconBtn, color: "var(--st-missing)" }}>
                              <Trash2 size={16} />
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
                {visibleDelegates.length === 0 && (
                  <tr>
                    <td colSpan={perms.manageDelegates ? 8 : 7} className="muted" style={{ padding: 24, fontSize: 14, textAlign: "center" }}>
                      {t("No delegates match your filters.")}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          )}
          {visibleDelegates.length > TOP_N && (
            <div style={{ padding: "12px 20px", borderTop: "1px solid var(--line)", textAlign: "center" }}>
              <button className="btn btn-ghost" onClick={() => setShowAllDelegates((v) => !v)}>
                {showAllDelegates ? t("Show less") : `${t("Show all")} ${visibleDelegates.length}`}
              </button>
            </div>
          )}
        </div>
      )}

      {/* ---- Create / Edit modal ----------------------------------------- */}
      {modalOpen && (
        <div style={S.overlay} onClick={() => !saving && setModalOpen(false)}>
          <div className="card" style={S.modal} onClick={(e) => e.stopPropagation()}>
            <div className="row between" style={{ marginBottom: 18 }}>
              <h2 style={{ fontSize: 18 }}>{editingId ? t("Edit delegate") : t("Add delegate")}</h2>
              <button onClick={() => setModalOpen(false)} style={S.iconBtn} aria-label={t("Close")}>
                <X size={18} />
              </button>
            </div>

            {editingId && (
              <div className="row" style={{ gap: 14, marginBottom: 18 }}>
                {/* Status-toned across all 5 states via the shared statusTone()
                    helper (DelegateAvatar.jsx) — was MISSING-vs-everyone-else
                    binary, so an Unassigned/Assigned/Late delegate's header
                    all showed the same green as Arrived. */}
                {editingPhotoUrl ? (
                  <img src={editingPhotoUrl} alt="" style={{ width: 56, height: 56, borderRadius: "50%", objectFit: "cover", flexShrink: 0, boxShadow: `0 0 0 2px ${statusTone(form.status).fg}` }} />
                ) : (
                  <span
                    className="avatar"
                    style={{
                      width: 56, height: 56, fontSize: 20,
                      background: statusTone(form.status).bg,
                      color: statusTone(form.status).fg,
                      boxShadow: `inset 0 0 0 1.5px ${statusTone(form.status).fg}`,
                    }}
                  >
                    {form.name.trim().split(/\s+/).map((w) => w[0]).slice(0, 2).join("").toUpperCase() || "?"}
                  </span>
                )}
                <div>
                  <label className="btn btn-ghost" style={{ cursor: "pointer", display: "inline-flex" }}>
                    {photoBusy ? t("Saving…") : t("Upload photo")}
                    <input
                      type="file"
                      accept="image/*"
                      disabled={photoBusy}
                      style={{ display: "none" }}
                      onChange={(e) => { handlePhotoChange(e.target.files?.[0]); e.target.value = ""; }}
                    />
                  </label>
                  {editingPhotoUrl && (
                    <button className="btn btn-ghost" style={{ marginLeft: 8, color: "var(--st-missing)" }} disabled={photoBusy} onClick={handleRemovePhoto}>
                      {t("Remove")}
                    </button>
                  )}
                  {photoErr && <div style={{ fontSize: 12, color: "var(--st-missing)", marginTop: 6 }}>{t(photoErr)}</div>}
                </div>
              </div>
            )}

            <label className="field-label">{t("Full name")}</label>
            <input className="input" autoFocus value={form.name}
              placeholder={t("e.g. Lim Wei Jie")}
              onChange={(e) => setForm({ ...form, name: e.target.value })} />

            <label className="field-label" style={{ marginTop: 14 }}>{t("Status")}</label>
            <select className="select" value={form.status}
              onChange={(e) => setForm({ ...form, status: e.target.value })}>
              <option value="UNASSIGNED">{t("Unassigned")}</option>
              <option value="ASSIGNED">{t("Assigned")}</option>
              <option value="ARRIVED">{t("Arrived")}</option>
              <option value="LATE">{t("Late")}</option>
              <option value="MISSING">{t("Missing")}</option>
            </select>

            <label className="field-label" style={{ marginTop: 14 }}>
              {t("Coach")} {form.status !== "UNASSIGNED" && <span className="muted">({t("required")})</span>}
            </label>
            <select className="select" value={form.coachId}
              disabled={form.status === "UNASSIGNED"}
              onChange={(e) => setForm({ ...form, coachId: e.target.value })}>
              <option value="">{form.status === "UNASSIGNED" ? t("No coach (unassigned)") : t("Select a coach…")}</option>
              {coaches.map((c) => (
                <option key={c.id} value={c.id}>{coachDisplayName(c)}</option>
              ))}
            </select>

            {form.status === "MISSING" && (
              <>
                <label className="field-label" style={{ marginTop: 14 }}>{t("Last seen (optional)")}</label>
                <input className="input" value={form.lastSeen}
                  placeholder={t("e.g. Lobby · 14:08")}
                  onChange={(e) => setForm({ ...form, lastSeen: e.target.value })} />

                <label className="field-label" style={{ marginTop: 14 }}>
                  {t("Last known location")} <span className="muted">({t("required")})</span>
                </label>
                <input className="input" value={form.lastLocation}
                  placeholder={t("e.g. Novotel Beijing Sanyuan, Lobby")}
                  onChange={(e) => setForm({ ...form, lastLocation: e.target.value })} />
                {form.lastLocation.trim() && (
                  <div style={{ marginTop: 8 }}>
                    <DelegateLocationMap location={form.lastLocation.trim()} height={160} />
                  </div>
                )}
              </>
            )}

            <label className="row" style={{ gap: 8, marginTop: 16, fontSize: 14, cursor: "pointer" }}>
              <input type="checkbox" checked={form.vip}
                onChange={(e) => setForm({ ...form, vip: e.target.checked })} />
              {t("Mark as VIP")}
            </label>

            <button
              type="button"
              onClick={() => setShowMoreFields((v) => !v)}
              className="row"
              style={{ gap: 6, marginTop: 16, background: "none", border: "none", padding: 0, cursor: "pointer", color: "var(--scc-red)", fontSize: 13, fontWeight: 600 }}
            >
              <ChevronRight size={15} style={{ transform: showMoreFields ? "rotate(90deg)" : "none", transition: "transform 0.15s" }} />
              {t("More details")}
            </button>

            {showMoreFields && (
              <div style={{ marginTop: 12, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                <div>
                  <label className="field-label">{t("Role")}</label>
                  <input className="input" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Company")}</label>
                  <input className="input" value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Industry")}</label>
                  <input className="input" value={form.industry} onChange={(e) => setForm({ ...form, industry: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Nationality")}</label>
                  <input className="input" value={form.nationality} onChange={(e) => setForm({ ...form, nationality: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Email")}</label>
                  <input className="input" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Phone")}</label>
                  <input className="input" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Website")}</label>
                  <input className="input" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Passport number")}</label>
                  <input className="input mono" value={form.passportNumber} onChange={(e) => setForm({ ...form, passportNumber: e.target.value })} />
                </div>
                <div>
                  <label className="field-label">{t("Passport expiry")}</label>
                  <input className="input" type="date" value={form.passportExpiry} onChange={(e) => setForm({ ...form, passportExpiry: e.target.value })} />
                </div>
                <div style={{ gridColumn: "1 / -1" }}>
                  <label className="field-label">{t("Accessibility notes")}</label>
                  <input className="input" value={form.accessibilityNotes} onChange={(e) => setForm({ ...form, accessibilityNotes: e.target.value })} />
                </div>
                <div style={{ gridColumn: "1 / -1" }}>
                  <label className="field-label">{t("Notes")}</label>
                  <textarea className="input" rows={2} style={{ resize: "vertical", fontFamily: "inherit" }}
                    value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} />
                </div>
              </div>
            )}

            {formErr && (
              <div style={{
                display: "flex", alignItems: "center", gap: 8, marginTop: 16, padding: "10px 12px",
                background: "var(--st-missing-bg)", color: "var(--st-missing)", borderRadius: "var(--r-sm)",
                fontSize: 13, fontWeight: 600,
              }}>
                {t(formErr)}
              </div>
            )}

            <div className="row" style={{ gap: 10, marginTop: 24, justifyContent: "flex-end" }}>
              <button className="btn btn-ghost" onClick={() => setModalOpen(false)} disabled={saving}>
                {t("Cancel")}
              </button>
              <button className="btn btn-primary" onClick={saveForm} disabled={saving || !form.name.trim()}>
                {saving ? t("Saving…") : editingId ? t("Save changes") : t("Add delegate")}
              </button>
            </div>
          </div>
        </div>
      )}
      </>
      )}

      {mapDelegate && (
        <div style={S.overlay} onClick={() => setMapDelegate(null)}>
          <div className="card" style={{ ...S.modal, width: "min(480px, 100%)" }} onClick={(e) => e.stopPropagation()}>
            <div className="row between" style={{ marginBottom: 14 }}>
              <div>
                <h2 style={{ fontSize: 16 }}>{mapDelegate.name}</h2>
                <p className="muted" style={{ fontSize: 12, marginTop: 2 }}>{mapDelegate.lastLocation}</p>
              </div>
              <button onClick={() => setMapDelegate(null)} style={S.iconBtn} aria-label={t("Close")}>
                <X size={18} />
              </button>
            </div>
            {mapDelegate.lastLocation ? (
              <DelegateLocationMap location={mapDelegate.lastLocation} height={280} />
            ) : (
              <div className="muted" style={{ fontSize: 13, padding: "12px 0" }}>
                {t("No location has been recorded for this delegate yet.")}
              </div>
            )}
          </div>
        </div>
      )}

      <style>{`.spin{animation:mg-spin 0.9s linear infinite}@keyframes mg-spin{to{transform:rotate(360deg)}}
        /* 4 equal columns at a fixed width, not auto-fit — auto-fit's minmax
           boundaries produce an uneven trailing gap/card width depending on
           exactly how many columns fit, which is what read as "unaligned".
           Explicit breakpoints instead of a fluid track keep every card the
           same size as its row-mates at every width. */
        .kpi-row{display:grid;grid-template-columns:1fr 1fr 2fr;gap:16px;margin-top:22px;align-items:stretch}
        .kpi-row > *{min-height:132px}
        @media (max-width:960px){.kpi-row{grid-template-columns:1fr 1fr;}.kpi-row > :last-child{grid-column:1 / -1}}
        @media (max-width:560px){.kpi-row{grid-template-columns:1fr}.kpi-row > :last-child{grid-column:auto}}
        .roster-bar{display:flex;height:8px;border-radius:999px;overflow:hidden;background:var(--surface-2)}
        .roster-bar > span{height:100%}
        .roster-stats{display:flex;gap:0;margin-top:14px;flex:1}
        .roster-stat{flex:1;display:flex;flex-direction:column;gap:2px;padding:0 14px;border:none;background:none;cursor:pointer;text-align:left}
        .roster-stat + .roster-stat{border-left:1px solid var(--line)}
        .roster-stat:first-child{padding-left:0}
        .kpi-clickable{transition:box-shadow .15s ease,border-color .15s ease,transform .15s ease}
        /* Hover/focus color now matches each card's OWN status tone (--kpi-tone,
           set inline per card) instead of a hardcoded var(--st-normal) — that
           hardcode was a leftover from when this hover style was written for
           the old single purple "Open exceptions" tile, so every OTHER card
           (including Late) inherited that same purple on hover regardless of
           its actual color. */
        .kpi-clickable:hover{box-shadow:var(--shadow-md);border-color:var(--kpi-tone);transform:translateY(-1px)}
        .kpi-clickable:focus-visible{outline:2px solid var(--kpi-tone);outline-offset:2px}`}</style>
    </div>
  );
}

/* ---- KPI tile ----------------------------------------------------------- */
function Kpi({ tone, icon: Icon, label, value, suffix, foot, big, onClick }) {
  const clickable = !!onClick;
  return (
    <div
      className={"card" + (clickable ? " kpi-clickable" : "")}
      onClick={onClick}
      role={clickable ? "button" : undefined}
      tabIndex={clickable ? 0 : undefined}
      onKeyDown={clickable ? (e) => (e.key === "Enter" || e.key === " ") && (e.preventDefault(), onClick()) : undefined}
      style={{
        padding: 20, display: "flex", flexDirection: "column", gap: 10, cursor: clickable ? "pointer" : undefined,
        "--kpi-tone": `var(--st-${tone})`,
      }}
    >
      <div className="row between">
        <span className="page-eyebrow" style={{ color: `var(--st-${tone})` }}>{label}</span>
        <Icon size={18} color={`var(--st-${tone})`} />
      </div>
      <div className="row" style={{ alignItems: "baseline", gap: 8 }}>
        <span className="mono"
          style={{ fontSize: big ? 44 : 40, fontWeight: 700, color: `var(--st-${tone})`, lineHeight: 1 }}>
          {value}
        </span>
        {suffix && <span className="muted" style={{ fontSize: 16 }}>{suffix}</span>}
      </div>
      {foot && <div className="muted" style={{ fontSize: 13 }}>{foot}</div>}
    </div>
  );
}

/* ---- Roster breakdown card -----------------------------------------------
 * Folds Arrived / Assigned / Unassigned into one card: a proportional stacked
 * bar (share of the roster in each status) plus 3 compact clickable stats —
 * the calmer counts don't need a full KPI tile each like Missing/Late do. */
function RosterCard({ t, k, onFilter }) {
  const segments = [
    { tone: "present", value: k.present },
    { tone: "assigned", value: k.assigned ?? 0 },
    { tone: "unassigned", value: k.unassigned },
  ];
  const total = Math.max(k.total, 1); // guard div-by-zero on an empty roster

  return (
    <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column" }}>
      <span className="page-eyebrow" style={{ color: "var(--ink-3)" }}>{t("Roster breakdown")}</span>
      <div className="roster-bar" style={{ marginTop: 12 }}>
        {segments.map((s) => s.value > 0 && (
          <span key={s.tone} style={{ width: `${(s.value / total) * 100}%`, background: `var(--st-${s.tone})` }} />
        ))}
      </div>
      <div className="roster-stats">
        <RosterStat tone="present" icon={UserCheck} label={t("Arrived")} value={k.present} onClick={() => onFilter("ARRIVED")} />
        <RosterStat tone="assigned" icon={Users} label={t("Assigned")} value={k.assigned ?? 0} onClick={() => onFilter("ASSIGNED")} />
        <RosterStat tone="unassigned" icon={HelpCircle} label={t("Unassigned")} value={k.unassigned} onClick={() => onFilter("UNASSIGNED")} />
      </div>
    </div>
  );
}

function RosterStat({ tone, icon: Icon, label, value, onClick }) {
  return (
    <button className="roster-stat" onClick={onClick}>
      <span className="row" style={{ gap: 6, color: `var(--st-${tone})` }}>
        <Icon size={14} />
        <span className="muted" style={{ fontSize: 12.5, color: "var(--ink-2)" }}>{label}</span>
      </span>
      <span className="mono" style={{ fontSize: 24, fontWeight: 700, color: `var(--st-${tone})`, lineHeight: 1.2 }}>{value}</span>
    </button>
  );
}

/* ---- Coach display helpers ----------------------------------------------
 * Coaches added outside the original seed may have no city, or a long label
 * ("Coach 5" instead of "C5") — never render "null" or overflow the avatar.
 * ------------------------------------------------------------------------- */
function coachDisplayName(c) {
  return [c.name, c.city].filter(Boolean).join(" · ");
}

function coachShortLabel(c) {
  if (c.label && c.label.length <= 3) return c.label;
  const num = String(c.label || c.name || "").match(/\d+/);
  return num ? `C${num[0]}` : String(c.label || c.name || "?").slice(0, 2).toUpperCase();
}

/** Format a delegate's upload timestamp (createdAt) as e.g. "12 Jul, 14:30".
 *  Older rows created before the column existed still get the migration time,
 *  so this only shows "—" if the value is genuinely missing/unparseable. */
function fmtUploadDate(v) {
  if (!v) return "—";
  const d = new Date(v);
  if (isNaN(d)) return "—";
  return d.toLocaleString([], { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
}

/** "Staff operations" active-sessions relative time, e.g. "15s ago" / "2m ago". */
function staffOpsTimeAgo(iso, t) {
  if (!iso) return "";
  const secs = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (secs < 10) return t("just now");
  if (secs < 60) return `${secs}${t("s ago")}`;
  return `${Math.round(secs / 60)}${t("m ago")}`;
}

/* ---- Coach progress bar -------------------------------------------------
 * When onOpen is provided the whole row is clickable and navigates to that
 * trip's board on the Trips (Desmond) page.
 * ------------------------------------------------------------------------- */
function CoachBar({ coach, onOpen }) {
  const { t } = useLang();
  const pct = coach.capacity ? Math.round((coach.boarded / coach.capacity) * 100) : 0;
  // Simplified two-state headline (per request): a coach is "Missing" if it
  // holds ANYONE not yet accounted for — LATE is folded in with MISSING, no
  // separate Late badge — and "Arrived" only when everyone assigned has
  // actually boarded. `attention` is that combined not-here count.
  const attention = (coach.missing || 0) + (coach.late || 0);
  const allArrived = coach.total > 0 && attention === 0 && coach.boarded === coach.total;
  const barColor = attention > 0 ? "var(--st-missing)" : "var(--st-present)";
  const clickable = !!onOpen;
  return (
    <div
      onClick={onOpen}
      role={clickable ? "button" : undefined}
      title={clickable ? t("Open in Trips board") : undefined}
      style={clickable ? { cursor: "pointer", borderRadius: "var(--r-sm)", padding: 6, margin: -6 } : undefined}
      className={clickable ? "coach-row" : undefined}
    >
      <div className="row between" style={{ marginBottom: 6 }}>
        <div className="row" style={{ gap: 10 }}>
          <span className="avatar" style={{ background: "var(--st-neutral-bg)", color: "var(--ink-2)" }}>
            {coachShortLabel(coach)}
          </span>
          <span style={{ fontWeight: 500, fontSize: 14 }}>{coachDisplayName(coach)}</span>
        </div>
        <div className="row" style={{ gap: 6 }}>
          {attention > 0 ? (
            <span className="badge badge-missing">{attention} {t("missing")}</span>
          ) : allArrived ? (
            <span className="badge badge-present">{t("Arrived")}</span>
          ) : coach.total > 0 ? (
            <span className="badge badge-neutral">{coach.total - coach.boarded} {t("to board")}</span>
          ) : (
            <span className="badge badge-neutral">{t("Empty")}</span>
          )}
          {clickable && <ChevronRight size={16} className="muted" />}
        </div>
      </div>
      <div style={S.track}>
        <div style={{ ...S.fill, width: `${pct}%`, background: barColor }} />
      </div>
      <div className="muted mono" style={{ fontSize: 12, marginTop: 4 }}>
        {coach.boarded}/{coach.capacity} {t("boarded")}
      </div>
    </div>
  );
}

/** Activity text comes from the backend as plain English ("Lim added",
 *  "All delegates removed (3)"), since it's stored as-is in the log. Rebuild
 *  it with the translated verb rather than adding a whole new API shape. */
function translateActivityText(text, t) {
  const allMatch = text.match(/^All delegates removed \((\d+)\)$/);
  if (allMatch) return `${t("All delegates removed")} (${allMatch[1]})`;
  const verbMatch = text.match(/^(.*) (added|updated|removed)$/);
  if (verbMatch) return `${verbMatch[1]} ${t(verbMatch[2])}`;
  return text;
}

function activityColor(kind) {
  if (kind === "exception") return "var(--st-missing)";
  if (kind === "reassign") return "var(--st-unassigned)";
  return "var(--st-present)";
}

/* ---- Local styles ------------------------------------------------------- */
const S = {
  dot: { width: 10, height: 10, borderRadius: 999, background: "var(--st-present)", display: "inline-block", flexShrink: 0 },
  twoCol: { display: "grid", gridTemplateColumns: "1.3fr 1fr", gap: 16, marginTop: 20 },
  track: { height: 8, borderRadius: 999, background: "var(--line)", overflow: "hidden" },
  fill: { height: "100%", borderRadius: 999, transition: "width 0.4s ease" },
  iconBtn: { background: "none", border: "none", color: "var(--ink-3)", display: "flex", padding: 4, borderRadius: 6 },
  overlay: { position: "fixed", inset: 0, background: "rgba(16,24,40,0.45)", display: "grid", placeItems: "center", padding: 20, zIndex: 50 },
  modal: { width: "min(440px, 100%)", maxHeight: "calc(100vh - 48px)", overflowY: "auto", padding: 24, background: "var(--surface)" },
  iconBadge: { width: 32, height: 32, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
};
