/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Trip Announcements
 *
 *  TEAMMATES: please DO NOT edit this file. Add your OWN feature files
 *  instead — see README/INTEGRATION_NOTES.md at the project root.
 * ============================================================================= */
/**
 * Trip Announcements — its own dedicated page (2026-07-26), not a Dashboard
 * widget: "make it a separate page where I click on sidebar, then it should
 * follow the trip ongoing itinerary." Reads/writes GET|POST /api/trips/:id/
 * announcements and DELETE /api/announcements/:id (routes/announcements.js).
 *
 * "Follow the trip itinerary" — each announcement can optionally tag a
 * specific itinerary stop (Day N · stop name · time) when posted; the page
 * groups the feed under that stop instead of one flat list, with a
 * "General" section up top for trip-wide notices with no specific stop.
 * Reuses the SAME trip-switcher localStorage key as DashboardPage.jsx (see
 * its DASHBOARD_TRIP_KEY comment) so both pages always track the same
 * "currently viewing" trip — switch it on either page, the other follows.
 *
 * Posting/editing/deleting requires the "manageAnnouncements" action
 * permission (2026-07-27 — Admin always has it, Staff needs it granted per-
 * account); viewing is any signed-in account with "viewAnnouncements"
 * (defaults true — see permissions.js).
 */
import { useEffect, useRef, useState } from "react";
import { Megaphone, Plus, X, Clock, ImagePlus, Video, ChevronLeft, ChevronRight } from "lucide-react";
import { apiGet, apiDelete, getPermissions, getToken } from "../../../lib/api.js";
import { useLang } from "../../../lib/i18n.jsx";
import { markAnnouncementsSeenNow } from "../../../lib/announcements/announcementsSeen.js";
import { useVisiblePolling } from "../../../lib/useVisiblePolling.js";
// Modularization pass (2026-08-02) — see pages/desktop/announcements/ for
// what used to be defined inline in this file.
import { AnnouncementCard, AnnouncementDetailModal } from "./AnnouncementCard.jsx";
// getActiveTripId/setActiveTripId aliased to this file's original local names
// (2026-08-02 modularization pass) — was a byte-for-byte duplicate of
// DashboardPage.jsx's OWN former duplicate of lib/activeTrip.js (same storage
// key "mg_dashboard_trip", same fallback "t-1"), except this copy never
// dispatched ACTIVE_TRIP_EVENT — so switching trips here silently didn't
// notify the floating ChatBubble the way switching on Dashboard already did.
// Using the shared helper fixes that inconsistency for free.
import { getActiveTripId as loadSelectedTripId, setActiveTripId as saveSelectedTripId } from "../../../lib/activeTrip.js";

const API_BASE = import.meta.env.VITE_API_URL || "/api";
const MAX_IMAGES = 6; // mirrors backend's routes/announcements.js MAX_IMAGES
const MAX_VIDEOS = 2; // mirrors backend's routes/announcements.js MAX_VIDEOS
const TRIP_ID = "t-1"; // fallback trip id (mirrors lib/activeTrip.js's own private default)

export default function AnnouncementsPage() {
  const { t } = useLang();
  const perms = getPermissions();
  const canManage = !!perms.manageAnnouncements;

  const [selectedTripId, setSelectedTripId] = useState(loadSelectedTripId);
  const [trips, setTrips] = useState([]);
  const [trip, setTrip] = useState(null);

  const [announcements, setAnnouncements] = useState([]);
  const [itineraryDays, setItineraryDays] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [formOpen, setFormOpen] = useState(false);
  // Day tabs (2026-07-26 — "put tab for day 1,2,3,4 instead of scrolling
  // down") — a multi-day trip used to stack every day's announcements in one
  // long scroll; now only the selected day (or "General") renders at a time.
  const [activeSection, setActiveSection] = useState(null); // "general" | "day-<N>"
  const [form, setForm] = useState({ title: "", message: "", itineraryItemId: "" });
  // Edit support (2026-07-27, "give me the option to edit the announcement")
  // — null means the modal is creating a new post; an id means it's editing
  // that one instead (openEdit() below prefills everything).
  const [editingId, setEditingId] = useState(null);
  // Multi-image support (2026-07-27, "give me multiple image upload option")
  // — `existingImages` is the array already saved on the announcement being
  // edited (empty when creating); `removedPublicIds` marks which of those the
  // user wants dropped on save; `newImages` are freshly picked files not
  // uploaded yet, each with its own local preview URL.
  const [existingImages, setExistingImages] = useState([]);
  const [removedPublicIds, setRemovedPublicIds] = useState(new Set());
  const [newImages, setNewImages] = useState([]); // [{file, previewUrl}]
  // Video support (2026-07-27, "give me... video upload also") — same
  // existing/removed/new shape as images, just its own separate arrays since
  // they upload to a different backend field/limit.
  const [existingVideos, setExistingVideos] = useState([]);
  const [removedVideoPublicIds, setRemovedVideoPublicIds] = useState(new Set());
  const [newVideos, setNewVideos] = useState([]); // [{file, previewUrl}]
  const [saving, setSaving] = useState(false);
  const [saveErr, setSaveErr] = useState(null);
  // Lightbox (2026-07-27, "give me option to enlarge the photo when click"/
  // "when click can view the video") — a single overlay that shows either an
  // image or a video full-size; `kind` picks which element to render.
  //
  // Holds the WHOLE media list plus a cursor, not just the one item clicked
  // (2026-07-29 — "allow me to click arrow button when in enlarge mode to
  // navigate"): stepping between photos needs to know what the neighbours are,
  // and a post can mix images and videos, so both live in one flat list in the
  // order they appear on the card.
  const [viewer, setViewer] = useState(null); // { items: [{kind,url}], index }
  const openViewer = (items, index) => setViewer({ items, index });
  const closeViewer = () => setViewer(null);
  const stepViewer = (delta) => setViewer((v) => {
    if (!v || v.items.length < 2) return v;
    // Wraps both ways, so you can keep pressing one arrow to cycle round
    // rather than hitting a dead end and having to reverse.
    const next = (v.index + delta + v.items.length) % v.items.length;
    return { ...v, index: next };
  });
  const viewerItem = viewer ? viewer.items[viewer.index] : null;

  // Announcement detail (2026-07-29 — "when i click it should give me to
  // detail page of this announcement, similar to delegate detail profile").
  // The cards are deliberately compact (a long message is clamped, media are
  // thumbnails), so there was no way to read a full post — this is the
  // read-everything view, mirroring the delegate profile modal's shape.
  const [detail, setDetail] = useState(null);

  // Arrow keys / Escape while the lightbox is open. Registered once and gated
  // on `viewer` so it never swallows keys when the overlay isn't showing —
  // and NOT while the detail modal alone is open, where arrows do nothing.
  useEffect(() => {
    if (!viewer) return undefined;
    const onKey = (e) => {
      if (e.key === "Escape") closeViewer();
      else if (e.key === "ArrowRight") stepViewer(1);
      else if (e.key === "ArrowLeft") stepViewer(-1);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [viewer]);

  useEffect(() => {
    apiGet("/all-trips").then((r) => {
      // Announcements only make sense for a trip actually happening right
      // now (2026-07-27 — "the announcement should display only in progress
      // trip") — a trip still in Planning has no live itinerary to tag
      // against, and one that's Completed is over; Planning trips ARE still
      // reachable elsewhere (Trips board) for setup work, just not here.
      const list = (r.trips || []).filter((tr) => tr.status === "In progress");
      setTrips(list);
      if (!list.some((tr) => tr.id === selectedTripId)) {
        const fallback = list.some((tr) => tr.id === TRIP_ID) ? TRIP_ID : (list[0]?.id || TRIP_ID);
        setSelectedTripId(fallback);
        saveSelectedTripId(fallback);
      }
    }).catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const [dash, checkpoints, ann] = await Promise.all([
        apiGet(`/trips/${selectedTripId}/dashboard`),
        apiGet(`/trips/${selectedTripId}/checkpoints`).catch(() => null),
        apiGet(`/trips/${selectedTripId}/announcements`),
      ]);
      setTrip(dash.trip || null);
      setItineraryDays(checkpoints?.days || []);
      setAnnouncements(ann.announcements || []);
      // Viewing the page clears this trip's sidebar badge (2026-07-26 — "if i
      // create new post, can you put the number, just like the exception
      // page show 1") — mark AFTER a successful fetch so a failed load
      // doesn't silently clear unseen posts nobody actually saw.
      markAnnouncementsSeenNow(selectedTripId);
    } catch (e) {
      setError(e.message || t("Could not reach the backend."));
    } finally {
      setLoading(false);
    }
  }
  // Pauses while the tab is hidden, catches up on re-show (2026-07-29) — see
  // useVisiblePolling. Keyed on selectedTripId exactly as before, so switching
  // trips still refetches immediately.
  useVisiblePolling(load, 8000, [selectedTripId]);

  function pickTrip(id) {
    setSelectedTripId(id);
    saveSelectedTripId(id);
  }

  function openForm(itineraryItemId = "") {
    setEditingId(null);
    setForm({ title: "", message: "", itineraryItemId });
    setExistingImages([]);
    setRemovedPublicIds(new Set());
    setNewImages([]);
    setExistingVideos([]);
    setRemovedVideoPublicIds(new Set());
    setNewVideos([]);
    setSaveErr(null);
    setFormOpen(true);
  }

  function openEdit(a) {
    setEditingId(a.id);
    setForm({ title: a.title, message: a.message || "", itineraryItemId: a.itineraryItemId || "" });
    setExistingImages(a.images && a.images.length ? a.images : []);
    setRemovedPublicIds(new Set());
    setNewImages([]);
    setExistingVideos(a.videos && a.videos.length ? a.videos : []);
    setRemovedVideoPublicIds(new Set());
    setNewVideos([]);
    setSaveErr(null);
    setFormOpen(true);
  }

  const remainingImageSlots = MAX_IMAGES - (existingImages.length - removedPublicIds.size) - newImages.length;
  const remainingVideoSlots = MAX_VIDEOS - (existingVideos.length - removedVideoPublicIds.size) - newVideos.length;

  function onPickImages(e) {
    const files = Array.from(e.target.files || []).slice(0, Math.max(0, remainingImageSlots));
    e.target.value = "";
    if (!files.length) return;
    setNewImages((prev) => [...prev, ...files.map((file) => ({ file, previewUrl: URL.createObjectURL(file) }))]);
  }

  function removeNewImage(idx) {
    setNewImages((prev) => prev.filter((_, i) => i !== idx));
  }

  function onPickVideos(e) {
    const files = Array.from(e.target.files || []).slice(0, Math.max(0, remainingVideoSlots));
    e.target.value = "";
    if (!files.length) return;
    setNewVideos((prev) => [...prev, ...files.map((file) => ({ file, previewUrl: URL.createObjectURL(file) }))]);
  }

  function removeNewVideo(idx) {
    setNewVideos((prev) => prev.filter((_, i) => i !== idx));
  }

  function toggleRemoveExistingVideo(publicId) {
    setRemovedVideoPublicIds((prev) => {
      const next = new Set(prev);
      if (next.has(publicId)) next.delete(publicId); else next.add(publicId);
      return next;
    });
  }

  function toggleRemoveExisting(publicId) {
    setRemovedPublicIds((prev) => {
      const next = new Set(prev);
      if (next.has(publicId)) next.delete(publicId); else next.add(publicId);
      return next;
    });
  }

  async function post() {
    if (!form.title.trim()) return;
    setSaving(true);
    setSaveErr(null);
    try {
      const body = new FormData();
      body.append("title", form.title.trim());
      body.append("message", form.message.trim());
      if (form.itineraryItemId) body.append("itineraryItemId", form.itineraryItemId);
      newImages.forEach(({ file }) => body.append("images", file));
      newVideos.forEach(({ file }) => body.append("videos", file));
      if (editingId && removedPublicIds.size) body.append("removeImagePublicIds", JSON.stringify([...removedPublicIds]));
      if (editingId && removedVideoPublicIds.size) body.append("removeVideoPublicIds", JSON.stringify([...removedVideoPublicIds]));

      const url = editingId ? `${API_BASE}/announcements/${editingId}` : `${API_BASE}/trips/${selectedTripId}/announcements`;
      const res = await fetch(url, {
        method: editingId ? "PATCH" : "POST",
        headers: { Authorization: `Bearer ${getToken() || ""}` },
        body,
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.message || t("Could not save the announcement."));
      }
      setFormOpen(false);
      load();
    } catch (e) {
      setSaveErr(e.message || t("Could not save the announcement."));
    } finally {
      setSaving(false);
    }
  }

  async function remove(id) {
    setAnnouncements((prev) => prev.filter((a) => a.id !== id));
    try {
      await apiDelete(`/announcements/${id}`);
    } catch {
      load(); // reconcile if the delete actually failed
    }
  }

  const general = announcements.filter((a) => !a.itineraryItemId);
  const byStop = new Map();
  for (const a of announcements) {
    if (!a.itineraryItemId) continue;
    if (!byStop.has(a.itineraryItemId)) byStop.set(a.itineraryItemId, []);
    byStop.get(a.itineraryItemId).push(a);
  }
  const currentCheckpoint = itineraryDays.flatMap((d) => d.checkpoints).find((c) => c.timeState === "current");

  // Day tabs (2026-07-27 — "currently this Beijing trip have 5 day in trip
  // page, so should base on that... if trip page change to 4, then show 4
  // accordingly") — one tab per day the TRIP actually has (itineraryDays
  // comes straight from the same itinerary the Trips board reads, so this
  // always matches whatever's really scheduled), not just days that happen
  // to already have a post. A day with nothing posted yet still gets its
  // own tab — just showing (0) and an empty state once you're on it.
  const sections = [
    ...(general.length > 0 ? [{ key: "general", label: t("General"), count: general.length }] : []),
    ...itineraryDays.map((d) => ({
      key: `day-${d.dayNumber}`, label: `${t("Day")} ${d.dayNumber}`,
      count: d.checkpoints.reduce((n, c) => n + (byStop.get(c.id)?.length || 0), 0),
    })),
  ];
  const sectionKeys = sections.map((s) => s.key).join(",");
  // New-announcement form scoped to whichever day tab you're actually on
  // (2026-07-27 — "on different day tab, if i try to create... should only
  // display the day event... hide day 1,3,4,5 and only show day 2") — General
  // stays available regardless of tab, since it isn't itself a day.
  const formDayNumber = activeSection?.startsWith("day-") ? Number(activeSection.slice(4)) : null;
  const formDays = formDayNumber != null ? itineraryDays.filter((d) => d.dayNumber === formDayNumber) : itineraryDays;
  // Default to today's day tab if it has anything, else General, else
  // whichever tab exists — re-picks whenever the available tabs change
  // (new trip loaded, first post of the day arrives) but leaves the user's
  // own tab choice alone otherwise.
  useEffect(() => {
    const keys = sectionKeys ? sectionKeys.split(",") : [];
    if (activeSection && keys.includes(activeSection)) return;
    const todayKey = trip?.dayOf ? `day-${trip.dayOf}` : null;
    setActiveSection(keys.includes(todayKey) ? todayKey : (keys[0] || null));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sectionKeys, trip?.dayOf]);

  return (
    <div className="page">
      <div className="row between" style={{ alignItems: "flex-start", flexWrap: "wrap", gap: 16 }}>
        <div>
          <div className="page-eyebrow">{t("Trip")}</div>
          <h1 className="page-title">{t("Announcements")}</h1>
          {trip && (
            <p className="page-sub">
              {trip.name} · {t("Day")} {trip.dayOf} {t("of")} {trip.totalDays}
            </p>
          )}
          {currentCheckpoint && (
            <span className="badge badge-assigned" style={{ marginTop: 6, display: "inline-flex" }}>
              <Clock size={12} /> {t("Now")}: {currentCheckpoint.label}{currentCheckpoint.scheduledTime ? ` · ${currentCheckpoint.scheduledTime}` : ""}
            </span>
          )}
        </div>
        {canManage && (
          <button className="btn btn-primary" onClick={() => openForm()}>
            <Plus size={16} /> {t("New announcement")}
          </button>
        )}
      </div>

      {trips.length > 1 && (
        <div className="row" style={{ gap: 8, marginTop: 16, alignItems: "center" }}>
          <span className="muted" style={{ fontSize: 13 }}>{t("Viewing trip")}</span>
          <select className="select" style={{ maxWidth: 260 }} value={selectedTripId} onChange={(e) => pickTrip(e.target.value)}>
            {trips.map((tr) => (
              <option key={tr.id} value={tr.id}>{tr.name}</option>
            ))}
          </select>
        </div>
      )}

      {error && <div style={{ marginTop: 20, color: "var(--st-missing)", fontSize: 13.5 }}>{t(error)}</div>}
      {loading && !announcements.length && <div className="muted" style={{ marginTop: 20 }}>{t("Loading…")}</div>}

      {/* 2026-07-30 ("why is the abc announcement have double announcement?")
          — this used to render whenever announcements.length === 0, with no
          regard for the day-tabs section below it. Once a trip had >1 day
          tab (sections.length > 1), THAT section renders its OWN "No
          announcements yet for this day" empty state for whichever day is
          active — so a trip with zero announcements showed both empty-state
          cards stacked, reading as a duplicate. This one is now only for
          the untabbed case (a trip with no day-grouping at all); the day
          tabs' own empty state (below) covers the tabbed case. */}
      {!loading && announcements.length === 0 && sections.length <= 1 && (
        <div className="card" style={{ marginTop: 20, padding: 24, textAlign: "center" }}>
          <Megaphone size={28} color="var(--ink-3)" />
          <p className="muted" style={{ marginTop: 8, fontSize: 13.5 }}>{t("No announcements yet for this trip.")}</p>
        </div>
      )}

      {/* ---- Day tabs (2026-07-26) ------------------------------------------ */}
      {sections.length > 1 && (
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 20 }}>
          {sections.map((s) => (
            <button
              key={s.key}
              className="btn"
              onClick={() => setActiveSection(s.key)}
              style={{
                background: activeSection === s.key ? "var(--scc-red-tint)" : "transparent",
                color: activeSection === s.key ? "var(--scc-red)" : "var(--ink-2)",
                border: `1px solid ${activeSection === s.key ? "var(--scc-red-tint-2)" : "var(--line)"}`,
              }}
            >
              {s.label} <span className="muted" style={{ fontSize: 11.5 }}>({s.count})</span>
            </button>
          ))}
        </div>
      )}

      {/* ---- General (untagged) announcements ------------------------------ */}
      {activeSection === "general" && general.length > 0 && (
        <div style={{ marginTop: 20 }}>
          {sections.length <= 1 && <h2 style={{ fontSize: 14, marginBottom: 10 }}>{t("General")}</h2>}
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {general.map((a) => <AnnouncementCard key={a.id} a={a} canManage={canManage} onDelete={remove} onEdit={openEdit} onView={openViewer} onOpen={setDetail} t={t} />)}
          </div>
        </div>
      )}

      {/* ---- Grouped by itinerary stop — only the selected day's tab -------- */}
      {itineraryDays.filter((day) => activeSection === `day-${day.dayNumber}`).map((day) => {
        const stopsWithPosts = day.checkpoints.filter((c) => byStop.has(c.id));
        return (
        <div key={day.dayNumber} style={{ marginTop: 20 }}>
          {sections.length <= 1 && <h2 style={{ fontSize: 14, marginBottom: 10 }}>{t("Day")} {day.dayNumber}</h2>}
          {stopsWithPosts.length === 0 ? (
            <div className="card" style={{ padding: 24, textAlign: "center" }}>
              <Megaphone size={28} color="var(--ink-3)" />
              <p className="muted" style={{ marginTop: 8, fontSize: 13.5 }}>{t("No announcements yet for this day.")}</p>
            </div>
          ) : stopsWithPosts.map((c) => (
            <div key={c.id} style={{ marginBottom: 16 }}>
              <div className="row" style={{ gap: 6, alignItems: "center", marginBottom: 8 }}>
                <Clock size={13} color="var(--ink-3)" />
                <span style={{ fontSize: 13, fontWeight: 600 }}>{c.label}</span>
                {c.scheduledTime && <span className="muted" style={{ fontSize: 12.5 }}>· {c.scheduledTime}</span>}
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 10, paddingLeft: 19 }}>
                {byStop.get(c.id).map((a) => <AnnouncementCard key={a.id} a={a} canManage={canManage} onDelete={remove} onEdit={openEdit} onView={openViewer} onOpen={setDetail} t={t} />)}
              </div>
            </div>
          ))}
        </div>
        );
      })}

      {/* ---- New announcement modal ------------------------------------------ */}
      {formOpen && (
        <div
          style={{ position: "fixed", inset: 0, background: "rgba(16,24,40,0.45)", display: "grid", placeItems: "center", padding: 20, zIndex: 60 }}
          onClick={(e) => { if (e.target === e.currentTarget) setFormOpen(false); }}
        >
          <div className="card" style={{ width: "min(520px, 100%)", maxHeight: "88vh", overflowY: "auto", padding: 24 }}>
            <div className="row between" style={{ marginBottom: 16 }}>
              <h2 style={{ fontSize: 16 }}>{editingId ? t("Edit announcement") : t("New announcement")}</h2>
              <button onClick={() => setFormOpen(false)} style={{ background: "none", border: "none", color: "var(--ink-3)", display: "flex" }} aria-label={t("Close")}>
                <X size={18} />
              </button>
            </div>

            <label className="field-label">{t("Tag to an itinerary stop (optional)")}</label>
            <select className="select" style={{ width: "100%", marginTop: 4, marginBottom: 12 }} value={form.itineraryItemId}
              onChange={(e) => {
                const id = e.target.value;
                // Auto-fill title from the stop's own label/time (2026-07-26
                // — "so user just need to put the image can already") —
                // picking a stop shouldn't force typing a title by hand.
                // Always overwrites (rather than only-if-empty) so switching
                // between stops keeps the title in sync with whichever one's
                // actually selected; still fully editable afterwards.
                const stop = id ? itineraryDays.flatMap((d) => d.checkpoints).find((c) => c.id === id) : null;
                setForm((f) => ({
                  ...f,
                  itineraryItemId: id,
                  title: stop ? `${stop.label}${stop.scheduledTime ? ` · ${stop.scheduledTime}` : ""}` : "",
                }));
              }}>
              <option value="">{t("General — not tied to a specific stop")}</option>
              {formDays.map((day) => (
                <optgroup key={day.dayNumber} label={`${t("Day")} ${day.dayNumber}`}>
                  {day.checkpoints.map((c) => (
                    <option key={c.id} value={c.id}>{c.label}{c.scheduledTime ? ` · ${c.scheduledTime}` : ""}</option>
                  ))}
                </optgroup>
              ))}
            </select>

            <label className="field-label">{t("Title")}</label>
            <input className="input" style={{ marginTop: 4, marginBottom: 12 }} value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })} />

            <label className="field-label">{t("Message (optional)")}</label>
            <textarea className="input" rows={3} style={{ marginTop: 4, marginBottom: 12, resize: "vertical" }} value={form.message}
              placeholder={t("Leave blank for an image-only post")}
              onChange={(e) => setForm({ ...form, message: e.target.value })} />

            <label className="field-label">{t("Images (optional)")} — {t("up to")} {MAX_IMAGES}</label>
            <div style={{ marginTop: 4, marginBottom: 16 }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                {existingImages.map((img) => {
                  const marked = removedPublicIds.has(img.publicId);
                  return (
                    <div key={img.publicId} style={{ position: "relative", opacity: marked ? 0.4 : 1 }}>
                      <img src={img.url} alt="" style={{ width: 84, height: 84, objectFit: "cover", borderRadius: "var(--r-sm)" }} />
                      <button
                        onClick={() => toggleRemoveExisting(img.publicId)}
                        style={{ position: "absolute", top: 4, right: 4, background: "rgba(0,0,0,0.6)", border: "none", borderRadius: "50%", width: 20, height: 20, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
                        aria-label={marked ? t("Keep image") : t("Remove image")}
                        title={marked ? t("Keep image") : t("Remove image")}
                      >
                        {marked ? <Plus size={11} /> : <X size={11} />}
                      </button>
                    </div>
                  );
                })}
                {newImages.map((img, idx) => (
                  <div key={img.previewUrl} style={{ position: "relative" }}>
                    <img src={img.previewUrl} alt="" style={{ width: 84, height: 84, objectFit: "cover", borderRadius: "var(--r-sm)" }} />
                    <button
                      onClick={() => removeNewImage(idx)}
                      style={{ position: "absolute", top: 4, right: 4, background: "rgba(0,0,0,0.6)", border: "none", borderRadius: "50%", width: 20, height: 20, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
                      aria-label={t("Remove image")}
                    >
                      <X size={11} />
                    </button>
                  </div>
                ))}
                {remainingImageSlots > 0 && (
                  <label className="btn btn-ghost" style={{ width: 84, height: 84, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", gap: 2, padding: 0 }}>
                    <ImagePlus size={18} />
                    <span style={{ fontSize: 10.5 }}>{t("Add")}</span>
                    <input type="file" accept="image/*" multiple onChange={onPickImages} style={{ display: "none" }} />
                  </label>
                )}
              </div>
            </div>

            <label className="field-label">{t("Videos (optional)")} — {t("up to")} {MAX_VIDEOS}</label>
            <div style={{ marginTop: 4, marginBottom: 16 }}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                {existingVideos.map((v) => {
                  const marked = removedVideoPublicIds.has(v.publicId);
                  return (
                    <div key={v.publicId} style={{ position: "relative", opacity: marked ? 0.4 : 1 }}>
                      <video src={v.url} style={{ width: 84, height: 84, objectFit: "cover", borderRadius: "var(--r-sm)", background: "#000" }} muted />
                      <Video size={16} style={{ position: "absolute", bottom: 4, left: 4, color: "#fff", pointerEvents: "none" }} />
                      <button
                        onClick={() => toggleRemoveExistingVideo(v.publicId)}
                        style={{ position: "absolute", top: 4, right: 4, background: "rgba(0,0,0,0.6)", border: "none", borderRadius: "50%", width: 20, height: 20, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
                        aria-label={marked ? t("Keep video") : t("Remove video")}
                        title={marked ? t("Keep video") : t("Remove video")}
                      >
                        {marked ? <Plus size={11} /> : <X size={11} />}
                      </button>
                    </div>
                  );
                })}
                {newVideos.map((v, idx) => (
                  <div key={v.previewUrl} style={{ position: "relative" }}>
                    <video src={v.previewUrl} style={{ width: 84, height: 84, objectFit: "cover", borderRadius: "var(--r-sm)", background: "#000" }} muted />
                    <Video size={16} style={{ position: "absolute", bottom: 4, left: 4, color: "#fff", pointerEvents: "none" }} />
                    <button
                      onClick={() => removeNewVideo(idx)}
                      style={{ position: "absolute", top: 4, right: 4, background: "rgba(0,0,0,0.6)", border: "none", borderRadius: "50%", width: 20, height: 20, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
                      aria-label={t("Remove video")}
                    >
                      <X size={11} />
                    </button>
                  </div>
                ))}
                {remainingVideoSlots > 0 && (
                  <label className="btn btn-ghost" style={{ width: 84, height: 84, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", gap: 2, padding: 0 }}>
                    <Video size={18} />
                    <span style={{ fontSize: 10.5 }}>{t("Add")}</span>
                    <input type="file" accept="video/*" multiple onChange={onPickVideos} style={{ display: "none" }} />
                  </label>
                )}
              </div>
            </div>

            {saveErr && <div style={{ color: "var(--st-missing)", fontSize: 12.5, marginBottom: 12 }}>{saveErr}</div>}

            <div className="row" style={{ gap: 10, justifyContent: "flex-end" }}>
              <button className="btn btn-ghost" onClick={() => setFormOpen(false)} disabled={saving}>{t("Cancel")}</button>
              <button className="btn btn-primary" onClick={post} disabled={saving || !form.title.trim()}>
                {saving ? (editingId ? t("Saving…") : t("Posting…")) : (editingId ? t("Save changes") : t("Post announcement"))}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ---- Media lightbox (2026-07-27) -------------------------------------
       * "give me option to enlarge the photo when click and give video upload
       * also, when click can view the video" — one overlay reused for both;
       * a video gets real playback controls instead of just a bigger <img>. */}
      {viewerItem && (
        <div
          style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)", display: "grid", placeItems: "center", padding: 24, zIndex: 70 }}
          onClick={closeViewer}
        >
          <button
            onClick={closeViewer}
            style={{ position: "absolute", top: 20, right: 20, background: "rgba(255,255,255,0.12)", border: "none", borderRadius: "50%", width: 36, height: 36, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
            aria-label={t("Close")}
          >
            <X size={20} />
          </button>

          {/* Prev/next (2026-07-29) — only rendered when there's more than one
              item, so a single-photo post doesn't get arrows that go nowhere.
              Arrow keys do the same thing (see the keydown effect above).
              stopPropagation matters on every control in here: the backdrop's
              own onClick closes the overlay, so without it, stepping forward
              would immediately dismiss the thing you're trying to look at. */}
          {viewer.items.length > 1 && (
            <>
              <button
                onClick={(e) => { e.stopPropagation(); stepViewer(-1); }}
                aria-label={t("Previous")}
                style={{ position: "absolute", left: 20, top: "50%", transform: "translateY(-50%)", background: "rgba(255,255,255,0.12)", border: "none", borderRadius: "50%", width: 44, height: 44, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
              >
                <ChevronLeft size={24} />
              </button>
              <button
                onClick={(e) => { e.stopPropagation(); stepViewer(1); }}
                aria-label={t("Next")}
                style={{ position: "absolute", right: 20, top: "50%", transform: "translateY(-50%)", background: "rgba(255,255,255,0.12)", border: "none", borderRadius: "50%", width: 44, height: 44, color: "#fff", display: "grid", placeItems: "center", cursor: "pointer" }}
              >
                <ChevronRight size={24} />
              </button>
              <div
                style={{ position: "absolute", bottom: 24, left: "50%", transform: "translateX(-50%)", background: "rgba(0,0,0,0.55)", color: "#fff", fontSize: 12.5, fontWeight: 600, padding: "5px 12px", borderRadius: 999 }}
              >
                {viewer.index + 1} / {viewer.items.length}
              </div>
            </>
          )}

          {viewerItem.kind === "video" ? (
            /* `key` forces a fresh <video> per item — without it, React reuses
               the element and stepping to another video keeps the previous
               one's playback position and paused state. */
            <video key={viewerItem.url} src={viewerItem.url} controls autoPlay style={{ maxWidth: "min(90vw, 900px)", maxHeight: "85vh", borderRadius: "var(--r-md)" }} onClick={(e) => e.stopPropagation()} />
          ) : (
            <img src={viewerItem.url} alt="" style={{ maxWidth: "min(90vw, 900px)", maxHeight: "85vh", borderRadius: "var(--r-md)", objectFit: "contain" }} onClick={(e) => e.stopPropagation()} />
          )}
        </div>
      )}

      {/* ---- Announcement detail (2026-07-29) --------------------------------
       * "when i click it should give me to detail page of this announcement,
       * similar to delegate detail profile" — a modal rather than a route, to
       * match how a delegate profile opens from the roster: you keep your day
       * tab and scroll position, and closing puts you straight back. Shows the
       * full untruncated message, which stop it's tagged to, who posted it and
       * when, and every photo/video at a usable size (still clicking through
       * to the lightbox above for full-screen). */}
      {detail && (
        <AnnouncementDetailModal
          a={detail}
          canManage={canManage}
          itineraryDays={itineraryDays}
          onClose={() => setDetail(null)}
          onView={openViewer}
          onEdit={(x) => { setDetail(null); openEdit(x); }}
          onDelete={(id) => { setDetail(null); remove(id); }}
          t={t}
        />
      )}
    </div>
  );
}

