/* =============================================================================
 *  OWNED BY:  InsightMetrics (JQ)
 *  PART OF:   MusterGo base — Admin Dashboard, Auth, Accounts & Permissions
 *
 *  TEAMMATES: please DO NOT edit this file. It is part of JQ's foundation that
 *  the rest of the app is built on. Add your OWN feature files instead, and see
 *  README/INTEGRATION_NOTES.md for what's yours vs. what's off-limits.
 * ============================================================================= */
/**
 * MusterGo — permissions: the single source of truth.
 *
 * BOTH the frontend and the backend import this file, so a new permission is a
 * ONE-LINE change here. Keep this file plain data/ESM only — no React, no
 * browser APIs, no Node-only APIs — because it's imported on both sides.
 *
 * TO ADD A NEW PERMISSION:
 *   1. Add one entry to PERMISSIONS below (key, label, desc, chip, default,
 *      group). → the checkbox appears in the New/Edit account modal
 *      automatically (grouped under `group`'s section), the chip appears in
 *      the accounts table automatically, the backend accepts/stores/returns
 *      it automatically.
 *   2. ENFORCE it where it matters (this part is always manual, by design):
 *      → backend/server.js:  wrap the route with requirePermission("yourKey")
 *      → frontend UI:        hide the control with getPermissions().yourKey
 *
 * Fields:
 *   key     — the permission id used in code and storage (camelCase)
 *   label   — checkbox title shown to the user
 *   desc    — one-line description under the checkbox
 *   chip    — short label shown in the accounts table
 *   default — the value used for an account whose STORED permissions predate
 *             this key (see cleanPermissions below) — also what a brand-new
 *             account's checkbox starts as. Action permissions (things that
 *             let you CHANGE data) default closed; view permissions (things
 *             that just let you SEE a page) default open, so rolling out a
 *             new page-level toggle never silently locks out staff who could
 *             already reach that page before the toggle existed — an admin
 *             opts a specific account OUT going forward, rather than every
 *             existing account being opted out by default.
 *   group   — "action" (a capability, enforced by the backend too) |
 *             "desktopView" (can this account see this desktop page/route —
 *             frontend-only gating, alongside whatever action permission
 *             actually protects the writes on that page) | "mobileView"
 *             (same, for the /mobile/* routes). Purely groups the checkboxes
 *             in Account control into labelled sections — carries no other
 *             meaning.
 *   parent  — (optional) another permission's `key`. Purely a RENDERING hint
 *             for Account control — indents this checkbox under its parent's
 *             ("dashboard -> Delegate/Analytics", "Home -> QR + Face Scanner/
 *             Exception") so related toggles read as a group. Carries no
 *             enforcement meaning — a child is NOT auto-disabled if its
 *             parent is unticked; each key is still checked independently
 *             everywhere it's actually enforced.
 *   adminOnly — (optional) this permission is never rendered as a toggle for
 *             a Staff account — only Admins get it (Admin already bypasses
 *             every check regardless of what's stored). Used for things that
 *             should never be individually grantable to Staff, like Account
 *             control access.
 */
export const PERMISSIONS = [
  // ---- Action permissions: capabilities enforced by the backend --------
  {
    key: "manageDelegates",
    label: "Manage delegates",
    desc: "Add, edit and delete delegates (including delete all)",
    chip: "Delegates",
    default: true,
    group: "action",
  },
  {
    key: "exportData",
    label: "Export data",
    desc: "Download the attendance report as Excel",
    chip: "Export",
    default: false,
    group: "action",
    parent: "manageDelegates",
  },
  {
    key: "viewDelegateDetails",
    label: "View delegate details",
    desc: "Open a delegate's full profile — phone number, last known location, and checkpoint timeline",
    chip: "Delegate details",
    // This view had no dedicated gate at all before (anyone who could see the
    // roster row could open the full profile too) — default TRUE so no
    // existing staff account silently loses access the moment this
    // permission starts being checked; an admin narrows it per-account
    // going forward (2026-07-25).
    default: true,
    group: "action",
    parent: "manageDelegates",
  },
  {
    key: "manageTrips",
    label: "Manage trips",
    desc: "Edit trips, coaches and itineraries on the Trips board",
    chip: "Trips",
    default: false,
    group: "action",
  },
  {
    key: "manageDocuments",
    label: "Manage documents",
    desc: "Upload/parse documents and confirm extracted delegates onto the trip (Onboarding)",
    chip: "Documents",
    // Carved out of manageDelegates (which used to gate this too) — default
    // TRUE so no existing staff account silently loses upload/confirm access
    // the moment this permission starts being checked; an admin can now
    // narrow it per-account going forward.
    default: true,
    group: "action",
  },
  {
    key: "manageScanner",
    label: "Manage scanner",
    desc: "Perform Face/QR check-ins from a signed-in session (the passwordless entrance kiosk is unaffected either way)",
    chip: "Scanner",
    // Check-in used to be open to any signed-in account with no dedicated
    // permission at all — default TRUE for the same "don't silently revoke
    // existing capability" reason as manageDocuments above.
    default: true,
    group: "action",
  },
  {
    key: "manageExceptions",
    label: "Manage exceptions",
    desc: "Log, resolve, delete tickets and perform manual attendance overrides",
    chip: "Exceptions",
    default: false,
    group: "action",
  },
  {
    key: "manageAnnouncements",
    label: "Manage announcements",
    desc: "Post, edit and delete trip announcements",
    chip: "Announcements",
    // Genuinely new capability (2026-07-27 — "set permission so only admin
    // can update/delete, staff can only view, but give the permission
    // access") — default FALSE, same reasoning as manageTrips/
    // manageExceptions above: a Staff account starts view-only (viewAnnouncements
    // already covers that) and an admin opts specific accounts IN to also
    // post/edit/delete, rather than this being hardcoded admin-only.
    default: false,
    group: "action",
  },
  {
    key: "manageAccounts",
    label: "Manage accounts",
    desc: "Access Account control — create, edit and delete accounts",
    chip: "Accounts",
    default: false,
    group: "action",
    // Never offered as a Staff toggle — only a real Admin should ever be
    // able to grant/revoke everyone else's access (see AccountControlPage.jsx,
    // which filters this out of the Staff-role form entirely).
    adminOnly: true,
  },

  // ---- Desktop web views: which /routes this account can even see -------
  // Ordered and grouped to match the actual left sidebar (Sidebar.jsx),
  // top to bottom: Dashboard, Trips, Documents, Exceptions, MusterChat —
  // then Account control (its own manageAccounts permission, admin-only,
  // not listed in this group at all). Announcements and Face + QR scan are
  // NOT in that main list — see their own comments below for where (or
  // whether) they actually show up right now.
  {
    key: "viewDashboard",
    label: "Main dashboard",
    desc: "See the live attendance dashboard (Screen 2)",
    chip: "Dashboard",
    default: true,
    group: "desktopView",
  },
  {
    key: "viewDelegates",
    label: "Delegate",
    desc: "See the Dashboard's Delegate tab — the full roster table",
    chip: "Delegate",
    default: true,
    group: "desktopView",
    parent: "viewDashboard",
  },
  {
    key: "viewHistory",
    label: "History logs",
    desc: "See the full date-stamped activity audit trail",
    chip: "History",
    default: true,
    group: "desktopView",
    // Nested two levels deep (Dashboard -> Delegate -> History logs) per
    // request — Account control's rendering supports this recursively, see
    // AccountControlPage.jsx's PermRow.
    parent: "viewDelegates",
  },
  // NOTE: "viewAnalytics" was removed 2026-07-27 ("staff can view delegate +
  // checkpoint, admin views all, regardless of account control — so remove
  // analytics from permission"). The Dashboard's Analytics / Room Management /
  // Staff operations tabs are now role-based (admin only), not per-account
  // toggles. cleanPermissions() below only keeps keys listed here, so any
  // stored viewAnalytics value is silently dropped on next read — no
  // migration needed.
  {
    key: "viewTrips",
    label: "Trips",
    desc: "See the Trips & coach management board",
    chip: "Trips",
    default: true,
    group: "desktopView",
  },
  {
    key: "viewDocuments",
    label: "Documents",
    desc: "See document parsing + boarding passes (Onboarding)",
    chip: "Documents",
    default: true,
    group: "desktopView",
  },
  {
    key: "viewExceptions",
    label: "Exceptions",
    desc: "See the exception ticket inbox",
    chip: "Exceptions",
    default: true,
    group: "desktopView",
  },
  {
    // Gates TWO things together, same as mobile's scanner permission: the
    // floating chat bubble (every route) AND the "MusterChat" sidebar nav
    // item (/assistant, Vance's full inbox) — not just the bubble alone.
    key: "viewChatbot",
    label: "Chatbot",
    desc: "See the floating Trip Assistant chat bubble and the MusterChat sidebar item",
    chip: "Chatbot",
    // Was open to every signed-in user with no gate at all — default TRUE so
    // nobody silently loses the assistant when this permission starts being
    // checked.
    default: true,
    group: "desktopView",
  },
  {
    // NOT in the main sidebar list — it's its own icon in the footer utility
    // row, beside the language/theme toggles (2026-07-27, "add another box
    // beside the translation button for announcement"). Listed here after
    // the main nav items since that's where it visually sits, off to the side.
    key: "viewAnnouncements",
    label: "Announcements",
    desc: "See the trip Announcements page (its own footer icon, not the main nav list)",
    chip: "Announcements",
    // Brand-new page/capability (2026-07-26) — default TRUE per the original
    // requirement ("all logged-in Staff and Admin accounts can view"); an
    // admin can still narrow it per-account afterwards, same as every other
    // view toggle here.
    default: true,
    group: "desktopView",
  },
  // NOTE: the desktop "Face + QR scan" permission (viewScanner) was removed
  // 2026-08-02 ("remove face + qr scanner on desktop, include the
  // permission") — it had no nav entry point at all (Sidebar.jsx's link was
  // commented out 2026-07-27, and /scanner redirected straight to
  // /dashboard), so keeping a toggle for it was pure clutter. If a desktop
  // scanner is ever restored, re-add it here fresh rather than un-deleting
  // this comment.

  // ---- Mobile views: which /mobile/* routes this account can see -------
  // Ordered and grouped to match the actual bottom tab bar in
  // MobileLayout.jsx, left to right: Home, Ops (Attendance + Exception +
  // Trips, all folded into ONE tab/screen), QR scanner, Face scanner, Manual
  // check-in, then Chatbot last since its floating bubble isn't a tab at all.
  // The always-visible Me tab is never listed here — it's account settings,
  // not a gateable feature view.
  {
    key: "viewMobileHome",
    label: "Home",
    desc: "See the mobile Home tab (trip + per-coach live status)",
    chip: "Home",
    default: true,
    group: "mobileView",
  },
  {
    // Attendance + Exception + Trips are three permissions but ONE nav tab:
    // MobileLayout.jsx shows a single "Ops" tab whenever any of the three is
    // on (MobileOpsPage.jsx composes Attendance/Trips together; Exception is
    // a card reached from within Ops) — there's no separate "Attendance tab"
    // or "Trips tab" to see on the phone.
    key: "viewMobileAttendance",
    label: "Attendance",
    desc: "See the Attendance side of the mobile Ops tab (full roster on the go)",
    chip: "Attendance",
    default: true,
    group: "mobileView",
  },
  {
    key: "viewMobileIssues",
    label: "Exception",
    desc: "See the mobile Issues/Exceptions tracking card inside the Ops tab",
    chip: "Mobile issues",
    default: true,
    group: "mobileView",
    parent: "viewMobileAttendance",
  },
  {
    key: "viewMobileTrips",
    label: "Trips",
    desc: "See the Trips side of the mobile Ops tab",
    chip: "Mobile trips",
    default: true,
    group: "mobileView",
    parent: "viewMobileAttendance",
  },
  // NOTE: "viewMobileAllTrips" was removed 2026-08-02 ("on mobile, should
  // hide the trip that is not in progress status, for simplicity" +
  // "this can remove") — MobileTripsPage.jsx no longer reads this permission
  // at all; `canSeeAllTrips` is hardcoded `false` there now, so every account
  // (including admins) only ever sees the In-progress trip on mobile.
  // Keeping a toggle for a permission the code no longer checks would just
  // be a lie in the Account control editor.
  {
    // Split from the old combined "viewMobileScanner" 2026-08-02 ("mobile
    // view: ... qr code scanner / face scanner / manual") into three
    // independent permissions — QR, Face, and Manual can now be granted or
    // revoked separately instead of all-or-nothing. Each still gates its own
    // route directly (App.jsx), so even if the in-page mode-switcher shows a
    // link to a mode this account lacks, following it lands on that route's
    // own ViewGate, not the actual scanner.
    key: "viewMobileScannerQr",
    label: "QR code scanner",
    desc: "See the mobile QR entrance-scanner tab",
    chip: "QR scanner",
    default: true,
    group: "mobileView",
  },
  {
    key: "viewMobileScannerFace",
    label: "Face scanner",
    desc: "See the mobile Face entrance-scanner tab",
    chip: "Face scanner",
    default: true,
    group: "mobileView",
  },
  {
    // Not its own nav tab — reached from inside the QR/Face scanner screens
    // as a fallback for when a scan won't cooperate (see MobileScannerPage.jsx).
    key: "viewMobileScannerManual",
    label: "Manual",
    desc: "See manual check-in, reached from inside the QR/Face scanner screens",
    chip: "Manual check-in",
    default: true,
    group: "mobileView",
  },
  {
    // Not a tab — a floating chat bubble rendered on every /mobile/* route,
    // independent of which tab is active.
    key: "viewMobileChatbot",
    label: "Chatbot",
    desc: "See the floating Trip Assistant chat bubble on mobile",
    chip: "Mobile chatbot",
    default: true,
    group: "mobileView",
  },
];

/** Just the keys, e.g. ["manageDelegates", "exportData", "manageAccounts"]. */
export const PERM_KEYS = PERMISSIONS.map((p) => p.key);

/** Default tick state for a new account, e.g. { manageDelegates: true, ... }. */
export const DEFAULT_PERMISSIONS = Object.fromEntries(
  PERMISSIONS.map((p) => [p.key, !!p.default])
);

/**
 * Coerce any input object into a clean { key: boolean } for every known key.
 * A key EXPLICITLY present in `input` (even `false`) always wins — that's a
 * real, saved admin decision. A key ABSENT from `input` (an account saved
 * before that permission existed) falls back to its declared `default`, not
 * a hardcoded false — see the `default` field doc above for why.
 */
export function cleanPermissions(input) {
  const out = {};
  for (const p of PERMISSIONS) {
    const present = !!input && Object.prototype.hasOwnProperty.call(input, p.key);
    out[p.key] = present ? !!input[p.key] : !!p.default;
  }
  return out;
}
